### ISSUE TITLE
Support custom Validators types

### ISSUE THREAD

**Issue by LauraRe** [keycloakify/keycloakify#139]
**Problem**:
When customizing UserProfileFormFields in RegisterUserProfile we are using the useFormValidationSlice function but it is not possible to send in custom params:
```typescript
export declare function useFormValidationSlice(params: {
  kcContext: {
    messagesPerField: Pick<KcContextBase.Common["messagesPerField"], "existsError" | "get">;
    profile: {
      attributes: Attribute[];
    };
    passwordRequired: boolean;
    realm: {
      registrationEmailAsUsername: boolean;
    };
    locale?: {
      currentLanguageTag: KcLanguageTag;
    };
  };
  /** NOTE: Try to avoid passing a new ref every render for better performances. */
  passwordValidators?: Validators;
}): {
  formValidationState: {
    fieldStateByAttributeName: {
      [k: string]: {
        value: string;
        displayableErrors: {
          errorMessage: JSX.Element;
          errorMessageStr: string;
          validatorName: "double" | "pattern" | "length" | "email" | "options" | "integer" | "up-immutable-attribute" | "up-attribute-required-by-metadata-value" | "up-username-has-value" | "up-duplicate-username" | "up-username-mutation" | "up-email-exists-as-username" | "up-blank-attribute-value" | "up-duplicate-email" | "local-date" | "person-name-prohibited-characters" | "uri" | "username-prohibited-characters" | "_compareToOther" | undefined;
        }[];
      };
    };
    isFormSubmittable: boolean;
  };
  formValidationReducer: import("react").Dispatch<{
    action: "update value";
    name: string;
    newValue: string;
  } | {
    action: "focus lost";
    name: string;
  }>;
  attributesWithPassword: Attribute[];
};
```
**What we need**:
We would need to pass our own Attribute[] object so that we can use our own Validators (extended from the base types).

**Why**:
We are adding a checkbox field which will have a boolean validator.

Any suggestion on how can we achieve this?

**Comment by garronej** [comment]
Hi @LauraRe,  
Why not using an option validator?  
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/6702424/179782927-cf64848d-ed21-48fc-9198-88df59534e1d.png">

You could render it however you'd like, Radio, Toggle...

**Comment by LauraRe** [comment]
Hi @garronej, thanks for the suggestion!

Yes, I think we can work with that for now but I think it would be nice to add support for custom validators on Keycloakify as well since Keycloak allows to create custom ones. From the [docs](https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/users/user-profile.adoc): "Define validation rules on a per-attribute basis by leveraging the built-in validators or writing custom ones"

**Comment by garronej** [comment]
> well since Keycloak allows to create custom ones. From the [docs](https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/users/user-profile.adoc): "Define validation rules on a per-attribute basis by leveraging the built-in validators or writing custom ones"   

That's interesting, thank you for bringing it up!  
In this case then, yes, Keycloakify should support custom validator.  
Unfortunately, I don't have the bandwidth to do it right now.  
I'll leave this issue open so see if it gains traction.  

Anyway PR are welcome but this isn't that easy to integrate with good typing.

**Comment by marziman** [comment]
@garronej @LauraRe 
we have a custom validator to avoid duplicate phoneNr entries. When we activate it, the registration pages gets destroyed and is white.
We are running on older keycloakify v4.14.2-beta.0

We are struggling to get the validator activated without killing the registration page. It seems we must include this page?
https://github.com/InseeFrLab/keycloakify/blob/57932386bff6bb41dff58e154a098d9e92239f15/src/lib/components/RegisterUserProfile.tsx

Your guidance would be appreciated @garronej . Thanks

**Comment by garronej** [comment]
@marziman please open another issue what you are describing isn't related to this issue's feature request.  
Thanks.

**Comment by garronej** [comment]
Despite not supporting custom validator types all validators of keycloak are supported in keycloakify 10 now
