### ISSUE TITLE
Additional FTL folder

### ISSUE THREAD

**Issue by ferretwithaberet** [keycloakify/keycloakify#148]
Designate a folder which's content will get copied directly in the theme. This will be useful for users that also want to overwrite the Welcome theme.

Something like: `<PROJECT_ROOT>/additional_ftl/welcome/index.ftl`

**Comment by garronej** [comment]
Ok, i'll try to make an option of it in keycloakify v6 but it may take time before it's available. I am on vacation.

**Comment by marziman** [comment]
Amazing! We also have the welcome page customized and are for now just opening the .jar file each time.
Many thanks @garronej !

**Comment by garronej** [comment]
Sorry it hasn't been done yet. I'll do it soon.

**Comment by garronej** [comment]
Even better would be to support customizing the welcome theme.  
I leave this here for future reference.  

https://keycloak.discourse.group/t/welcome-screen-theme/91/3?u=garronej

**Comment by garronej** [comment]
@ferretwithaberet @RhysOnlyBetter.  
I just introduced a new hook that enable to transform the `dist_keycloak` directory before the .jar is created.  
This should enable you to copy over the extra file that you need.  
See: https://docs.keycloakify.dev/build-options#postbuild-hook  

I know this is not Wellcome theme support but at least it opens a way that should enable to make it work on your side.
