### ISSUE TITLE
Feature request: Increase testibility for i18n

### ISSUE THREAD

**Issue by oleh-hutsalo-ks** [keycloakify/keycloakify#176]
You did a great work with `useI18n()` hook and that made development much smoother.
But now I am facing difficulties with migration from v5.
My unit tests now missing `i18n` object which is passed as a prop now. It would be really handy if you exported [this function](https://github.com/InseeFrLab/keycloakify/blob/v6.3.6/src/lib/i18n/index.tsx#L88-L176) from `keycloakify/lib/i18n`

Then it would be possible to write unit tests like this

```javascript
import { screen, render } from '@testing-library/react'
import { getI18n } from 'keycloakify/lib/i18n'
import { kcContext } from './mocks'


test('should render a title', () => {
 const i18n = await getI18n({ kcContext, extraMessages: {en: {myTitle: "Test title"}} })
 render(<MyComponent i18n={i18n} titleKey="myTitle" />)
 expect(screen.getByText('Test title')).toBeInTheDocument()
})

```

or like this

```javascript
import { screen, render } from '@testing-library/react'
import { getI18nSync } from 'keycloakify/lib/i18n'
import { kcContext } from './mocks'

const i18n = getI18nSync({ kcContext, extraMessages: {en: {myTitle: "Test title"}} })

test('should render a title', () => {
 render(<MyComponent i18n={i18n} titleKey="myTitle" />)
 expect(screen.getByText('Test title')).toBeInTheDocument()
})

```

**Comment by garronej** [comment]
Hi @oleh-hutsalo-ks,  

Thanks for reaching out, and for your kind words.  
I see you are a man of culture as well, I have the same testability problem in my own use case.  

I'll try to figure something out but I am very busy so I can't tell you when it lands.  

PR are welcome but not expected.   

Best,

**Comment by garronej** [comment]
I feel like I can close this now.  
In v7.7 we have a good storybook support which in turn should resolve testability issues.
