### ISSUE TITLE
Publish a tutorial on Youtube

### ISSUE THREAD

**Issue by garronej** [keycloakify/keycloakify#188]
If someone would like to shoot a Keycloakify video tutorial, it would greatly help beginners create their first Keycloak theme.  

I think such a video would get a some views.  

Of course you can publish it from your Youtube channel.

**Comment by manodupont** [comment]
+1.

Although I think there is a huge potential, i literaly think that its easier to just fork keycloak and just start in dev mode and do some freemarker edition.

**Comment by garronej** [comment]
>  i literaly think that its easier to just fork keycloak and just start in dev mode and do some freemarker edition.  

I think that isn't the case. But I'm obviously biaised. So [here is a quote from the Keycloak support team]( i literaly think that its easier to just fork keycloak and just start in dev mode and do some freemarker edition.).  

> For me its not clear what the project. Is it a FreeMarker generator ? Converter? Will i code react component and it will just magically be converted into *.ftl that fits into keycloak ecosystem ?  

It's a login theme generator for Keycloak. It generates a `.jar` that you'll be able to import in Keycloak and you'll be able to select the theme in the Keycloak admin web UI.  
<img width="672" alt="image" src="https://user-images.githubusercontent.com/6702424/198617231-dab338fc-cdac-41cf-a9f9-f8a51c72727b.png">  

You don't need to understand how it works to use it.  
How it work in practice is it injects in every pages an `.ftl` script that convert the FreeMarker data model into the declaration of a  global JavaScript objet, `kcContext` that you'll be able to use on the fontend to construct your page.  

You can try to login in [this app](https://datalab.sspcloud.fr/), open the console on the login page and type `console.log(kcContext)`. You can also do `reveal html`.  

You can also start from the starter repo. 
https://github.com/garronej/keycloakify-advanced-starter or https://github.com/garronej/keycloakify-starter  
and hack around.  

Good luck

**Comment by garronej** [comment]
I dorp this here, even if it's not realy a tutorial but rather a post build instruction video:  
https://youtu.be/WMyGZNHQkjU

**Comment by willwill96** [comment]
I created a video yesterday, which might serve this purpose:
https://youtu.be/x3ux2JM1Bxk
