### ISSUE TITLE
Failure on WebauthnAuthenticate (race condition?)

### ISSUE THREAD

**Issue by upfluentpatrickpilch** [keycloakify/keycloakify#209]
I'm running into a very consistently reproduced WebAuthn bug when using a keycloakify 6.8.5 based theme on Keycloak 19.0.3. When authenticating via a security key (tried various kinds) to the account console, I get the following:

![image](https://user-images.githubusercontent.com/97203210/202804276-36a06268-d186-4306-8aa8-294b2b1bfeed.png)

Investigating the failure further, I noticed that the POST payload being sent for authentication (with the required values like `clientDataJSON`, `authenticatorData`, etc.) had all of the values un-set.

After some experimentation, I realized that simply delaying the form submission worked around the problem. Specifically, I delayed [the form submission](https://github.com/InseeFrLab/keycloakify/blob/v6.8.5/src/lib/components/WebauthnAuthenticate.tsx#L79) like so:
```typescript
setTimeout(() => {
    submitForm();
}, 1000);
```

I'm investigating the root cause, but I figured I'd open the issue in case any React experts share a hunch.

**Comment by garronej** [comment]
Hey @upfluentpatrickpilch,  
Thank you for reporting!  
Sory for the late reply I'll try to have a look tomorow.  
I didn't implement this page.

**Comment by garronej** [comment]
Fixed
