### ISSUE TITLE
RegisterUserProfile.tsx always renders both username and email regardless of realm.registrationEmailAsUsername

### ISSUE THREAD

**Issue by civilizeddev** [keycloakify/keycloakify#238]
## Problem

I am not sure whether `RegisterUserProfile.tsx` works properly in accordance with `realm.registrationEmailAsUsername`.

## My Expectations

Shouldn't the field `username` or `email` be hidden when `registrationEmailAsUsername: true`?

### When `registrationEmailAsUsername: true`

```
{
  pageId: 'register-user-profile.ftl',
  realm: {
    registrationEmailAsUsername: true
  },
  ...
}
```

<img width="1624" alt="Screenshot 2023-02-02 at 11 40 12" src="https://user-images.githubusercontent.com/15084045/216218125-76ab15d5-a174-4d59-9665-0babf77621d3.png">

### When `registrationEmailAsUsername: false`

```
{
  pageId: 'register-user-profile.ftl',
  realm: {
    registrationEmailAsUsername: false
  },
  ...
}
```

<img width="1624" alt="Screenshot 2023-02-02 at 11 39 59" src="https://user-images.githubusercontent.com/15084045/216218040-7ebcbcbc-86f7-41f3-9d5b-a059c7680196.png">

## Question

- To achieve my expectation, do I have to create my own `RegisterUserProfile` component without help of `UserProfileCommons`?
- How can I exclude the fields `First name` and `Last name`? (They are always rendered.)

## Related

- https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/RegisterUserProfile.tsx
- https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/shared/UserProfileCommons.tsx

**Comment by garronej** [comment]
Hello @civilizeddev,  

Thanks for reaching out,  
Before anything could you check if you have the same behaviour in keycloak with the default theme?  

If you are only witnessing the unexpected behaviour with Keycloakify it means that I made an error in the translation from freeMarker to React.  
It the error is hapenning in both case I can fix it in keycloakify but we should as well submit a PR to Keycloak.

**Comment by civilizeddev** [comment]
It's almost with the default theme. I changed only the background color. 

Here is my repo: https://github.com/glassdomeinc/omnibus-keycloak

### How to reproduce

1. yarn
2. yarn keycloak (first time, keycloak 20.0.3)
3. yarn start

**Comment by garronej** [comment]
I mean, not the default Keycloakfiy theme.  
The acutal default theme from keycloak.  
<img width="512" alt="image" src="https://user-images.githubusercontent.com/6702424/216410805-882c1572-3f54-4605-998f-11f58e0620db.png">

![image](https://user-images.githubusercontent.com/6702424/216411189-24d20838-f09a-481f-a681-341f4c9e020c.png)

**Comment by civilizeddev** [comment]
It seems to work as expected with the default theme in keycloak.

### Email as Username: ON

<img width="1624" alt="Screenshot 2023-02-03 at 3 42 28" src="https://user-images.githubusercontent.com/15084045/216420293-4dbc0398-b426-4f30-99de-3a84cc3f9ff8.png">

<img width="1624" alt="Screenshot 2023-02-03 at 3 40 30" src="https://user-images.githubusercontent.com/15084045/216419723-0ed6448f-156d-490e-ba87-b92272a14e7c.png">

### Email as Username: ON

<img width="1624" alt="Screenshot 2023-02-03 at 3 42 50" src="https://user-images.githubusercontent.com/15084045/216420503-e4a02769-5347-4cb8-8088-9daca4c02557.png">

<img width="1624" alt="Screenshot 2023-02-03 at 3 43 20" src="https://user-images.githubusercontent.com/15084045/216420429-cf8ad014-2f65-43d6-a358-27a8b99fe1a5.png">

**Comment by garronej** [comment]
Ok then we need to fix 
https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/RegisterUserProfile.tsx
or 
https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/shared/UserProfileCommons.tsx

**Comment by garronej** [comment]
@civilizeddev If you could go the extra miles and checkout yourself what it wrong it the translation that would be of great help. 
You can submit a PR or just share your finding here.  
- user-profile-common: [The reference implementation in ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/user-profile-commons.ftl) -- [The React translation](https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/shared/UserProfileCommons.tsx)  
- register-user-profile: [The reference implementation in ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/register-user-profile.ftl) -- [The React translation](https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/RegisterUserProfile.tsx)

**Comment by civilizeddev** [comment]
I think there's something wrong with this part.

https://github.com/InseeFrLab/keycloakify/blob/fa8e1195141eb5d0adffb2087c376df488240b4b/src/lib/useFormValidationSlice.tsx#L335-L382

**Comment by garronej** [comment]
Damn I forgot about this.  
I have to get back at it.

**Comment by garronej** [comment]
Hi,  
I didn't do anything about it but it seems to have been fixed.  
Or at least, I can't reproduce.  
In the starter project:  

<img width="347" alt="image" src="https://user-images.githubusercontent.com/6702424/233454354-bfbe9a17-f944-4f92-822a-e2aff87183d6.png">

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/6702424/233454700-e302217a-eee2-4059-811d-1096ef9bf398.png">


<img width="343" alt="image" src="https://user-images.githubusercontent.com/6702424/233454753-65e76cf0-b664-4e4a-99d8-0c97d241188a.png">
  

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/6702424/233454808-9cc51472-b9b8-4840-b206-1144437e4e40.png">

**Comment by Frank-D** [comment]
hello @garronej, 
I just felt on this closed issue, and just wanted to mention that this described issue is still relevant, at least during dev cycle using storybook.

when using the 'register-user-profile.ftl' mockData, applying `registrationEmailAsUsername: true` is not taken into account, e.g.:
`kcContext.ts`:
```
export const { getKcContext } = createGetKcContext<KcContextExtension>({
mockData: [
...
{
	pageId: "register-user-profile.ftl",
	realm: {
		registrationEmailAsUsername: true
	},
        ...
}
...
]
});
```

As opposed to the deprecated file `Register.tsx` which does have a [check for that parameter](https://github.com/keycloakify/keycloakify/blob/5c5dce14224434cee25f7f184b2e7cdd7ab408fd/src/login/pages/Register.tsx#L85), the `RegisterUserProfile.tsx` which relies on [UserProfileFormFields.tsx](https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/shared/UserProfileFormFields.tsx) to control its registration attributes is probably missing that check...does that make sense to you?

**Comment by Frank-D** [comment]
Also, while we're at it, the issue had a 2nd question which I believe wasn't answered:
> How can I exclude the fields First name and Last name? (They are always rendered.)

I would also be interested in knowing what's the best approach with keycloakify to do so? In my case, I would like to remove/hide the "Confirm Password" field (this is now a deprecated practice in general in terms of UX registration, the least number of fields the better, just asking the password is enough, worst case user will have to do the forgot password, but it's better that way since it applies to only a very few users, than asking to confirm password for 100% of registration cases..)

I've looked at the `Attribute` [type definition](https://github.com/keycloakify/keycloakify/blob/main/src/login/kcContext/KcContext.ts#L493), but there is no attribute parameter to hide the attribute, so I believe I would need to go hack directly the [UserProfileFormFields.tsx](https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/shared/UserProfileFormFields.tsx) file with a condition on the attribute field name in order to hide the password confirmation (same approach for first name or last name basically), is that the right approach? thanks!

**Comment by garronej** [comment]
Hello @Frank-D,  

> when using the 'register-user-profile.ftl' mockData, applying registrationEmailAsUsername: true is not taken into account, > e.g.:
> kcContext.ts:  

What version of Keycloakify are you using? Is is the case in v9?  

> I would also be interested in knowing what's the best approach with keycloakify to do so? In my case, I would like to remove/hide the "Confirm Password" field (this is now a deprecated practice in general in terms of UX registration, the least number of fields the better, just asking the password is enough, worst case user will have to do the forgot password, but it's better that way since it applies to only a very few users, than asking to confirm password for 100% of registration cases..)  

Allright 👍🏻   

> I've looked at the Attribute [type definition](https://github.com/keycloakify/keycloakify/blob/main/src/login/kcContext/KcContext.ts#L493), but there is no attribute parameter to hide the attribute, so I believe I would need to go hack directly the [UserProfileFormFields.tsx](https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/shared/UserProfileFormFields.tsx) file with a condition on the attribute field name in order to hide the password confirmation (same approach for first name or last name basically), is that the right approach? thanks!  

Keycloakify is only a framwork for creating theme. What you want to acheive would be something that you'd configure in Keycloak.  
According to chatGPT it should be possible: https://chat.openai.com/share/a3254182-6228-438d-888a-2084acea6e23  

But the option to hide the password confirm and make the post request with the correct password-confirm param is also very much acheivable (for example with a controlled hidden field) and I see nothing wrong with it.  
You would overwrite this component: https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/shared/UserProfileFormFields.tsx

**Comment by Frank-D** [comment]
Thanks a lot for your quick answer @garronej !

I am indeed using latest keycloakify version as of this writing, e.g. v9.

Thanks for sharing that chatGPT potential solution, according to it, it may now be possible to achieve the type of customization that we’re asking here directly from the keycloak admin console over a few mouse clicks, I’ll give it a try, as this might be the best overall solution to this peoblem, if possible through the admin console, instead of having to do more advance java keycloak server development with “SPI” etc. Tbd!

Else, if it ends up not being as simple as what chatGPT suggests, I’ll just go with your alternate front-end/ui hacky but simple solution! ;-) I’ve found a slightly older but not too old [stackoverflow thread](https://stackoverflow.com/a/74900844) that explains the same, but with a bit more details (even though it applies for a native new keycloak .ftl theme, I’ll just need to do the equivalent - as you are suggesting - within my keycloakify stack instead).

Thanks again

**Comment by garronej** [comment]
> But the option to hide the password confirm and make the post request with the correct password-confirm param is also very much acheivable (for example with a controlled hidden field) and I see nothing wrong with it.

In the next release there will be an option allowing not to have to type password configmation:
