### ISSUE TITLE
Build multiple themes at once

### ISSUE THREAD

**Issue by sebbrousse** [keycloakify/keycloakify#256]
Hi,

A quick question : is there a way to build multiple (login) themes at once with keycloakify ? 

Thanks a lot !

**Comment by garronej** [comment]
Hi,  
I'm not sure I understand what you mean.  
Can you elaborate ?

**Comment by sebbrousse** [comment]
Something that would be able to generate multiple themes in the same jar with a keycloak-themes.json like this : 

```
{
  "themes": [
    {
      "name": "themeA",
      "types": [
        "login",
        "email"
      ]
    },
    {
      "name": "themeB",
      "types": [
        "login",
        "email"
      ]
    }
  ]
}
```

**Comment by garronej** [comment]
Hi,  
Sorry for the late reply, no this isn't something that we currently support.  
Feel free to submit a RFC if you think this is a usecase worth supporting

**Comment by garronej** [comment]
Hi @sebbrousse,  

It has now been implemented: https://docs.keycloakify.dev/build-options#keycloakify.extrathemenames
