### ISSUE TITLE
Restore Storybook

### ISSUE THREAD

**Issue by garronej** [keycloakify/keycloakify#274]
Hi @lordvlad,  
I have templorarely removed storybook from the starter and moved it to a separate repo: https://github.com/garronej/keycloakify-storybook  

Of course it's still published but at an other adress: https://storybook.keycloakify.dev (If it's 404 it means that the DNS haven't been updated yet.)  

Not that I think the Storybook isn't important, it's a game changer, I've added the link to it everywhere I could and thank you for going through with it.  
However, I don't want to eject all the pages in the starter project. idealy I wouldn't eject but considering the starter also serves as an interactive tutorial I have to.  

As a matter of fact, we don't need to eject the pages in the starter to have them in the storybook.  
And we could have a single story file for the `KcApp.tsx` component instead of a story per pages.  
This way we would enable the users to see how pages that they aren't ejected will render with their Template.  
Or rather, we would have two `.stories.tsx` files, one for the `login` and one for the `account` theme and many views in each.  

You already did the heavy lifting, we just need to refactor a bit.  

Connex issue: https://github.com/InseeFrLab/keycloakify/issues/176

**Comment by lordvlad** [comment]
> And we could have a single story file for the KcApp.tsx component instead of a story per pages.
> This way we would enable the users to see how pages that they aren't ejected will render with their Template.

Not sure I get you. Every story is using the same kcapp.tsx already, the stories only differ in pageid. So now already you should be able to have a mix of customized ('ejected') and non-customized pages. Correct me if I'm wrong.


Keeping the starter as an interactive tutorial and a project template would have been all the more reason to keep storybook in the project IMHO. I like to keep my storybook where my components are. Now they are in a different repo.

**Comment by lordvlad** [comment]
> I understand your frustration, you have spent time and effort to set this up only to see it buried in a different repo a few day later.
Rest assured that your work isn't lost, and that I've moved it away only as a temporary measure.

No please don't misunderstand me, I don't attach myself to my products. I'm thinking about usability here.

> We want to enable users to preview what pages are available and how they look by default this gives something to the designers to work with.
We want to make it as easy as possible for users to test their theme in storybooks.

And you can easily combine both cases in the starter, no? 

Case one is covered by the storybook that is [publicly hosted here](https://storybook.keycloakify.dev/storybook/?path=/story/theme-pages-actions-configure-totp--default).

Case two is covered by a developer using the starter as template and running `pnpm storybook`.

Those two steps are as simple as it gets. Only step that was required was to remove the many duplicate pages from the starter project. That was the error on my side, there was actually no need to copy e.g. [LoginOtp.tsx](https://github.com/codegouvfr/keycloakify-starter/pull/2/files#diff-aea95398ad79ee40530bef83a45fb7889f64acaa28584da76e4fbcbbfac94216) from keycloakify project, cause keycloakify would fall back to the default template anyway.

**Comment by lordvlad** [comment]
Okay, right, I guess then it makes sense to have two storybook setups. Main point I wanted to make that it does make sense to have storybook setup in starter project. If you agree with that, there's no disagreement :)

**Comment by garronej** [comment]
I'm on it:  

![image](https://user-images.githubusercontent.com/6702424/232246851-2ee758d2-db6a-460e-825d-bdc372f7a337.png)  

![image](https://user-images.githubusercontent.com/6702424/232246878-d00d2c20-694a-46e8-8638-e15a0fe0aaa1.png)

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/232350420-1921af90-d33e-492e-9296-0083298a84fa.png)

[x] - Good basic storybook setup in the starter project.

**Comment by lordvlad** [comment]
<3

**Comment by garronej** [comment]
It's starting to look good!

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/6702424/232652521-0be703ca-3313-4c24-8e4a-a00ea89a8daf.png">
