### ISSUE TITLE
[Question] Using Keycloak default theme later then 11.x

### ISSUE THREAD

**Issue by TomRom27** [keycloakify/keycloakify#276]
(tried to search the existing issues but haven't found anything relevant)
As far I can see, keycloakify arbitrary uses "keycloakVersion": "11.0.3" as a "base" theme.

This version is old and specially newer versions use additional styles, like @patternfly/react-core.

I wander is it "proved" that keycloakify is unable to work with newer themes and if not maybe it would be possible somehow make it configurable?

And thanks for great job with keycloakify!!!

Example:
new package in the structure and its styles used in default login screen (identity providers styling):
![image](https://user-images.githubusercontent.com/13231866/227543269-7536f1f8-d373-48dc-a08a-af9238dc08d0.png)

**Comment by TomRom27** [comment]
Thanks for quick answer.
Yes, I understand switching to use latest KC theme version is not a simple thing and can fail due to some incompatibilities.
That's why I thought on just making possible to decide via config or env. variable which theme version is the keycloakify base.
And this would be fully on developer's risk. Also, the updates you mentioned will be left on the developer - depending on how much they want to use new KC theme's features.

One thing: would kecloakify be able to download the latest KC theme resources (and making them accessible by Template or Login component) without any further changes but in the line 52 in keycloakify.ts ("keycloakVersion": "11.0.3")?

**Comment by garronej** [comment]
> One thing: would kecloakify be able to download the latest KC theme resources (and making them accessible by Template or Login component) without any further changes but in the line 52 in keycloakify.ts ("keycloakVersion": "11.0.3")?   

Yes.  

I can make a build option, that's a no brainer.  As long as you unserstand that the only thing it will do is make the resources available.  

Do you want me to create that option?

**Comment by garronej** [comment]
@TomRom27: It's done!  
https://docs.keycloakify.dev/build-options#keycloakify.keycloakversiondefaultassets  

Hope it fit your needs.

**Comment by TomRom27** [comment]
Thank you!!!
