### ISSUE TITLE
idp redirect page

### ISSUE THREAD

**Issue by satanshiro** [keycloakify/keycloakify#277]
In some cases it seems you cannot disable idp redirect page.
the case being saml authentication. which requires the saml binding in html.
this is the original ftl page:
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/saml-post-form.ftl
would be nice to create a keycloakify page for this too if possible.

**Comment by garronej** [comment]
Hi @satanshiro,  
If you would submit a RP to add it the community and I would be very grathful!  
Here is a guide on how to procede: https://docs.keycloakify.dev/contributing

**Comment by satanshiro** [comment]
Hi @garronej 
It's in our backlog I Hope we will get to it soon but I can't promise.
thanks for your quick reply, have a nice day~

**Comment by garronej** [comment]
Done! https://storybook.keycloakify.dev/?path=/story/login-saml-post-form-ftl--default

**Comment by chongrui** [comment]
Hi @garronej, it seems like the above link you provided fails with _**"Cannot read properties of undefined (reading 'submit')"**_, do you have any ideas why and could this be related to the fix @satanshiro put in for https://github.com/keycloakify/keycloakify/issues/341?

**Comment by garronej** [comment]
Thanks for reporting. I'll fix that tomorrow

**Comment by garronej** [comment]
@chongrui I fixed the storybook, thanks for reporting.  
Note that this page is a bit perticular, it's never actually seen by the user when everything goes well. The user is automatically redirected right away.

**Comment by chongrui** [comment]
Thank you for the quick fix!
