### ISSUE TITLE
Use value from theme.properties (container runtime env value) in theme

### ISSUE THREAD

**Issue by radovan-pranda** [keycloakify/keycloakify#288]
Hi, I'd like to ask, how can I use runtime ENV value in theme.

In KC ftl file I could use ENV value by adding `cookieUrl=${env.appCookieUrl:}` to `theme.properties`. Then I could bind value using `${properties.cookieUrl}`  in any ftl file.

Is there any option I do this using keycloakify? 
Thank you for any response

**Comment by radovan-pranda** [comment]
I also found section **keycloakify.extraThemeProperties**, but there isn't any further info, how to use this variable in code.

**Comment by garronej** [comment]
Hi @radovan-pranda,  
Thanks for reaching out.  

If you use add this in your package.json:  

<img width="415" alt="image" src="https://user-images.githubusercontent.com/6702424/229109973-18faa4c4-e3c7-4022-a663-e90d79e0b169.png">

You'll get this in your kcContext:  

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6702424/229109898-a9fdef6e-3250-466d-ad66-8113c81ad34f.png">  

You are right.  
This is not documented enough.

**Comment by willwill96** [comment]
Are runtime env variables currently supported? I tried this and it created the extra property, but the value is left as a string literal. It looks like this:
```
// window.kcContext.properties
{
  "myCustomVar": "${env.MY_VAR}",
  "kcAlertClass":
  ....
}
```

**Comment by radovan-pranda** [comment]
> Hi @radovan-pranda, Thanks for reaching out.
> 
> If you use add this in your package.json:
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/6702424/229109973-18faa4c4-e3c7-4022-a663-e90d79e0b169.png">
> 
> You'll get this in your `kcContext`:
> 
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/6702424/229109898-a9fdef6e-3250-466d-ad66-8113c81ad34f.png">
> 
> You are right. This is not documented enough.

Thank you for your response. It helped to solve my issue :)

**Comment by radovan-pranda** [comment]
> Are runtime env variables currently supported? I tried this and it created the extra property, but the value is left as a string literal. It looks like this:
> 
> ```
> // window.kcContext.properties
> {
>   "myCustomVar": "${env.MY_VAR}",
>   "kcAlertClass":
>   ....
> }
> ```

Yes, it is supported, you need to define it like it is mentioned in response to my question.
In package json like this:
"extraThemeProperties": {
"yourCustomProperty=${env.YOUR_VAR:defaultvalue}"
}
