### ISSUE TITLE
i18n example messages not in library

### ISSUE THREAD

**Issue by bralandealmeida** [keycloakify/keycloakify#295]
Studying the library for an implementation I'm doing, I noticed that some pages import standard messages from `./baseMessages` and these messages are ignored in `.gitignore`. Could you remove these files from .gitignore` to have a value reference for custom messages?

This is important considering that some pages, in the context of keycloak, are difficult to reproduce, eg expired login page.

**Comment by garronej** [comment]
Hi @bralandealmeida,  
Only primary source of truth should be tracked by Git. Those messages are fetched from the Keycloak repo.  
You get them when installing Keycloakify from NPM though.  
You can also clone the repo and `yarn install` and you will get them.   

> This is important considering that some pages, in the context of keycloak, are difficult to reproduce, eg expired login page.  

Keycloakify features a mock mechanism that enables to test any pages outside of Keycloak: https://github.com/keycloakify/keycloakify-starter#quick-start  

We also have a storybook: https://storybook.keycloakify.dev/storybook
