### ISSUE TITLE
Terms page appears as blank

### ISSUE THREAD

**Issue by sukso96100** [keycloakify/keycloakify#297]
Hi, I'm currently using Keycloak 21.0.1. And, Seems like the Terms page is not working with keycloakify v7.x. It has no problem on v6.x
Same thing happened after migrating my theme to latest keycloakify and deploy on keycloak 21.0.1
## How to reproduce
- Clone Starter project https://github.com/keycloakify/keycloakify-starter with [latest commit](https://github.com/keycloakify/keycloakify-starter/commit/37f4756e3549d8a13096b311976c18e2e9daf4b1)
- [Run these commands](https://github.com/keycloakify/keycloakify-starter#standalone-keycloak-theme) to turn it into keycloak standalone theme
- On `src/login/kcApp.tsx`...

Import followings additonally
```js
import { useDownloadTerms } from "keycloakify/login";
import tos_en_url from "./assets/tos_en.md";
import tos_ko_url from "./assets/tos_fr.md";
```
Then add `useDownloadTerms` hook like below

```js
export default function App(props: { kcContext: KcContext; }) {

    const { kcContext } = props;

    const i18n = useI18n({ kcContext });

	useDownloadTerms({
        kcContext,
        "downloadTermMarkdown": async ({ currentLanguageTag }) => {

            const markdownString = await fetch((() => {
                switch (currentLanguageTag) {
                    case "fr": return tos_fr_url;
                    default: return tos_en_url;
                }
            })()).then(response => response.text());

            return markdownString;
        }
    });
    
    if (i18n === null) {
        //NOTE: Locales not yet downloaded, we could as well display a loading progress but it's usually a matter of milliseconds.
        return null;
    }
...
```
- Install dependencies with `yarn install`
- Build theme with `yarn build-keycloak-theme`
- Get and unzip keycloak 21.0.1 package
    - https://github.com/keycloak/keycloak/releases/download/21.0.1/keycloak-21.0.1.zip
- Place theme jar file on `providers` directory of keycloak
- Run `./bin/kc.sh build; ./build/kc.sh start-dev` to start keycloak dev server
- Enable `Terms and Conditions` on Authentication - Required actions of keycloak admin console.
- Create test user and configure required action with terms and conditions.
- Login with test user.

## Expected behavior
Terms of service screen with `Accept`, `Decline` button appear

## Actual behavior
White blank screen appears. With an error found on devtools console.
```
index.tsx:12 Uncaught Error: This app is a Keycloak themeIt isn't meant to be deployed outside of Keycloak
    at index.tsx:12:15
    at index.tsx:12:15
    at index.tsx:12:15
    at index.tsx:12:15
```
![image](https://user-images.githubusercontent.com/1916739/229559206-e7b20aa8-6b5e-4a36-ba08-19a56e55cc1f.png)
![image](https://user-images.githubusercontent.com/1916739/229559372-9d8559e9-620f-4501-8de2-57d014918042.png)

**Comment by garronej** [comment]
Found the bug... fixing...

**Comment by garronej** [comment]
It should be fixed in the last release. Please reopen if you have any remaining issues.   
Thanks for reporting!

**Comment by sukso96100** [comment]
It works without error now! Thank you :)

**Comment by garronej** [comment]
Thank you for the feedback
