### ISSUE TITLE
Typescript error for algToKeyUriAlg in LoginConfigTotp.tsx

### ISSUE THREAD

**Issue by thosil** [keycloakify/keycloakify#300]
Hello,

first of all: awesome project!

Typescript is not happy with this line:
https://github.com/keycloakify/keycloakify/blob/a02c38ac4502163935a4c36fcf3efdbb52892a6d/src/login/pages/LoginConfigTotp.tsx#L19

The error: `TS2702: 'KcContext' only refers to a type, but is being used as a namespace here.`

I think it should be:
```ts
const algToKeyUriAlg: Record<typeof kcContext["totp"]["policy"]["algorithm"], string> = { 
```

What do you think?

**Comment by thosil** [comment]
By the way, the page LoginConfigTotop is crashing because it try to call "map()" on totp.policy.supportedApplications, but supportedApplications is directly under totp.

I think it should be defined like this in keycloakify/src/login/kcContext/KcContext.ts
```ts
        totp: {
            enabled: boolean;
            manualUrl: string;
            policy: {
                algorithm: "HmacSHA1" | "HmacSHA256" | "HmacSHA512";
                digits: number;
                lookAheadWindow: number;
            } & (
                | {
                      type: "totp";
                      period: number;
                  }
                | {
                      type: "hotp";
                      initialCounter: number;
                  }
            );
            qrUrl: string;
            supportedApplications: string[];
            totpSecret: string;
            totpSecretEncoded: string;
            totpSecretQrCode: string;
            otpCredentials: { id: string; userLabel: string }[];
        }
```

Here a copy of the totp object when I debug:
```json
{
    "enabled": false,
    "totpSecretEncoded": "...",
    "totpSecret": "...",
    "manualUrl": "https://....",
    "supportedApplications": [
        "totpAppGoogleName",
        "totpAppFreeOTPName"
    ],
    "totpSecretQrCode": "....",
    "policy": {
        "initialCounter": "0",
        "type": "totp",
        "codeReusable": false,
        "lookAheadWindow": "1",
        "algorithm": "HmacSHA1",
        "period": "30",
        "algorithmKey": "SHA1",
        "digits": "6"
    },
    "qrUrl": "https://....",
    "otpCredentials": []
}
```

**Comment by thosil** [comment]
Sure, but I also hit #262, @sukso96100 seems to be working on it.
Should I only fix this one or try to do both in the same PR?

**Comment by garronej** [comment]
If you could do both it would be awesome

**Comment by thosil** [comment]
That's a weird issue :sweat_smile: 
It only happen when ejecting the page, because KcContext is not exported as a Namespace anymore but like this in a keycloakified app:
`export type KcContext = NonNullable<typeof kcContext>;`

**Comment by garronej** [comment]
Yes that's exatly it.  
It's because users are enable to extend the KcContext so they can have corect typing for their custom plugin or implement unsupported page themselvs without having to submit a PR.  

Thanks for working on a PR!
