### ISSUE TITLE
Info.ftl extending pages not applying the theme correctly

### ISSUE THREAD

**Issue by Rafael-Ramblas** [keycloakify/keycloakify#305]
For pages that extends info.ftl, such as `realms/myrealm/device/status` after grant access to a device, the theme is not being applied.

My login KcApp.tsx
```typescript
const KcApp = ({ kcContext }: { kcContext: KcContext }) => {
  return (
    <Suspense>
      {(() => {
        switch (kcContext.pageId) {
          case 'info.ftl':
            return (
              <>
                <pre>{JSON.stringify(kcContext)}</pre>
              </>
            )
        }
      })()}
    </Suspense>
  )
}

export default KcApp
```
This works running the project with `mockPageId: info.ftl`, but when building the theme and applying it, it doesn't work for pages that use info.ftl.

Device Login Successful Page html:
```html
<!DOCTYPE html>
<html class="login-pf">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">
            <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <link rel="icon" href="/resources/w9enr/login/keycloak/img/favicon.ico" />
            <link href="/resources/w9enr/common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css" rel="stylesheet" />
            <link href="/resources/w9enr/common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css" rel="stylesheet" />
            <link href="/resources/w9enr/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css" rel="stylesheet" />
            <link href="/resources/w9enr/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css" rel="stylesheet" />
            <link href="/resources/w9enr/common/keycloak/lib/pficon/pficon.css" rel="stylesheet" />
            <link href="/resources/w9enr/login/keycloak/css/login.css" rel="stylesheet" />
</head>
<body class="">
<div class="login-pf-page">
    <div id="kc-header" class="login-pf-page-header">
        <div id="kc-header-wrapper"
             class=""></div>
    </div>
    <div class="card-pf">
        <header class="login-pf-header">
                <h1 id="kc-page-title">Device Login Successful</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">
    <div id="kc-info-message">
        <p class="instruction">You may close this browser window and go back to your device.</p>
    </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
```
As you can see in the html, we have the id `kc-info-message`, which is only present in `info.ftl` for the base keycloak theme.
Also, there's no `status` page in the login pages from keycloak repo, and the string `Device Login Successful Page` is a i18n key that is applied in `messageHeader` in `services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java:287`
```java
  LoginFormsProvider forms = session.getProvider(LoginFormsProvider.class);
            return forms.setAttribute("messageHeader", forms.getMessage(Messages.OAUTH2_DEVICE_VERIFICATION_COMPLETE_HEADER))
                .setAttribute(Constants.SKIP_LINK, true).setSuccess(Messages.OAUTH2_DEVICE_VERIFICATION_COMPLETE)
                .createInfoPage();
```

**Comment by garronej** [comment]
Hi @Rafael-Ramblas,  

When on the pages that renders `index.ftl` can you open the dev tools of your browser, run `console.log(JSON.stringify(kcContext, null, 2))` and paste the result here.  

I'll try to figure out what's going on.

**Comment by Rafael-Ramblas** [comment]
Actually was a bad config of mine. 
The client theme was being overwritten by the realm theme.
I'm gonna close the issue. Thanks for the help!

**Comment by iprikhodko** [comment]
Guys, I encountered the same issue with info.ftl. Specifically, when working with the login-oauth-grant flow, the page at realms/myrealm/device/status is still using a different theme. I have correctly matched the themes in the root component, just as @Rafael-Ramblas did.

@Rafael-Ramblas @garronej Could you please provide more details on how you resolved this issue?

**Comment by garronej** [comment]
I don't remember exactly but usually it's that you are on another realm.  

Look in the url, see if you see `/master/` our `/<your realm>/`.  

If you see master it means that your theme must be applied as the realm level (which should be avoided)  

If you are seeing the name of your relam it means that you have applied your theme at the client level, and you must apply it to another client or at the realm level. If you want to know the name of the client look for `client_id` in the URL.  

I'm willing to help [on discord](https://discord.gg/mJdYJSdcm4) if need be

**Comment by iprikhodko** [comment]
@garronej I'm back with new details. My theme is not applied at `/realms/develop/device/status` when it's used only for specific client, but when I apply it for entire realm it works! How can I apply custom theme for specific client and see it at `/realms/develop/device/status`? Is it possible?

**Comment by garronej** [comment]
Well as you can see in your `/realms/develop/device/status` url there is no mention of the client_id.  

The pages being stateless, it's theorically impossible for keycloak to know that it must use `MY_CLIENT`

If you add `&client_id=MY_CLIENT` to the status url it will work.

**Comment by iprikhodko** [comment]
@garronej Thank you for clarification

When I add ?client_id=MY_CLIENT to the status url it doesn't work

It's sad because I need to have two different themes for two different clients. I can't apply specific theme for entire realm
