### ISSUE TITLE
Account Page: Accidental "I" after the Cancel Button

### ISSUE THREAD

**Issue by julienthoma** [keycloakify/keycloakify#306]
https://github.com/keycloakify/keycloakify/blob/57b056b388dd45bcd2c832bab793493c27c4c31d/src/account/pages/Account.tsx#L127

There is a typo after the cancel button on the account page.

![localhost_8080_realms_myrealm_account_](https://user-images.githubusercontent.com/2485581/231423808-d3dc0135-0e9b-4d77-aad0-d0d5fcb04b26.png)

**Comment by garronej** [comment]
Thanks for the report, fixing
