### ISSUE TITLE
Mime Type Error on latest keycloakify-starter

### ISSUE THREAD

**Issue by willwill96** [keycloakify/keycloakify#331]
My login pages aren't rendering and getting this on the latest keycloakify-starter repo:

![image](https://user-images.githubusercontent.com/10997562/233870153-860b5c7a-b5cc-4c74-9114-a984cdfdb26c.png)

This is a fresh install of keycloak + keycloakify. Here is my Dockerfile for reference (Located one directory up from keycloakify-starter):
```Dockerfile
FROM node:18 as keycloakify_jar_builder

COPY ./keycloakify-starter/package.json ./keycloakify-starter/yarn.lock /opt/app/

WORKDIR /opt/app

RUN yarn install --frozen-lockfile

COPY ./keycloakify-starter/ /opt/app/

RUN yarn build-keycloak-theme

FROM quay.io/keycloak/keycloak:latest as builder

WORKDIR /opt/keycloak

COPY --from=keycloakify_jar_builder /opt/app/build_keycloak/target/keycloakify-starter-keycloak-theme-4.4.4.jar /opt/keycloak/providers/
RUN /opt/keycloak/bin/kc.sh build


FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/
ENV KC_HOSTNAME=localhost
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

I verified stale assets aren't being included and I've tried with both building the keycloakify jar inside and out of a Dockerfile build step

**Comment by garronej** [comment]
@willwill96  😥   

I can't reproduce, I just tried right now, everything is working as expected on my end (except https://www.keycloak.org/app is down).  

I'm going to paste here the same aswer I gave you yesterday, I'm very willing to find what's up but I'll need a clear reproduction path.  

Hello @willwill96!

That's odd indeed.

Can you confirm if you built your theme with the `--external-assets` option (please check your CI workflow)? I don't believe you did, but if so, that could easily explain the error you're encountering.

I'm currently using the latest version in production, and it works perfectly:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6702424/233735475-468e3c4f-ea98-4c39-9acc-722189cf5813.png">

Additionally, the latest Keycloakify starter theme is also running smoothly in production:

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/6702424/233735584-58c86700-cd35-4bf1-8223-e10f88893e97.png">

I'd recommend giving the latest Keycloakify-starter theme a try in your Keycloak instance. You can find it here: https://github.com/keycloakify/keycloakify-starter/releases/download/v4.4.4/keycloak-theme.jar

If it doesn't work, it may indicate an issue with the JAR's build process.

However, if it does work, that would imply I introduced a breaking change somewhere.
