### ISSUE TITLE
Repo is much bigger than it needs to be

### ISSUE THREAD

**Issue by lordvlad** [keycloakify/keycloakify#333]
Just noticed in a container while trying to reproduce another bug:

```
root@f78e058348a9:/tmp# git clone https://github.com/keycloakify/keycloakify.git
Cloning into 'keycloakify'...
remote: Enumerating objects: 14109, done.
remote: Counting objects: 100% (3928/3928), done.
remote: Compressing objects: 100% (1881/1881), done.
remote: Total 14109 (delta 2067), reused 3818 (delta 1998), pack-reused 10181
Receiving objects: 100% (14109/14109), 47.62 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (8679/8679), done.
```

The git repo is almost 50MiB big, possibly slowing CI

- [ ] analyze why its so big
- [ ] analyze impact on CI
- [ ] propose pruning strategy if need be

**Comment by garronej** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/6702424/234139373-57fd217f-7aa2-42f1-b5af-fdc67690ebe2.png">
I trucated the history of the `gh-pages` branch.  It's much more reasonable now. Thanks for noticing.

**Comment by lordvlad** [comment]
<3
