### ISSUE TITLE
Question: Access extra pages

### ISSUE THREAD

**Issue by hypery2k** [keycloakify/keycloakify#334]
Hey folks,

thanks for the great work. I really like the project. 

I'm trying to build a custom theme with extra page, so i started with your starter project and made some customizations. 
How can I access the `my-extra-page-1.ftl` in a local Keycloak?  I already tried http://localhost:8080/realms/master/account/my-extra-page-1 but it leads to a 404. 

Any suggestions what I'm doing wrong here? In the bundled theme everyhing seems fine:
![image](https://user-images.githubusercontent.com/979121/234187189-6e5336e8-24f0-4bd6-bebe-58792f8b1af4.png)

**Comment by garronej** [comment]
Hi @hypery2k,  

Thanks for the kind words,  

The extra pages are only for for implementing pages that are known by Keycloak but that are not implemented by us yet.  
You can't create arbitrary new pages.  
The naming isn't great I admit that it's confusing.  

However you can acheive the same result by using client side rooting, by manually switching the react node.

**Comment by garronej** [comment]
@filipzava thanks for reporting!  

This is indeed a bug that need fixing, I'm on it

**Comment by garronej** [comment]
Fixed in 7.11.3 🚀

**Comment by filipzava** [comment]
Cool, its now working! Kudos! 👍

**Comment by luigidevelopment** [comment]
Hi guys,

How can I access the extra pages now? I'm trying to use the URI /account/my-extra-page-2, but without success. That's anyway to create a custom extra page and access them?

**Comment by garronej** [comment]
Hello @luigidevelopment,

The term "extra page" may seem a little unclear. Essentially, my-extra-page-2 cannot be directly accessed from Keycloak; it serves as a placeholder name. The "extra page" feature in Keycloakify is designed for two main scenarios:

It aids in the development of pages that theoretically exist in Keycloak, but have not yet been implemented by the Keycloakify team. However, it's worth noting that this applies to a minimal number of pages as most common ones are already in place.

It provides support for Keycloak plugins that generate additional user-facing pages.

This feature tends to be most useful for experienced Keycloakify users, those who have a deep understanding of the system and are undertaking very specific tasks. For instance, a company might require an extra page for a unique user interface, such as an iris scanner.

If your goal is to create an additional page that doesn't need to have a special interaction with the Keycloak server, bear in mind that you hold the reins. You can design it as you would within a regular React App, as long as you submit the correct form data to the server. This gives you the freedom to shape your user interface to best fit your needs.

**Comment by luigidevelopment** [comment]
Thanks @garronej !

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
