### ISSUE TITLE
Issue with the JARs created by the Keycloakify bundler

### ISSUE THREAD

**Issue by dyeske61283** [keycloakify/keycloakify#336]
Hello,

As pointed out here "https://docs.keycloakify.dev/build-options#keycloakify.bundler" we should create an issue, if we need to use the legacy **mvn** bundler. This was the case.

**Our use case & issue:**
When using the keycloakify build, we need to unpack the generated JARs in the process to add to some additional files and perform some renaming. After using the keycloakify bundler, the JAR files could not be unpacked by using either JAR or unzip -- the errors are added at the bottom. 
This is apparently due to the format of the created archive. See the thread here for an explanation: https://stackoverflow.com/questions/47208272/android-zipinputstream-only-deflated-entries-can-have-ext-descriptor 

Workaround:
Using **mvn** as the bundler works fine.

---
This was the error, when using **JAR**:
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:313)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1360)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:409)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1680)

This was the error, when using **unzip**: 
_error: invalid zip file with overlapped components (possible zip bomb)_

**Comment by lordvlad** [comment]
@dyeske61283 anyway tofind out which jar entry caused the error? Can't reproduce the unzip issue. Can you try unzip again with the zip bomb detection disabled? `UNZIP_DISABLE_ZIPBOMB_DETECTION=true unzip -t bla.jar`

**Comment by lordvlad** [comment]
Quite certain this is related to #330 #331

**Comment by dyeske61283** [comment]
@lordvlad The unzip did work for me as well on my local machine (MacOS), but not inside a node:18.12.1 docker image (which should be debian-based in our build pipeline). I will disable the detection and try it again.

In regards to the JAR entries: Sadly, starting the JAR executable in verbose mode does not reveal any additional info.

**Comment by lordvlad** [comment]
@dyeske61283 can you try using the branch from #339?

**Comment by garronej** [comment]
@dyeske61283 I just released, you can test with latest. No need to checkout the branch.  
@lordvlad next time, if you want to enable pepole to test, just release a candidate updating the package.json version to `X.Y.Z-rc.U`, this will publish on npm a version that pepole won't get with `"latest"` but that will be available if they specify the ecact version number.

**Comment by dyeske61283** [comment]
@lordvlad @garronej  Thank you for your help, I will make sure to test that. 
I just now realized, that I should have mentioned, that we are on version 6.13.2. Therefor, I will need to resolve the breaking changes from 6 to 7 first. 
I will do that over the next few days and check again.

**Comment by garronej** [comment]
Okay 👍🏻 
It's worth it. V7 is a major improvement in many ways but yeah. There are breaking changes 😕

**Comment by lordvlad** [comment]
@garronej can this be closed? wdyt?
