### ISSUE TITLE
Error when reading loginAction with LoginOAuthGrant page and template

### ISSUE THREAD

**Issue by abencun-symphony** [keycloakify/keycloakify#357]
We're seeing a following error on our Keycloak instance:
```
2023-06-12 16:46:14 2023-06-12 14:46:14,044 ERROR [freemarker.runtime] 
(executor-thread-162) Error executing FreeMarker template part in the 
#attempt block: freemarker.core._TemplateModelException: An error has 
occurred when reading existing sub-variable "loginAction"; see cause 
exception! The type of the containing value was: extended_hash+string 
(org.keycloak.forms.login.freemarker.model.UrlBean wrapped into 
f.e.b.StringModel)
2023-06-12 16:46:14 
2023-06-12 16:46:14 ----
2023-06-12 16:46:14 FTL stack trace ("~" means nesting-related):
2023-06-12 16:46:14     - Failed at: #if !object[key]??  [in template 
"login-oauth-grant.ftl" in function 
"ftl_object_to_js_code_declaring_an_object" at line 212, column 21]
....

2023-06-12 16:46:14     at 
org.keycloak.forms.login.freemarker.model.UrlBean.getLoginAction(UrlBean.java:48)
2023-06-12 16:46:14     ... 111 more
2023-06-12 16:46:14 
```

The template is trying to get the `loginAction` URL, it seems, but `loginAction` shouldn't be available nor requested by the FTL on this specific page. The page works it's just that we're seeing this error in console. Is there any way to prevent this?
BTW we do not need `loginAction` here, we're just interested in why the error is happening and can we resolve this.

Environment info:
Keycloak v20.0.5, Keycloakify 7.11.11
Also tested on Keycloak v21, same exception.

**Comment by garronej** [comment]
That's it.  
I just added an exception for `login-oauth-grant.ftl`, `url.loginAction` isn't read anymore for this page in Keycloakify v7.12.2 that is currently being deployed.  

https://github.com/keycloakify/keycloakify/blob/310f857257335e30108545e00e83caa9b59db148/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L174-L177  

Thank you for reporting!

**Comment by abencun-symphony** [comment]
Much appreciated! Will test ASAP and report back!

**Comment by zivcex** [comment]
This fixed the issue with this page! Thanks for the support!

I'm working together with @abencun-symphony; so after the keycloakify update I've checked our logs and this exception doesn't pop up anymore.

**Comment by garronej** [comment]
Happy it did it. Thanks for reporting!
