### ISSUE TITLE
Failed to run yarn build

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#358]
Hello,
I cloned to keycloakify-starter-project, and if i run yarn start or yarn build it all works correctly.

If I install a new dependencies like 'antd' (ant design), and I try to use it in my Login.tsx file to customize the UI, when i run the build command it failed with the following error:

![Screenshot 2023-06-13 alle 12 19 22](https://github.com/keycloakify/keycloakify/assets/45390137/9821823c-f769-4aed-b12f-935a45a55282)

I did not change anything in the tsconfig.json file or any other file except for the Login.jsx and of course the package.json (with the new dependecy).

Running 'yarn start' it all works correctly. The problem is only with the build command.

How can i solve this ? 

Thank you ,

**Comment by garronej** [comment]
Hi @PietroFalcetti,  

The issue is unrelated to Keycloakify.  
The keycloakify starter is a vanilla https://create-react-app.dev/ project, you would get the same build error if Keycloakify wasn't there.  

I'll be probably able to quickly debug you if you can show me the code.  

Best

**Comment by garronej** [comment]
Sorry can't reproduce. Everything working fine if I just install antd and use the basic example provided in their reamde:  

```tsx
import { Button, DatePicker } from 'antd';


  <>
    <Button type="primary">PRESS ME</Button>
    <DatePicker placeholder="select date" />
  </>

```

There must be something else going on in your repo, try googleing your issue or comming up with a reproduction path.  

Best

**Comment by PietroFalcetti** [comment]
I re-cloned the repo and tried again.
Now it all works correctly.

Thank you for your help! 

Have a nice day

**Comment by garronej** [comment]
You're wellcome.  

Do not hesitate to reach out if you have any other issues

**Comment by garronej** [comment]
Got a similarish error  
<img width="1161" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/6cdc26f0-7c1f-4dab-85f3-585346761741">
Was unable to reproduce. I beleve you.
