### ISSUE TITLE
Contents of resource_common/node_modules in created JARs

### ISSUE THREAD

**Issue by amk0** [keycloakify/keycloakify#360]
Hello!

When I build a theme, for example the starter theme, in the JAR file under **/theme/keycloakify-starter/login/resources/resources_common/node_modules/** I see some Angular packages. 

Are these angular files actually used by the themes? Would it be possible to configure the build script to ignore them while creating the JAR file?

These Angular files are triggering some security scans in our Keycloak Image, because it contains an old Angular 1.8 JS version.

Thanks in advance o7

**Comment by amk0** [comment]
Awesome, thank you for the answer. Ill finish updating my theme from v6 to v7 and give that option a go.

**Comment by garronej** [comment]
Feel free to reopen if you are still having problems
