### ISSUE TITLE
Why internal server error displayed, when invalid url is entered in browser?

### ISSUE THREAD

**Issue by amirtbi** [keycloakify/keycloakify#361]
I am using keycloak V.21.0.2 and my template.ftl structure is as follows:
```
<#macro registrationLayout bodyClass="" displayInfo=false displayMessage=true displayRequiredFields=false showAnotherWayIfPresent=true>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="${properties.kcHtmlClass!}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="icon" href="${url.resourcesPath}/img/kando.ico" />
    <meta name="robots" content="noindex, nofollow">
    <link href='${url.resourcesPath}/css/index.css' rel='stylesheet'/>
    
      <#nested "styles">
       
    
</head>
<body>
  <div id="app"></div>
  <script id="environment" type="application/json">


    {
  
      "urls": {
        "project":"${url.resourcesPath}",
        "loginResetCredentials": "${url.loginResetCredentialsUrl}",
        "login": "${url.loginUrl}",
        "registration": "${url.registrationUrl}",
        "loginAction": "${url.loginAction}",
        "registrationAction": "${url.registrationAction}",
        "loginRestartFlowUrl":"${url.loginRestartFlowUrl}"
      },
      "titles": {
        "loginProfileTitle": "${msg("loginProfileTitle")}",
        "loginAccountTitle": "${msg("loginAccountTitle")}",
        "registerTitle": "${msg("registerTitle")}",
        "emailForgotTitle": "${msg("emailForgotTitle")}",
        "confirmLinkIdpTitle": "${msg("confirmLinkIdpTitle")}",
        "emailLinkIdpTitle": "${msg("emailLinkIdpTitle", idpDisplayName)}"
      },
      "permissions": {
        "usernameEditDisabled": <#if usernameEditDisabled??>true<#else>false</#if>,
        "loginWithEmailAllowed": <#if realm.loginWithEmailAllowed>true<#else>false</#if>,
        "registrationEmailAsUsername": <#if realm.registrationEmailAsUsername>true<#else>false</#if>,
        "rememberMe": <#if realm.rememberMe>true<#else>false</#if>,
        "resetPasswordAllowed": <#if realm.resetPasswordAllowed>true<#else>false</#if>,
        "password": <#if realm.password>true<#else>false</#if>,
        "registrationAllowed": <#if realm.registrationAllowed>true<#else>false</#if>,
        "registrationDisabled": <#if registrationDisabled??>true<#else>false</#if>,
        "passwordRequired": <#if passwordRequired??>true<#else>false</#if>,
        "phoneNumberIsRequired": <#if phoneNumberRequired??>true<#else>false</#if>,
        "verifyPhoneIsRequired":  <#if verifyPhone??>true<#else>false</#if>,
        "supportPhone": <#if supportPhone??>true<#else>false</#if>
       
      },
      "error":{
        "errorCondition": <#if !(auth?has_content && auth.showUsername() && !auth.showResetCredentials())>true<#else>false</#if>,
        "requiredField": <#if displayRequiredFields>true<#else>false</#if>
      },
      "labels": {
        "firstName": "${msg("firstName")}",
        "lastName": "${msg("lastName")}",
        "username": "${msg("username")}",
        "usernameOrEmail": "${msg("usernameOrEmail")}",
        "email": "${msg("email")}",
        "password": "${msg("password")}",
        "passwordConfirm": "${msg("passwordConfirm")}",
        "rememberMe": "${msg("rememberMe")}",
        "doForgotPassword": "${msg("doForgotPassword")}",
        "doLogIn": "${msg("doLogIn")}",
        "doSubmit": "${msg("doSubmit")}",
        "noAccount": "${msg("noAccount")}",
        "doRegister": "${msg("doRegister")}",
        "backToLogin": "${kcSanitize(msg("backToLogin"))?no_esc}",
        "confirmLinkIdpContinue": "${msg("confirmLinkIdpContinue")}",
        "doClickHere": "${msg("doClickHere")}"
      },

      "totp":{
        "totpTopSecret": <#if totp??>"${(totp.totpSecret!'')}"<#else>""</#if>,
        "totpQrCode": <#if totp??>"${(totp.totpSecretQrCode)}"<#else>""</#if>,
        "totpError": <#if messagesPerField.existsError('totp')>true<#else>false</#if>
      },
      "forms": {
        "loginUsername": "${(login.username!'')}",
        "loginRememberMe": <#if login.rememberMe??>true<#else>false</#if>,
        "selectedCredential": "${(auth.selectedCredential!'')}",
        "registerFirstName": <#if register??>"${(register.formData.firstName!'')}"<#else>""</#if>,
        "registerLastName": <#if register??>"${(register.formData.lastName!'')}"<#else>""</#if>,
        "registerEmail": <#if register??>"${(register.formData.email!'')}"<#else>""</#if>,
        "registerUsername": <#if register??>"${(register.formData.username!'')}"<#else>""</#if>
      },
      "user": {
        "username": <#if user??>"${(user.username!'')}"<#else>""</#if>,
        "email": <#if user??>"${(user.email!'')}"<#else>""</#if>,
        "firstName": <#if user??>"${(user.firstName!'')}"<#else>""</#if>,
        "lastName": <#if user??>"${(user.lastName!'')}"<#else>""</#if>
      },
      "validations": {
        "firstName": <#if messagesPerField.existsError('firstName')>"${kcSanitize(messagesPerField.get('firstName'))?no_esc}"<#else>""</#if>,
        "lastName":  <#if messagesPerField.existsError('lastName')>"${kcSanitize(messagesPerField.get('lastName'))?no_esc}"<#else>""</#if>,
        "email": <#if messagesPerField.existsError('email')>"${kcSanitize(messagesPerField.get('email'))?no_esc}"<#else>""</#if>,
        "usernameOrPassword": <#if messagesPerField.existsError('username','password')>"${kcSanitize(messagesPerField.getFirstError('username','password'))?no_esc}"<#else>""</#if>,
        "username": <#if messagesPerField.existsError('username')>"${kcSanitize(messagesPerField.get('username'))?no_esc}"<#else>""</#if>,
        "password": <#if messagesPerField.existsError('password')>"${kcSanitize(messagesPerField.get('password'))?no_esc}"<#else>""</#if>,
        "passwordConfirm": <#if messagesPerField.existsError('password-confirm')>"${kcSanitize(messagesPerField.get('password-confirm'))?no_esc}"<#else>""</#if>,
        "PhoneOrCode": <#if messagesPerField.existsError('code','phoneNumber')>"${kcSanitize(messagesPerField.getFirstError('phoneNumber','code'))?no_esc}"<#else>""</#if>,
        "RegisterCode": <#if messagesPerField.existsError('registerCode')>"${kcSanitize(messagesPerField.get('registerCode'))?no_esc}"<#else>""</#if>    
      },
      "message": {
        "type": <#if displayMessage && message?has_content && (message.type != 'warning' || !isAppInitiatedAction??)>"${message.type}"<#else>""</#if>,
        "summary": <#if displayMessage && message?has_content && (message.type != 'warning' || !isAppInitiatedAction??)>"${kcSanitize(message.summary)?no_esc}"<#else>""</#if>
      },
      "instruction": {
        "title": "${msg("appRealmName",realm.displayName)}",
         "realmTitle":"${msg("realName",realm.name)}",
        "emailLinkIdp1": "${msg("emailLinkIdp1", idpDisplayName, realm.username, realm.displayName)}",
        "emailLinkIdp2": "${msg("emailLinkIdp2")}",
        "emailLinkIdp3": "${msg("emailLinkIdp3")}",
        "emailLinkIdp4": "${msg("emailLinkIdp4")}",
        "emailLinkIdp5": "${msg("emailLinkIdp5")}"
      },
      "social": [
        <#if realm.password && social.providers??>
          <#list social.providers as p>
            { 
              "alias": "${p.alias}",
              "displayName": "${p.displayName!}",
              "loginUrl": "${p.loginUrl}"
            }<#sep>, </#sep>
          </#list>
        </#if>
      ]
    }
  </script>
 <#nested "scripts">
</body>
</html>
</#macro>
```
and i use vue 3 and webpack.config for building my pages. and each .ftl page is build as follows:
```
<#import "template.ftl" as layout>
<@layout.registrationLayout displayMessage=!messagesPerField.existsError('firstName','lastName','email','username','password','password-confirm'); section>
  <#if section = "scripts">
    <script typo="module" src="${url.resourcesPath}/js/register.js"></script>
  </#if>
</@layout.registrationLayout>
```
, 
My issue, is, when use enter an invalid url, my error page is not displayed, and internal server error displayed, And also, the keycloak tells the following message:

> | Caused by: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "loginAction"; see cause exception! The type of the containing value was: extended_hash+string (org.keycloak.forms.login.freemarker.model.UrlBean wrapped into f.e.b.StringModel)
idp     | 
idp     | ----
idp     | FTL stack trace ("~" means nesting-related):
idp     |       - Failed at: ${url.loginAction}  [in template "template.ftl" in macro "registrationLayout" at line 28, column 25]
idp     |       - Reached through: @layout.registrationLayout displayMes...  [in template "error.ftl" at line 2, column 1]
idp     | ----
idp     |       at freemarker.ext.beans.BeanModel.get(BeanModel.java:185)
idp     |       at freemarker.core.Dot._eval(Dot.java:43)
idp     |       at freemarker.core.Expression.eval(Expression.java:101)
idp     |       at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
idp     |       at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
idp     |       at freemarker.core.Environment.visit(Environment.java:383)
idp     |       at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:889)
idp     |       at freemarker.core.Environment.invokeMacro(Environment.java:825)
idp     |       at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
idp     |       at freemarker.core.Environment.visit(Environment.java:347)
idp     |       at freemarker.core.Environment.visit(Environment.java:353)
idp     |       at freemarker.core.Environment.process(Environment.java:326)
idp     |       at freemarker.template.Template.process(Template.java:383)
idp     |       at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
idp     |       ... 38 more
idp     | Caused by: java.lang.reflect.InvocationTargetException
idp     |       at jdk.internal.reflect.GeneratedMethodAccessor279.invoke(Unknown Source)
idp     |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
idp     |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
idp     |       at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)
idp     |       at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:233)
idp     |       at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
idp     |       ... 51 more
idp     | Caused by: java.lang.RuntimeException: action URI not set
idp     |       at org.keycloak.forms.login.freemarker.model.UrlBean.getLoginAction(UrlBean.java:48)
idp     |       ... 57 more

**Comment by garronej** [comment]
Hello,  
The issue has been closed?

**Comment by amirtbi** [comment]
> Hello, The issue has been closed?

Actually, this issue is occured in creating theme By vue js 3. I thought, the above issue or better above problem be mentioned in main keycloak repository, Q&A section. But if you have any ideas about this, i would be appreciated.

**Comment by garronej** [comment]
Hi @amirtbi,  
It's best to have a generic script that converts the FTL context into a JavaScript object.  
You can reuse the one of Keycloakify: https://github.com/keycloakify/keycloakify/blob/f98d1aaadec130217467cb5273bb9beb27c1e1f3/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl  

It convert the FTL `.data_model` into a JavaScript `kcContext` variable that is accecible globally.  

You may notice that we attempt/recover every call that can throw so we are sure that the template will never crash when trying to dereference some variable (like you are experiencing).  

However even catched error will be printed in the Keycloak log, this is less than ideal, so we have implemented certain exception here:  

https://github.com/keycloakify/keycloakify/blob/f98d1aaadec130217467cb5273bb9beb27c1e1f3/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L163-L198  

For example we avoid to dereference `url.loginAction` in `error.ftl`.  

You can reuse this scrip, just make sure to remove:  

https://github.com/keycloakify/keycloakify/blob/f98d1aaadec130217467cb5273bb9beb27c1e1f3/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L122-L126  

https://github.com/keycloakify/keycloakify/blob/f98d1aaadec130217467cb5273bb9beb27c1e1f3/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#LL16C106-L16C142  

End result:  

<img width="1524" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/11e41d0a-a4f2-49b8-babb-258dffb9c16f">
