### ISSUE TITLE
Account totp: Hide the totp secrets

### ISSUE THREAD

**Issue by TN1ck** [keycloakify/keycloakify#362]
Hi all,

Although not yet officially supported by keycloakify, I implemented the Totp page (totp.ftl) for the account theme for internal usage. It works fine, the only issue is that it leaks the totp secrets at the moment in the credentials field, while not the worst thing, definitely should be addressed as afaik they can be used to authenticate another device with the token and thus problematic for the security.

I haven't really looked into the codebase, but I know that for the login theme fields are already whitelisted. I try to look into it myself, but wanted to open the issue first before providing a PR. EDIT: Ok it's the [ftl_object_to_js_code_declaring_an_object.ftl](https://github.com/keycloakify/keycloakify/blob/58301e0844851dfccab743bb6ca28bbb49458f85/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl) file where this would need to be changed.

Here is a screenshot of the problematic fields:

![Screenshot 2023-06-17 at 19 34 06](https://github.com/keycloakify/keycloakify/assets/2116347/c33bcc56-6eb6-476e-b6f0-a1168872679d)

I also checked the keycloak.v2 theme and what they deliver in the api, definitely not the secret:
![Screenshot 2023-06-17 at 19 36 25](https://github.com/keycloakify/keycloakify/assets/2116347/acdb51bf-b5f9-4ff5-8b4c-6680b4b7424e)

**Comment by garronej** [comment]
Hi @TN1ck,  
Thanks for reporting.  
Preventing thoses from being forwarded to the client side but I didn't bother doing it as I was told it has no security implication.  
I also though that the keycloak team wouldn't expose to the FreeMarker context any sensitive data but it might as well be an oversight from their part.  
I'm worried about the implication of hiding this secret. Isn't it ever useful?

**Comment by TN1ck** [comment]
@garronej Thanks for the reply! Honestly I'm not that sure myself, I can research a bit more, but I thought I can use these values to connect another phone with the same code, the security implication here would be that the second factor can easily be replicated if someone got access to this page. It's not that serious though.

I did see some sensitive stuff in the Freemarker context e.g. smpt credentials for example can end up there, so I wouldn't trust that argument too much.

I don't think this is ever useful, normally you would connect a new phone by generating another otp code and deleting the other. But let me check next week with someone more well versed in security.

**Comment by garronej** [comment]
Here you go, just released a new version (3.12.7) currently being published, it makes sures thoses value are not in the kcContext client side.  
Thanks for reporting.

**Comment by garronej** [comment]
> I did see some sensitive stuff in the Freemarker context e.g. smpt credentials for example can end up there, so I wouldn't trust that argument too much.  

Is that so? If it's the case I should hide this as well...

**Comment by TN1ck** [comment]
> > I did see some sensitive stuff in the Freemarker context e.g. smpt credentials for example can end up there, so I wouldn't trust that argument too much.
> 
> Is that so? If it's the case I should hide this as well!

You fixed that already in version 7, it appeared on an url like:

http:localhost:8080/auth/realms/customer/protocol/

You can still see `smtpConfig` in the source, but it's commented out with the "submit an issue if you need this" message.

**Comment by TN1ck** [comment]
> Here you go, just released a new version (3.12.7) currently being published, it makes sures thoses value are not in the kcContext client side. Thanks for investigating the issue.

Wow, you're so fast! Just tested it, the values are sadly still there, I did a very similar try at the code as you, but couldn't make it work either.
![Screenshot 2023-06-18 at 09 43 45](https://github.com/keycloakify/keycloakify/assets/2116347/3d7798cb-f8cf-4aad-bfc7-380f36aaf719)

![Screenshot 2023-06-18 at 09 43 28](https://github.com/keycloakify/keycloakify/assets/2116347/8b8fb8e3-6632-4f86-a225-08ed3d5c7a62)

**Comment by garronej** [comment]
Ah, I understand now! My apologies for the confusion, I've just recognized that `otpCredentials` is indeed an array. I'll proceed with the necessary correction.

> Do note that `smtpConfig` is still observable in the source code, albeit it's been commented out accompanied by a message saying, "Please submit an issue if this is required."

While this does seem familiar, I've not been able to locate the corresponding case within the code despite my thorough search. Similarly, a related issue has also eluded me. If you could possibly recall and share additional details, it would significantly assist in resolving this matter. Thank you!

**Comment by garronej** [comment]
@TN1ck it should be fixed in 7.12.8. Sorry I didn't pay enough attention to your screenshot.  

Still curious about the SMTP secret though...

**Comment by TN1ck** [comment]
> @TN1ck it should be fixed in 7.12.8. Sorry I didn't pay enough attention to your screenshot.
> 
> Still curious about the SMTP secret though...

Thank you so much! Just tested, the secrets are properly hidden now:

![Screenshot 2023-06-19 at 00 48 13](https://github.com/keycloakify/keycloakify/assets/2116347/030b2ac8-695b-48c2-a9ab-e4474d3364aa)


About the smtpConfig:

Sorry for not being specific enough. I encountered this problem with version `6.11.8`, I don't know when the exact change happened, but in that version, if you would go to e.g. `http://localhost:8080/auth/realms/<realm>/protocol/`, the `error.ftl` would be triggered and there you could see `smtpConfig` being leaked in the HTML source.

This problem got fixed at least with `7.11.11`, since then, these sensitive keys would be hidden like this in the HTML source:
![Screenshot 2023-06-19 at 00 52 11](https://github.com/keycloakify/keycloakify/assets/2116347/8e57960e-3495-4f08-8fe4-6170393f9341)

**Comment by garronej** [comment]
@TN1ck Ohhhh I see!  
On the error page ther's an accept list on what realm values can be forwarded!  
https://github.com/keycloakify/keycloakify/commit/23fedbf94a2ff0d408876ead38889c41412f4da2   

Thanks a lot for helping me clarifying that.  

Thanks for helping me patch this vulnerability.
