### ISSUE TITLE
Expecting Account Theme 

### ISSUE THREAD

**Issue by filipzava** [keycloakify/keycloakify#364]
Hi 👋 @garronej!
In my keycloakify project I am not using `account` theme, but from extra pages removal (7.14.0) I got this error: 

![image](https://github.com/keycloakify/keycloakify/assets/12759049/20b3d5d1-7e00-4157-bbdf-ee375fd29ae3)

Using: 
yarn: 1.22.19
node: 16.18

**Comment by thosil** [comment]
Hi, I'm busy fixing it ;-)

**Comment by garronej** [comment]
@filipzava @thosil sorry about this.  
I pushed an update this morning at 4AM that wasn't tested enough.  
Everything should be fixed in 7.14.1, now being deployed.  

Best regards.
