### ISSUE TITLE
Register user profile appears blank

### ISSUE THREAD

**Issue by LeonardaH** [keycloakify/keycloakify#365]
Hey, my register user profile page is visible on storybook but when I build a theme it appears blank. How should I fix it? All others pages.ftl work as expected but register-user-profile.ftl acts different.

**Comment by garronej** [comment]
Hello @LeonardaH,  
Can you please provide the error message you get's in the console?  
You kcContext also would help:  
<img width="690" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/c0fba5d7-d57c-490e-8223-cb786127f3bc">

And the generated HTML of the page.  

Ideally the code as well.

**Comment by LeonardaH** [comment]
I've tried to console.log(kcContext) but when I built it, it does not appear because it can not even retrieve that page ( I can not get an error as well). Here is the screenshot of kcContext in storybook. 
![Screenshot 2023-06-26 111857](https://github.com/keycloakify/keycloakify/assets/93203715/fa019008-c182-49f4-8548-58c8102f256e)
When it was built the register page was not recognized and it appeared blank. Here are some screenshots: 
![image](https://github.com/keycloakify/keycloakify/assets/93203715/6fb3f781-0b3b-42ff-8ac2-b5536f0b9f2a)
![image](https://github.com/keycloakify/keycloakify/assets/93203715/15cbbf45-db99-429a-a834-2d63e369ac1f)
![Screenshot 2023-06-26 110624](https://github.com/keycloakify/keycloakify/assets/93203715/7631de79-1abf-45cf-af2f-591ca82269d0)
![Screenshot 2023-06-26 110652](https://github.com/keycloakify/keycloakify/assets/93203715/27893a06-e6a9-487f-9db1-1e502430feb6)
![Screenshot 2023-06-26 110700](https://github.com/keycloakify/keycloakify/assets/93203715/965691ab-a6c7-436c-9821-da962890bdb2)

**Comment by garronej** [comment]
Hi @LeonardaH,  

Sorry, I cannot make sence of:  
> I've tried to console.log(kcContext) but when I built it, it does not appear because it can not even retrieve that page ( I can not get an error as well).  

If in your build_keycloak directory you have `register-user-profile.ftl` and if in your Keycloak you have User Profile features enabled the page should be used.  

<img width="364" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/7c5fa39b-ca02-4bc1-9895-592ca66a858f">

I'm willing to help but please share a reproduction repo or more information.

**Comment by LeonardaH** [comment]
Sorry but where can I find User Profile features in Keycloak? I does not show up in my keycloak account...

**Comment by garronej** [comment]
It has to be enabled via environement variable, it's explained here: https://docs.keycloakify.dev/realtime-input-validation

**Comment by LeonardaH** [comment]
Thanks! It works now.

**Comment by garronej** [comment]
Let's go! congrats
