### ISSUE TITLE
keycloakify build broken

### ISSUE THREAD

**Issue by satanshiro** [keycloakify/keycloakify#372]
upgrading to version beginning with 7.14.1 results in an error of : 

`🔏 Building the keycloak theme...⌚
Can't locate your theme source directory. It should be either: 
src/ or src/keycloak-theme.
Example in the starter: https://github.com/keycloakify/keycloakify-starter/tree/main/src/keycloak-theme`
I can't completely discern myself the reason it looks like keycloakify is looking for specific folders and does not actually work if the app is directly under src, even though the error makes it seem as it should
probably something in the code here : https://github.com/keycloakify/keycloakify/compare/v7.14.0...v7.14.1

**Comment by satanshiro** [comment]
didn't notice https://docs.keycloakify.dev/migration-guides/v6-greater-than-v7
I'll tr to fix it on my end thanks

**Comment by garronej** [comment]
Hi @satanshiro,  

I created a file to help other pepole like you that might be perplex as to where the source file can be located:  
https://github.com/keycloakify/keycloakify-starter/blob/main/src/keycloak-theme/README.md  

Thank for the feedback
