### ISSUE TITLE
How do I change the text in kcContext.message.summary?

### ISSUE THREAD

**Issue by Kytila** [keycloakify/keycloakify#375]
Hi, thanks for supporting the project.
I am using keycloakify-starter. Faced with the problem that I can't override the text of kcContext.message.summary. The text matches the invalidUserMessage key, but when I change its values I still get the default text. I try to change the values using the doForgotPassword key as an example.

**Comment by garronej** [comment]
Hello @Kytila,  

What are you trying to do exactly? Are you in the process of mocking the `kcContext` for devlopement puposes or are you trying to change the message you're getting in production?

**Comment by garronej** [comment]
Coud you tell me precisely from what to what you'd like to change the message? Thanks

**Comment by Kytila** [comment]
I'm trying to change the message for production. Here is the key and text that I want to change `"invalidUserMessage": "Invalid username or password."`, this is the message that comes when a user entered an invalid username or password

**Comment by garronej** [comment]
I realized yesterday that Keycloakify does not enable to customize the messages from `kcContext.messages.sumarry` nor the message from `kcContext.messagesPerField` yet.  
I'll be working on it.  

In the meantime you can hack a solution like:  

```ts
kcContext.message.submary === "Invalid username or password" ? "your message" : kecontext.message.submary
```  

If the reason for wanting to change the message is just to change the language, there is a better way.

**Comment by garronej** [comment]
Thank you for your understanding, I'll let you know when I have a better solution.

**Comment by kpoelhekke** [comment]
I'm running into the same problem. For the time being I've created a little script that will run over the translation source files and if a match is found it will return the `msgStr()` value. It will also catch any `{0}` `{1}` etc values passes them to the `msgStr` function:

```ts
export function translateLoginSummary(summary: string, i18n: I18n) {
  const { msgStr } = i18n;

  for (const [key, value] of [
    ...Object.entries(nlBaseStrings),
    ...Object.entries(enBaseStrings),
    ...Object.entries(esBaseStrings),
  ]) {
    const match = summary.match(new RegExp(`^${value.replace(/{\d}/, "(.+)")}$`));
    if (match && value !== "{0}") {
      const [, ...args] = match;
      return msgStr(key as MessageKey, ...args);
    }
  }

  return summary;
}
```

**Comment by garronej** [comment]
@kpoelhekke thanks for sharing your workaround!  

Be aware though that the resources files are big, preloading many languages considerably increace the bundle size.  

I put in my todo to inject custom translation to the server side. This is the next thing I will do regarding this project.

**Comment by kpoelhekke** [comment]
Yeah good point, so Ideally you would lazy load them based on the `currentLanguageTag` or just include all the possible string that would need to be converted.

This also reduces the risk of a wrong match. For now we will work with this and wait for your server side fix 🙌

**Comment by garronej** [comment]
I'll do it soon

**Comment by garronej** [comment]
It's done in v7.15 🚀  
I've done a little video to introduce the feature: https://youtu.be/D6tZcemReTI

**Comment by 18Miguel** [comment]
Hi! I'm trying to use keycloakify v11 and I'm having trouble overriding the message for `emailSentMessage`. I’ve added a custom translation, but it always falls back to the default one.

**Comment by garronej** [comment]
@18Miguel, makes sense. You can't externalize your i18n resources.  

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/be8e2923-6ab7-4dec-a3b6-713f6ba65b4c" />

https://docs.keycloakify.dev/features/i18n/adding-new-translation-messages-or-changing-the-default-ones  

You need to declare your translation in the i18n.ts file, it's analyzed at build time by keycloakify.
