### ISSUE TITLE
Password validation issues

### ISSUE THREAD

**Issue by Cherrywoood** [keycloakify/keycloakify#377]
Hello, I am defining a password policy in Keycloak. When I use the keycloak theme the error messages appear, but when I use my theme created with Keycloakify the error message does not appear.
![image](https://github.com/keycloakify/keycloakify/assets/58643112/f4c28129-b950-4da6-a4ac-38db27a91127)

Keycloak theme:
![image](https://github.com/keycloakify/keycloakify/assets/58643112/cc14bb2f-16dd-48e5-b0dd-dc276610e20b)

My theme:
![image](https://github.com/keycloakify/keycloakify/assets/58643112/52d8fdc1-7b0a-4dd4-a3df-13c14db2953d)

I also get validation and error messages that I didn't define.
![image](https://github.com/keycloakify/keycloakify/assets/58643112/a80a62c6-a89e-49c2-9fc7-876fccc976fc)

**Comment by garronej** [comment]
Hello @Cherrywoood,  
Do you use `Register` or `RegisterUserProfile`?  

Can I see the code of your page?

**Comment by Cherrywoood** [comment]
I use RegisterUserProfile.
https://github.com/Cherrywoood/react-keycloak

**Comment by Cherrywoood** [comment]
Thank you very match
