### ISSUE TITLE
Person-name-prohibited-characters validation

### ISSUE THREAD

**Issue by Cherrywoood** [keycloakify/keycloakify#378]
Hello, I'm still having some validation issues. The thing is that  I want to use the person-name-prohibited-characters validator for the first and last name, but for some reason it doesn't work on the client side.
Perhaps I'm defining this validator incorrectly in the context?
![image](https://github.com/keycloakify/keycloakify/assets/58643112/ccdde727-ecac-419d-8e2f-1eaddc0a7a78)

And is there more detailed documentation on client-side validation in Keyclokify? In Keycloak, in the email validator, for example, you cannot override the error message, is it possible to do this in keycloakify?

**Comment by garronej** [comment]
Is that a built-in validator? What is it suposed to do?  
I haven't implemented it yet

**Comment by garronej** [comment]
Yes, its prossible to update the error message for email, example:  
<img width="680" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/949d4989-c1e9-4ba1-8340-4cc8a41cb0a8">

**Comment by Cherrywoood** [comment]
> Это встроенный валидатор? Что он должен делать? Я его еще не внедрил

This is the validator in Keycloak.
![image](https://github.com/keycloakify/keycloakify/assets/58643112/a75d6bb7-b0bc-49e9-aebd-bb38fb0054a9)

As I saw in the Keyclokify code it listed as Existing validator.
![image](https://github.com/keycloakify/keycloakify/assets/58643112/7ab1fb14-a0de-4301-81df-5193f06933ce)

**Comment by Cherrywoood** [comment]
> Да, возможно обновить сообщение об ошибке для электронной почты, например: <img alt="изображение" width="680" src="https://user-images.githubusercontent.com/6702424/251829450-949d4989-c1e9-4ba1-8340-4cc8a41cb0a8.png">

Can you tell me how to do it in code?

**Comment by garronej** [comment]
It's recognized as a type but it's not actually implemented.  

You can find here the hook that given a `kcContext.profile` generates the correct errors in realtime.  

https://github.com/keycloakify/keycloakify/blob/main/src/login/lib/useFormValidation.tsx  

You import it here:  https://github.com/Cherrywoood/react-keycloak/blob/854581cde46ed75f7ca92d0e442d7e194b7a793c/src/keycloak-theme/login/pages/shared/UserProfileFormFields.tsx#L4

You are free to customize it however you like.  

I only bothered implementing the more commonly used validator like:  
- https://github.com/keycloakify/keycloakify/blob/7214dbccdbb4c366c8c327f9882c0064cdc265c2/src/login/lib/useFormValidation.tsx#L239  
- https://github.com/keycloakify/keycloakify/blob/7214dbccdbb4c366c8c327f9882c0064cdc265c2/src/login/lib/useFormValidation.tsx#L329  
- https://github.com/keycloakify/keycloakify/blob/7214dbccdbb4c366c8c327f9882c0064cdc265c2/src/login/lib/useFormValidation.tsx#L361  
- https://github.com/keycloakify/keycloakify/blob/7214dbccdbb4c366c8c327f9882c0064cdc265c2/src/login/lib/useFormValidation.tsx#L389  

But if you want contribute and add `person-name-prohebited-characters`, your contribution will be very welcome!

**Comment by Cherrywoood** [comment]
> But if you want contribute and add `person-name-prohebited-characters`, your contribution will be very welcome!

Unfortunately, I'm not that good at it. But ok, thanks, I'll know that it's not implemented.
What about the error message. Do I understand correctly that I need to override invalidEmailMessage in i18n.ts?

**Comment by garronej** [comment]
Keep in mind though that frontend validation is only chery on top. You still have backend validation providing error message. The default Keycloak don't provide any frontend validation whatsoever

**Comment by Cherrywoood** [comment]
Yes, I have validation on the backend too.
