### ISSUE TITLE
Keycloakify fails after 7.13.2 on Linux

### ISSUE THREAD

**Issue by x4121** [keycloakify/keycloakify#381]
Hi, we recently updated Keycloakify and had our builds fail on Linux machines and in AWS CodeBuild (`aws/codebuild/standard:7.0` which is built on top of Ubuntu 22.04).

I tried it locally on a Ubuntu 22.04 with Node 18.16.1 and get the same issue as CodeBuild (which is using Node 18.16.0).
Colleagues running MacOS don't seem to have this issue and can build the themes.
I also don't get the issue if the local git repository isn't cleaned up (e.g. `git clean -xdf`) before switching to a newer version of Keycloakify.
Is it possible that the folder `build_keycloak` is not always created in newer versions?

Last version that seems to work for us was 7.13.2

```
🔏 Building the keycloak theme...⌚
--
758 | node:fs:601
759 | handleErrorFromBinding(ctx);
760 | ^
761 |  
762 | Error: ENOENT: no such file or directory, open '/codebuild/output/src1672772893/src/github.com/****/build_keycloak/pom.xml'
763 | at Object.openSync (node:fs:601:3)
764 | at Object.writeFileSync (node:fs:2249:35)
765 | at generateJavaStackFiles (/codebuild/output/src1672772893/src/github.com/****/node_modules/keycloakify/bin/keycloakify/generateJavaStackFiles.js:79:12)
766 | at /codebuild/output/src1672772893/src/github.com/****/node_modules/keycloakify/bin/keycloakify/keycloakify.js:180:87
767 | at step (/codebuild/output/src1672772893/src/github.com/****/node_modules/keycloakify/bin/keycloakify/keycloakify.js:67:23)
768 | at Object.next (/codebuild/output/src1672772893/src/github.com/****/node_modules/keycloakify/bin/keycloakify/keycloakify.js:48:53)
769 | at fulfilled (/codebuild/output/src1672772893/src/github.com/****/node_modules/bin/keycloakify/keycloakify.js:39:58)
770 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
771 | errno: -2,
772 | syscall: 'open',
773 | code: 'ENOENT',
774 | path: '/codebuild/output/src1672772893/src/github.com/****/build_keycloak/pom.xml'
775 | }
776 |  
777 | Node.js v18.16.0
778 | error Command failed with exit code 1.
779 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
780 |  
781 | [Container] 2023/07/12 16:18:05 Command did not exit successfully yarn keycloakify exit status 1
```

**Comment by x4121** [comment]
Hi @garronej,
thanks for you quick reply.
The repo is sadly not open source, since it's a bigger repo containing our whole Keycloak setup.
Is there some example project I could try to use? I'm not a frontend dev, but maybe I can help to reproduce the bug in a minimal setup

**Comment by garronej** [comment]
Well ther's the starter project https://github.com/keycloakify/keycloakify-starter

**Comment by x4121** [comment]
OK, I'm getting the same error there as well.

Can you try:
```
git clone --recursive https://github.com/keycloakify/keycloakify-starter
docker run -it --rm -v $PWD/keycloakify-starter:/keycloakify-starter ubuntu:20.04

# in docker
apt update && apt install -y curl
curl -sL https://deb.nodesource.com/setup_16.x | bash -
apt install -y nodejs
npm install -g yarn
cd keycloakify-starter
yarn && yarn keycloakify
```

**Comment by garronej** [comment]
So, I investigated,  
Can I get the directory structure of your project.  
My guess is you have a "keycloak-theme" somewhere within your "src/" directory 
but you don't have neither a "login" nor "account" nor an "email" directory directly within your "keycloak-theme" dir.  

Is that the case?

**Comment by garronej** [comment]
Ok, I'm having a look to your repro setup thanks!

**Comment by x4121** [comment]
We do have a `Login` folder in `src/KcApp/keycloak-theme`, but no `Account` or `Email`.
We send out emails via a separate service that is called by an SPI, we are not using Keycloak for email templates.
Right now we are also not using the account client in Keycloak as well.

**Comment by garronej** [comment]
> OK, I'm getting the same error there as well.
> 
> Can you try:
> 
> ```
> git clone --recursive https://github.com/keycloakify/keycloakify-starter
> docker run -it --rm -v $PWD/keycloakify-starter:/keycloakify-starter ubuntu:20.04
> 
> # in docker
> apt update && apt install -y curl
> curl -sL https://deb.nodesource.com/setup_16.x | bash -
> apt install -y nodejs
> npm install -g yarn
> cd keycloakify-starter
> yarn && yarn keycloakify
> ```

If this doesen't work it's unreleated.  
It's because we are supposed to build the app then build the theme.  
So it's either `yarn build && npx keycloakify` or `yarn build-keycloak-theme` (there is a script as an alias)  

`yarn keycloakify` is just an equivalent of `npx keycloakify`.  Keycloakify takes as main input the `build` dir.

**Comment by garronej** [comment]
> We do have a `Login` folder in `src/KcApp/keycloak-theme`, but no `Account` or `Email`. We send out emails via a separate service that is called by an SPI, we are not using Keycloak for email templates. Right now we are also not using the account client in Keycloak as well.

I do not handle capitalized directory names. (Maybe I should). Try renaming `Login` to `login`.  

**Be carful though** if you just rename a file or directory by changing only the case, git won't notice (it's such a pain).  

I think we got things figured out now. It explain everything. Why it works on your colleags machines, they must have "login" uncapitalized in their local copy but it's capitalized when you pull a fresh repo.

**Comment by x4121** [comment]
> It's because we are supposed to build the app then build the theme.

Ah OK, that makes sense. Then I can't reproduce the issue with the `keycloakify-starter` repo.
If I run `yarn && yarn build && yarn keycloakify` instead of `yarn && yarn keycloakify` it's working fine.
So at least it seems related to our setup.

> I do not handle capitalized directory names

I think that might be the clue. Linux and MacOS handle capitalization differently (e.g. the mentioned git issue doesn't exist under Linux. If you change the capitalization under Linux it will show as a diff in git).
This would also explain why my colleagues on MacOS don't see the same issue. I would guess Keycloakify expects `login` and `account`, and under Linux it will not ignore the wrong capitalization of our folders, while it will ignore the capitalization under MacOS.

Thanks so much for the help. I'll fix the capitalization in our repo

Can you try

**Comment by EmperorPeter3** [comment]
Faced with the same problem. Renaming helps.
