### ISSUE TITLE
[Docs] Add an example of a custom webpack configuration

### ISSUE THREAD

**Issue by ddubrava** [keycloakify/keycloakify#384]
Hi! Thank you for maintaining this package.

Since CRA is a little bit deprecated (see https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741, https://github.com/reactjs/react.dev/pull/5487), it would be great to add an example of a custom webpack plugin.

I think we can take the key points from this issue, I faced all of them when was implementing the config - https://github.com/keycloakify/keycloakify/issues/47

**Comment by ddubrava** [comment]
btw, I've built it without CRA, so I think I can contribute.

**Comment by garronej** [comment]
Agreed,  
Do you suggest we eject the Keycloakify starter? 🤔
Or maybe we should just focus our efforts on supporting vite. I think I can get it done by september.  
Is there that many pepoles still using webpack anyway? 
Beside all the project that didn't migrate away from CRA yet I mean.

**Comment by garronej** [comment]
Ok, good points.  
Don't worry I won't deprecate it, it's true that there's a ton of very usefull plugins that are Webpack specific.  

Your PR will be much appreciated thanks!

**Comment by ddubrava** [comment]
> Ok, good points. Don't worry I won't deprecate it, it's true that there's a ton of very usefull plugins that are Webpack specific.
> 
> Your PR will be much appreciated thanks!

Could you please check my comment in this issue - https://github.com/keycloakify/keycloakify/issues/47? I'm trying to use the custom config, but unfortunately, there are still some issues.

**Comment by garronej** [comment]
I can probably fix this

**Comment by ddubrava** [comment]
> I can probably fix this

Thanks! Any idea why it's not working? Also, do you know of any temporary fixes?

**Comment by garronej** [comment]
I just released a patch, should be fixed in 7.15.1 let me know if it isn't the case

**Comment by ddubrava** [comment]
> I just released a patch, should be fixed in 7.15.1 let me know if it isn't the case

It solves the issue with missing `process.env`, but URLs are still invalid (see the related issue) - GET http://localhost:8080/src_login_KcApp_tsx.bundle.js net::ERR_ABORTED 404 (Not Found). I'll create a repro tomorrow morning. 

`process.env` is not the main issue, since it can be hacked via `DefinePlugin`. But the problem is that URLs to resources are not updated, they are from '/'. 

If you have some time, could you please explain why we have `process.env` in a browser, and how it works in CRA. Maybe it will help me to fix the issue.

Thanks for your hard work, I appreciate it

**Comment by garronej** [comment]
> If you have some time, could you please explain why we have process.env in a browser, and how it works in CRA. Maybe it will help me to fix the issue.  

In CRA all environements variables prefixed by `REACT_APP_` available when the app is build (`npx react-scripts build`) are made available through `process.env`.  
`process.env` is where you read the ENV in node so they made this decision to make the two runtime as isomorphic as possible.  

Regarding the `PUBLIC_URL` env. This one is special.  
See, in the `package.json` of a CRA project there is usually a `"homepage"` property. Well, when this property isn't defined or when its something like `"homepage": "https://xxx.yy"` the `process.env["PUBLIC_URL"]` will be `` but when it's something like `homepage": "https://xxx.yy/a/b/c"` it will be `/a/b/c`.  
This is to enable the app to be hosted elsewhere than at the root of the domain.  
I need to read this value only for the mocks, to know where to find public static assets that are otherwise provided by Keycloak.

**Comment by garronej** [comment]
In v5  I had a "Supported framwork" section in the doc: https://docs.keycloakify.dev/v/v5/#supported-react-frameworks  
Maybe it can be of some use...  

![image](https://github.com/keycloakify/keycloakify/assets/6702424/5c69001f-0b5e-4780-be42-aa93b7e539ec)

Have you though about starting from the starter project and running `npx react-scripts eject`.  

https://create-react-app.dev/docs/available-scripts/#npm-run-eject

**Comment by ddubrava** [comment]
> Have you though about starting from the starter project and running `npx react-scripts eject`.
> 
> https://create-react-app.dev/docs/available-scripts/#npm-run-eject

I tried, it's very complex and it's really hard to figure out what's going on there

**Comment by ddubrava** [comment]
> > If you have some time, could you please explain why we have process.env in a browser, and how it works in CRA. Maybe it will help me to fix the issue.
> 
> In CRA all environements variables prefixed by `REACT_APP_` available when the app is build (`npx react-scripts build`) are made available through `process.env`. `process.env` is where you read the ENV in node so they made this decision to make the two runtime as isomorphic as possible.
> 
> Regarding the `PUBLIC_URL` env. This one is special. See, in the `package.json` of a CRA project there is usually a `"homepage"` property. Well, when this property isn't defined or when its something like `"homepage": "https://xxx.yy"` the `process.env["PUBLIC_URL"]` will be `` but when it's something like `homepage": "https://xxx.yy/a/b/c"` it will be `/a/b/c`. This is to enable the app to be hosted elsewhere than at the root of the domain. I need to read this value only for the mocks, to know where to find public static assets that are otherwise provided by Keycloak.

Ok, thank you. But it seems that the problem is not in the `PUBLIC_URL` since when you run locally, it's on '/'. Do you have any ideas why resources to URLs are not updated using the custom webpack configuration?

**Comment by ddubrava** [comment]
I made a reproduction - https://github.com/ddubrava/keycloakify-custom-webpack-repro

**Comment by garronej** [comment]
I've taken a look at your repository and have pinpointed the source of the issue.

As I previously communicated in this [guide](https://docs.keycloakify.dev/v/v5/#supported-react-frameworks), it is indeed true that the `build` directory should contain an `index.html`. However, it's also crucial to remember that all static assets, which include `*.bundle.js` files, must be within a `build/static` directory, regardless of their specific locations beyond that.

In the current setup of your repository, all files are situated at the root of the `build` directory. It's essential to tweak your webpack configuration to align with the requirements I detailed in this [document](https://docs.keycloakify.dev/v/v5/#supported-react-frameworks).

For a clearer picture, I suggest comparing your `build` directory with that of the starter repository.

Beside, If your objective is to develop a standalone theme, you might find it beneficial to run this [script](https://github.com/keycloakify/keycloakify-starter#standalone-keycloak-theme).

I hope this information assists you in resolving the problem. If you come across any further issues, please do not hesitate to contact me again. Alternatively, you are welcome to join our Discord channel for ongoing support and updates.

Best regards,

**Comment by ddubrava** [comment]
> I've taken a look at your repository and have pinpointed the source of the issue.
> 
> As I previously communicated in this [guide](https://docs.keycloakify.dev/v/v5/#supported-react-frameworks), it is indeed true that the `build` directory should contain an `index.html`. However, it's also crucial to remember that all static assets, which include `*.bundle.js` files, must be within a `build/static` directory, regardless of their specific locations beyond that.
> 
> In the current setup of your repository, all files are situated at the root of the `build` directory. It's essential to tweak your webpack configuration to align with the requirements I detailed in this [document](https://docs.keycloakify.dev/v/v5/#supported-react-frameworks).
> 
> For a clearer picture, I suggest comparing your `build` directory with that of the starter repository.
> 
> Beside, If your objective is to develop a standalone theme, you might find it beneficial to run this [script](https://github.com/keycloakify/keycloakify-starter#standalone-keycloak-theme).
> 
> I hope this information assists you in resolving the problem. If you come across any further issues, please do not hesitate to contact me again. Alternatively, you are welcome to join our Discord channel for ongoing support and updates.
> 
> Best regards,

Many thanks, I completely forgot to check the build directory

**Comment by ddubrava** [comment]
Well, I managed to resolve the 404 errors. You were right; we needed to maintain the same structure. The only downside is that now all the complexity from CRA has shifted to the custom configuration. Once everything is completed, I'll submit a PR along with the necessary documentation changes

**Comment by garronej** [comment]
Congratulation for pulling it out and sorry it was such a complex process to acheive.  

I'm sorry, I'll have offered a patch for not requireing the assets to be within a sub directory of the build dir if it was an easy fix but unfortunately it isn't.  

Looking forward for your PR.

**Comment by ddubrava** [comment]
Hi, unfortunately, I do not have enough time to submit a PR now. So if someone reads this issue, there are some tips.

Keycloakify requires a specific directory structure (from CRA, when you have static, js, css, etc.), but it relies not only on the structure but also on some approaches from CRA. For example, PUBLIC_URL in index.html. So I would strongly recommend ejecting the CRA config and adding what you need.

If you would like to clean up the CRA config, since it ejects into thousands of lines of code, I also do not recommend it. Everything is closely related, and there is a huge chance to break something.

**Comment by garronej** [comment]
https://docs.keycloakify.dev/keycloakify-in-my-codebase/in-your-react-project/in-your-webpack-project
