### ISSUE TITLE
When adding an environment variable to kcContext.properties I always get the default value

### ISSUE THREAD

**Issue by Kytila** [keycloakify/keycloakify#387]
Hi, I'm using keycloakify version 7.15.4. I can't get the value from the environment variable to be added to `kcContext.properties`. Thanks in advance for your help.

my package.json
<img width="464" alt="image" src="https://github.com/keycloakify/keycloakify/assets/41388910/b2c1bf37-d8bc-4a77-83d2-aa272a08f73a">

my .env
<img width="614" alt="image" src="https://github.com/keycloakify/keycloakify/assets/41388910/1597ee14-0f02-4877-9005-0778dab8745b">

result
<img width="965" alt="image" src="https://github.com/keycloakify/keycloakify/assets/41388910/8365ae84-1940-4219-85fd-7f8c2d482f25">

**Comment by garronej** [comment]
There must be a missunderstanding here,  
This is for passing over environement variables from the server running Keycloak over to the theme.  
If you wand to get the environement variables that are available when the theme is being build you'd use create-react-app builtin feature.  

You can put in your `.env` file:  

```env
REACT_APP_FOO=value_of_foo
```

You can access it this way in typescript:  

```ts
process.env["REACT_APP_FOO"]
```

your can also do `REACT_APP_FOO=value_of_foo_2 yarn build_keycloak_theme` to overwrite whatever is in the `.env` file.  

Now I'm curious, what are you refering to as `BASE_URL`?  

Like you want your main app to be hosted at `https://xxx.yy/${BASE_URL}`?

**Comment by garronej** [comment]
@Kytila you're welcome

**Comment by Kytila** [comment]
I was confused a bit and that's what caused the question.Your answer helped me, thank you.

**Comment by garronej** [comment]
Glad I could help.  

For reference,  resources related to environement variables https://docs.keycloakify.dev/environnement-variables
