### ISSUE TITLE
How to make a custom Account theme ?

### ISSUE THREAD

**Issue by rgdev** [keycloakify/keycloakify#388]
I downloaded the started project (version 4.6.5 and I updated keycloakify to 7.15.5) but I don't understand how to change the account theme.

I've ejected all the pages (account.tpl and password.tpl), edited the styles a little, built with `yarn build-keycloak-theme` and selected the "keycloakify-starter" theme in Keycloak (22.0.1) but I still see the default account theme : 

![image](https://github.com/keycloakify/keycloakify/assets/2675421/89fc80a2-3da8-41a3-8178-96079e84f0fc)

I also tried to "update" the local theme with `npx download-builtin-keycloak-theme` but no difference

**Comment by rgdev** [comment]
The page for Account and Password also looks completely different from what Keycloak has : 
![image](https://github.com/keycloakify/keycloakify/assets/2675421/477d5902-9b0a-4a88-bfc9-e11da0e79df2)

**Comment by garronej** [comment]
My sincere apologies,

Regrettably, I'm unable to support the Account theme in Keycloak 22. The original Account theme v1 has been phased out by Keycloak, and the current methods of implementing account and login themes have diverged significantly. 

I've reached out to the Keycloak development team in an effort to identify a possible resolution. However, I must candidly admit that a prompt solution might not be immediately forthcoming.

Here are the alternative courses of action you may wish to consider:

1. Develop a custom account theme in line with Keycloak's established method. The language employed is TypeScript/React which could be a silver lining for some. However, you would need to navigate the building and bundling process independently. Please refer to the following resource for more information: [Keycloak's Official Repository](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/keycloak.v2/account).

2. Continue using Keycloak 21 while I work on devising a viable solution.

In hindsight, I regret not having foreseen this situation and deeply apologize for any inconvenience this may cause. I appreciate your understanding and patience in this matter.

**Comment by garronej** [comment]
follow up here: https://github.com/keycloakify/keycloakify/issues/389

**Comment by garronej** [comment]
https://docs.keycloakify.dev/account-theme
