### ISSUE TITLE
Account theme not available in Keycloak

### ISSUE THREAD

**Issue by raubel** [keycloakify/keycloakify#389]
I'm trying keycloakify with keycloak 22.0.0.

I'm able to have a customized login screen and keycloakify does the job. Looks great.
However, I'm not able to have a customized account theme.

I'm using the keycloakify-starter project. It produces a jar file containing the login and account themes.
But in Keycloak Realm Settings, the `keycloakify-starter` and `keycloakify-starter-variant-1` themes are missing from the account dropdown (there are present in the login dropdown). See screenshots.

![CopyQ HgXfSu](https://github.com/keycloakify/keycloakify/assets/54514/d6f20443-8db6-4671-9de1-e46a5b893edb)
![CopyQ rucMDK](https://github.com/keycloakify/keycloakify/assets/54514/d010ac51-21e2-438d-ac8f-b6fa868c20db)

My understanding is that they are missing because the parent theme (`keycloak`) is itself missing.
Keycloak produces the logs below:
```
aim_keycloak | 2023-08-01 14:25:52,338 WARN  [org.keycloak.theme.DefaultThemeManager] (executor-thread-10) Not found parent theme 'keycloak' of theme 'keycloakify-starter'. Unable to load ACCOUNT theme 'keycloakify-starter' due to this.
aim_keycloak | 2023-08-01 14:25:52,338 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-10) Failed to find ACCOUNT theme keycloakify-starter, using built-in themes
aim_keycloak | 2023-08-01 14:25:52,339 WARN  [org.keycloak.theme.DefaultThemeManager] (executor-thread-10) Not found parent theme 'keycloak' of theme 'keycloakify-starter-variant-1'. Unable to load ACCOUNT theme 'keycloakify-starter-variant-1' due to this.
aim_keycloak | 2023-08-01 14:25:52,339 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-10) Failed to find ACCOUNT theme keycloakify-starter-variant-1, using built-in themes
```

**Comment by rgdev** [comment]
@raubel update keycloakify to 7.15.5 in your package.json

**Comment by raubel** [comment]
Indeed, with keycloakify 7.15.5, the keycloak-starter theme appears in the dropdown, but the theme is not applied when I select it. The account console still looks like the keycloak theme.

With Keycloak 21.0.0, the theme appears and is correctly applied.

Maybe I did something wrong, I'll try again tomorow.

**Comment by garronej** [comment]
Got it, Sorry about that guys.  

Though I fixed it with [this](https://github.com/keycloakify/keycloakify/commit/4140ca6fbd678e0bca0a8dc3b32be83b9b57fada) but I didn't test it.  
As soon as I saw the theme appear in the dropdown I just assumed it was working.  

Anyway I'll fix it ASAP

**Comment by garronej** [comment]
`7.15.6-rc.0`  is being released.  
You can try it out.  
I have to investigate precisely what's going on but in the meantime I made the account theme extends the base theme.  
Let me know if it work.  
I think it will work for `account.ftl` and `password.ftl` but all the other pages will look totally unstyled.

**Comment by garronej** [comment]
My sincere apologies,

Regrettably, I'm unable to support the Account theme in Keycloak 22. The original Account theme v1 has been phased out by Keycloak, and the current methods of implementing account and login themes have diverged significantly. 

I've reached out to the Keycloak development team in an effort to identify a possible resolution. However, I must candidly admit that a prompt solution might not be immediately forthcoming.

Here are the alternative courses of action you may wish to consider:

1. Develop a custom account theme in line with Keycloak's established method. The language employed is TypeScript/React which could be a silver lining for some. However, you would need to navigate the building and bundling process independently. Please refer to the following resource for more information: [Keycloak's Official Repository](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/keycloak.v2/account).

2. Continue using Keycloak 21 while I work on devising a viable solution.

In hindsight, I regret not having foreseen this situation and deeply apologize for any inconvenience this may cause. I appreciate your understanding and patience in this matter.

**Comment by raubel** [comment]
Thank you @garronej for the explanation. I really hope you'll find a sustainable solution.
For now, I'll stick with Keycloak 21.0.0.

**Comment by garronej** [comment]
Going to have an helping hand from a Java/Keycloak guru. He's sugesting there might be a quick solution. I'll keep you updated.

**Comment by garronej** [comment]
Thanks to @xgp, things are looking good!  
https://groups.google.com/g/keycloak-dev/c/j0aEZTWh-Lw

**Comment by xgp** [comment]
Issue: https://github.com/keycloak/keycloak/issues/22318
Draft PR: https://github.com/keycloak/keycloak/pull/22317

**Comment by garronej** [comment]
For reference: https://github.com/xgp/keycloak-account-v1/issues/3#issuecomment-1671243204

**Comment by Gayathri2102** [comment]
The custom account theme is no longer available in 22.0.3 as well. Is there a fix in the next versions?

**Comment by garronej** [comment]
Yes, there will be a fix soon

**Comment by masterbater** [comment]
> Yes, there will be a fix soon

nice

**Comment by inomn** [comment]
Hi! Any updates on this?
Thanks.

**Comment by garronej** [comment]
@inomn Still on top of my mind but I'm currently like two week late on shiping a very important feature our main project.  
This is why I aven't got time to work on this yet but this is definately not "abandonned" it will lend as soon as I manage to get back on schedule.  

Sorry for the delay on this.

**Comment by xgp** [comment]
Also @inomn the required changes to Keycloak have been merged to Keycloak `main` but they haven't made it into a release yet.

**Comment by inomn** [comment]
@xgp @garronej thanks for the update!

**Comment by Ali-Khlifi** [comment]
Is there news about the bug coorection for keycloakify support keycloak 22.0.3 ? Thanks guys :)

**Comment by garronej** [comment]
@Ali-Khlifi, I think I'll be able to make some time to work on this this week end but, anyway, there was no new Keycloak release since the patch of @xgp has been merged so there is this constraint of anteriority.  

And just to make it clear for everyone. The login themes work fine on Keycloak 22, it's only the Account themes that does not work at the moment.

**Comment by Ali-Khlifi** [comment]
@garronej, Thank you so much for your prompt response. I am looking forward to implementing your solution !

**Comment by xgp** [comment]
FYI the patch to Keycloak https://github.com/keycloak/keycloak/issues/22318 was released in `v23.0.0` today https://www.keycloak.org/2023/11/keycloak-2300-released.html

**Comment by garronej** [comment]
@xgp Thanks for the update!  
Well it means that Keycloak 22 and Account theme is not happening, pepole will have to update to Keycloak 23.  

@xgp I'll do my experimentation and I let you know if everything work as expected.

**Comment by garronej** [comment]
# Let's GO!

Keycloakify v9 has just been released!  
This version introduces account theme support for Keycloak 23 and upwards (sadly, Keycloak 22 is a lost battle). 

What's more, the themes remain retrocompatible with older versions of Keycloak, simply select `_retrocompat` in the dropdown when selecting your theme if you are on Keycloak 21 or prior.

A huge shout-out to @xgp, this absolute legend, who made this possible by submitting [a PR](https://github.com/keycloak/keycloak/pull/22317) to Keycloak and successfully getting it merged!

For more details, check out the migration guide: [Keycloakify v8 to v9](https://docs.keycloakify.dev/migration-guides/v8-greater-than-v9)

**Comment by garronej** [comment]
@all-contributors please add @xgp for code
