### ISSUE TITLE
 Is "login-x509-info.ftl" not supported? 

### ISSUE THREAD

**Issue by wangchengxin** [keycloakify/keycloakify#390]
hi, team, when I created the theme, I found that I couldn't find pageId:login-x509-info.ftl, is there an alternative solution at the moment, or does not support this page? thank you!

**Comment by garronej** [comment]
Hello @wangchengxin,

Keycloakify supports all pages, although we currently don't provide a default component for every single one. The "extra page" feature is there to bridge this gap, accommodating the fact that not all pages are included in our library of default components.

In the starter, you'll find my-extra-page-1.ftl. This can be replaced with login-x509-info.ftl. You can download the default theme using npx download-builtin-keycloak-theme and convert the .ftl template into React (ChatGPT can assist you in this process).

Further information is available in our documentation:

KeycloakifyDocumentationhttps://docs.keycloakify.dev/limitations#some-pages-still-have-the-default-theme.-why

The documentation outlines the process, and we encourage you to submit a PR if you can. There are only a few additional steps required to extend the support of an extra page from your project to Keycloakify, making it accessible for the comunity.

I hope this information is helpful. Please don't hesitate to reach out if you have any further questions.
