### ISSUE TITLE
Any localization other than English does not work

### ISSUE THREAD

**Issue by evgeny946** [keycloakify/keycloakify#392]
Hello! You need replace `defaultValue` to `value` to enable translation to other languages.

https://github.com/keycloakify/keycloakify/blob/e7afb88f22f3ba1f320e9b1ce00971cec4999407/src/login/pages/LoginUpdatePassword.tsx#L126

**Comment by garronej** [comment]
Thank you for reporting!  
A new version is being deplyed.
