### ISSUE TITLE
How to add terms and conditions?

### ISSUE THREAD

**Issue by Cherrywoood** [keycloakify/keycloakify#393]
Hello, I followed the guide in the documentation and checked the keycloak action as required. I used keycloak-starter project. But in the registration form there is no button with the terms and conditions. What am I doing wrong?

![image](https://github.com/keycloakify/keycloakify/assets/58643112/edf48491-718a-4862-9762-832b7d98d0fc)

**Comment by garronej** [comment]
It's notmal.  
The terms are not shown on the `register-user-profile.ftl` page but later on in the flow.  
It's when the user first try to connect that terms are shown to him and get to accept or refuse.

**Comment by Cherrywoood** [comment]
yes, thanks
