### ISSUE TITLE
Make TemplateProps and PageProps more versatile

### ISSUE THREAD

**Issue by ddubrava** [keycloakify/keycloakify#402]
Hi! What do you think about making the `TemplateProps` and `PageProps` interfaces less hardcoded by making `TemplateProps['headerNode']`, `TemplateProps['doUseDefaultCss']`, and `PageProps['doUseDefaultCss']` optional? If you develop a completely custom Keycloak theme, these properties might not make much sense. The template is a completely custom layout, and it's possible that it doesn't need a `headerNode`. The same applies to `doUseDefaultCss` – you don't necessarily need to configure them from components; you can pass undefined to `usePrepareTemplate`, and that's it.

https://github.com/keycloakify/keycloakify/blob/3e155d8e80fa4cac2beff1eec721d4863712c58f/src/login/TemplateProps.ts#L8

https://github.com/keycloakify/keycloakify/blob/3e155d8e80fa4cac2beff1eec721d4863712c58f/src/login/TemplateProps.ts#L16

https://github.com/keycloakify/keycloakify/blob/3e155d8e80fa4cac2beff1eec721d4863712c58f/src/account/pages/PageProps.ts#L9

**Comment by garronej** [comment]
Sorry this slipped through. I'm open to the idea!

**Comment by garronej** [comment]
Closing for now to keep track of the most active issues but I'll think about it if I refactor the props which I'll probably to to make it easyer to overload specific components.
