### ISSUE TITLE
Does keycloakify allow apps to use their own custom context providers?

### ISSUE THREAD

**Issue by abhilashlr7** [keycloakify/keycloakify#408]
We have a scenario where we would like to unify our product UI (components) and Keycloak theme's UI elements. For instance buttons, input boxes, etc. It is a duplicated effort for us to write the styles in 2 different places, hence we were thinking of using Keycloakify being a react based implementation. Our UI components heavily rely on `styled-components` and `antd` and therefore it requires a `ConfigProvider` wrapper set up. 
I tried setting this up and running the app locally with storybook, things are fine. But while doing a `yarn start` by running the app locally or by building the theme and then using that theme in our local keycloak instance, it fails to run.

The following is what I see on browser console:
```ts
Uncaught TypeError: dispatcher is null
```

Anyone who has implemented it or can someone help what could I be doing wrong? Right now, this `ConfigProvider` I've tried adding it on the root `index.tsx` file, then into `keycloak-theme/login/KcApp.tsx` and also tried it inside `pages/Login.tsx`. Neither setup worked :(.
Any help is much appreciated!

**Comment by garronej** [comment]
Hi,  
I think the problem you are describing is not related with keycloakify.  
You would get the same error in a fresh create-react-app project.  
I can have a look though if you provide the reproduction repo. I should be able to tell you what's wrong quicky.

**Comment by abhilashlr7** [comment]
Sure let me do that.

**Comment by abhilashlr7** [comment]
> Hi, I think the problem you are describing is not related with keycloakify. You would get the same error in a fresh create-react-app project. I can have a look though if you provide the reproduction repo. I should be able to tell you what's wrong quicky.

Apparently, it was a React and react-dom issue since I had the UI repo symlinked. Cleared it out now. Thanks. I will close this Issue.
