### ISSUE TITLE
Invalid reference exception messagesPerField  [in template "error.ftl" at line 82, column 30]

### ISSUE THREAD

**Issue by hookenful** [keycloakify/keycloakify#409]
Hello. We are using Keycloakify v5.9.3 and started getting this message. Can u help somehow?

![image](https://github.com/keycloakify/keycloakify/assets/31849464/35da1bac-473d-4958-9d6a-f800b90cba85)

**Comment by garronej** [comment]
Hello,  
It's something that have been fixed in later relases of Keycloakify
