### ISSUE TITLE
Reset password and verify email urls missing in keycloakify starter

### ISSUE THREAD

**Issue by koo27** [keycloakify/keycloakify#413]
I added two pages in keycloakify starter: login-reset-password and login-verify-email
In the first one I don't see any url where to submit the form to actually send the reset password email.
in the kcContext I only see this
```
type LoginResetPassword = Common & {
        pageId: "login-reset-password.ftl";
        realm: {
            loginWithEmailAllowed: boolean;
        };
        url: {
            loginResetCredentialsUrl: string;
        };
    };
```
but the logintResetCredentialsUrl is for showing the reset form

In the same way it would be useful to have the url to send the email to verify the registration after the registration has done (in the verify-email page) in order to say to the user to click to receive the email again if didn't receive it yet.

**Comment by garronej** [comment]
Hi @koo27,  

The types definition are just here to provide a better devlopper experience, to give you an idea of what's supposed to be on the `kcContext` depending on the page you're on.  
However it's Keycloak, not Keycloakify that decides what's available. Keycloakify just forward the all context to the frond blindely.  
If you want to actually see what's there you can `console.log(window.kcContext)` in your browser console.  
If you figure out that one of our type definition is lying or if there are some properties that aren't present in the type definition, please, PR are wellcomes :)

**Comment by garronej** [comment]
Looks like it's `kcContext.urls.loginActions` you are looking for isn't it?  https://github.com/keycloakify/keycloakify/blob/15aa114579c891d90900e9da28792c0d2bf53b59/src/login/pages/LoginResetPassword.tsx#L26

**Comment by koo27** [comment]
I already tried that one, but it seems to be the url for loggin in, isn't it?
Shouldn't it be different to ask for a password reset?

**Comment by koo27** [comment]
I tried again and it seems to work with this url. It sends the email and then redirects the user to the login page. I think the same happends with the update password page.
So I close this issue, thank you again
