### ISSUE TITLE
Chunks are loaded from /static

### ISSUE THREAD

**Issue by AlexandrValerevich** [keycloakify/keycloakify#416]
If I build the same code several times one .jar file work well and use /resources/{id}/static/... path for fetching recourses (expected behavior) and sometime it change path to static/... and get failed.

I have no idea about it and can't event assume how this path are generated.

keycloakify@8.0.0
keycloak 21.1.1

**Comment by garronej** [comment]
Hi @AlexandrValerevich,  
Sorry about that, can you produce the reproduction steps, screen shots and the jar file so i can investigate ?

**Comment by garronej** [comment]
Are you using create react app or a different build system ?

**Comment by filipzava** [comment]
Hi @AlexandrValerevich, 
did you manage this ? I am facing the same issue ... 🙏

**Comment by garronej** [comment]
What do you mean by "sometimes?" some resources are dowloaded from `/resources/{id}/static/...` and others from `static/... `?

**Comment by garronej** [comment]
Ok thank you for the clarification.  
If you submit a pr to the v7 branch I can relase another version but I don't have the time to patch older version myself.
