### ISSUE TITLE
Can I know origin url ? 

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#443]
Hi there.

I got my app hosted on a certain domain, when opening that page, automatically i'm redirected to the keycloak login page customized with my keycloakify theme.
Is it possible from the keycloak login page know from where is it been open ?

Example:

- http://app1 is my application
- http://keycloak is my keycloak instance

Navigating to http://app1 if not already logged in i'm redirected to http://keycloak.

Can i know from KcContext that the page invoking keycloak is http://app1 ?

My goal would be render different customization of a single theme depending on the origin url.

Thank you in advance .

**Comment by PietroFalcetti** [comment]
Hello @garronej,

Thank you for your response.
In my case we are forced to use one single client so the idea of define multi of them is not acceptable. Also how could you initialize the keycloak instance with different clients ? 


The second approach you provided seems better for our use-case, but I see that it's implemented with the library "oidc-spa" instead of "keycloak-js". Can i reach my goal without migrating to the new library ? Also why did you migrate from keycloak-js to oidc-spa ? What are the advantages ? 

Thank you again,

Pietro

**Comment by PietroFalcetti** [comment]
thank you for you response.

The approach of having multiple client within a realm Is ok, but I'm not having multiple applications.
I have one single application that invoke the KeycloakJS method init.
The same application has to display different login pages based on the url the user come from. But in the end it is always the same application with the same code. So the KEycloakJS method init is called with one default clientId, I cannot change it dynamically. That's why I need to access to the origin from the keycloakify theme.

**Comment by garronej** [comment]
> So the KEycloakJS method init is called with one default clientId, I cannot change it dynamically.  

You can have multiple oidc instance within the same web application. `oidc-spa` supports it ouf of the box.  
In [Onyxia](https://onyxia.sh) for example there are many oidc instances that coexist in the web app, each initialized with different client id.  
We have one clientId to connect to S3, one for Vault, one for Kuberneter and one for the App rest API.  

There's no problem implementing the approach that consist in passing the param via the URL. I'm saying that just so you know.

**Comment by PietroFalcetti** [comment]
Hello @garronej,
I've been able to set up the param as suggested by you, thank you.


I got a second scenario actually, we developed the theme for Keycloak with keycloakify, a client is integrating with keycloak through a Java application and rendering our theme.
is it possible, you know how to, via Java application to pass a parameter like we did in a react application ?

**Comment by garronej** [comment]
@PietroFalcetti I highly encourage you to get a paid suscription to ChatGPT. Me and my team are working with this on the daily.  

https://chat.openai.com/share/ec8cffec-b5b0-4f42-8618-34c7d39636d8

**Comment by PietroFalcetti** [comment]
Thank for the tips! 
I use to use chat GPT, but for this topic I preferred to ask you before.

So thank you again! 

Marking the Issue as closed as you solved my problem!

**Comment by garronej** [comment]
cheer!
