### ISSUE TITLE
"extraPages" property in "keycloakify" in package.json is not working

### ISSUE THREAD

**Issue by PrzemyslawPolrolniczak** [keycloakify/keycloakify#445]
I've did exactly the same steps as stated there: https://docs.keycloakify.dev/build-options#extrapages

I've checked the starter repo (https://github.com/keycloakify/keycloakify-starter) which has `my-extra-page-1.ftl` and `my-extra-page-2.ftl` added and I saw, that it's not using `extraPages` property in `package.json`.

However I've found that old demo project (https://github.com/garronej/keycloakify-demo-app/tree/look_and_feel) is using it, so it makes me wonder if that option is deprecated?

Am I missing something?

here's keycloakify part in my  `package.json` file:
``` 
...
 "keycloakify": {
    "extraPages": [
      "set-currency-action.ftl"
    ],
    "extraThemeProperties": [
      "parent=keycloak",
    ]
  },
...
```

**Comment by garronej** [comment]
Hey @PrzemyslawPolrolniczak,  

Good catch!  
I should remove this from the doc.  
It's no longer required to declare the extra pages in the package.json.  
Keycloakify is smart enough to figure this on it's own.

**Comment by PrzemyslawPolrolniczak** [comment]
But is there a way to explicitly tell keycloakify to create an additional page? I'm using quite custom setup with Vite, so automatic page creation might not work on my machine

**Comment by garronej** [comment]
No there's not but as long as your project respect one of the supported dirrectory structure:  

<img width="320" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/2b7f227b-300e-419a-98cb-80484e2cec34">

And you have a `kcContext.ts` file somewhere with `pageId: "my-page.ftl"` 

![image](https://github.com/keycloakify/keycloakify/assets/6702424/207a15ba-f82a-4e1f-8c61-6839fb55d085)

It will work.  

This is the relevent code:  

https://github.com/keycloakify/keycloakify/blob/main/src/bin/keycloakify/generateTheme/readExtraPageNames.ts
