### ISSUE TITLE
[Language Support] Update password process not translated

### ISSUE THREAD

**Issue by nabil-aitbaha** [keycloakify/keycloakify#450]
Hello,

I try to create a keycloak theme in Norvegian. I have a translate issue in the update password that is not translated.

I have force the translation by adding a file messages_no.properties in /build_keycloak/src/main/resources/theme/<theme_name>/login/messages.

I have try to do same that is describe in documentation but not works for me.

I have force the translation but some fields are not translated yet.

<img width="410" alt="screenshot" src="https://github.com/keycloakify/keycloakify/assets/26165516/682ab2d7-b200-49f9-a9ad-dceafa2f79d9">

Find below the content of message_no.properties 
```
confirmExecutionOfActions=Utf\u00F8r f\u00F8lgende handlinger
proceedWithAction=&raquo;Klikk her for \u00E5 fortsette
requiredAction.UPDATE_PASSWORD=Oppdater passord
updatePasswordTitle=Oppdater passord
```

**Comment by garronej** [comment]
Sorry this slipped through, fixed in keycloakify 10
