### ISSUE TITLE
Refused to execute script from 'https://{host}/static/js/451.45207923.chunk.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by AliaksandrKazerski** [keycloakify/keycloakify#453]
Hi. First of all, thank you for your package and effort.
**Description:** 
The paths to the chunks in the main chunk are not resolved correctly.
**Expected:** https://{host}/resources/{some-number}/login/{theme-name}/build/static/js/451.45207923.chunk.js
**Actual result:** https://{host}/static/js/451.45207923.chunk.js
**How to reproduce:** 
Reproduced after updating dependencies in my project (npm install)
After returning to the previous dependencies, the problem disappeared.
One of my guesses is that the issue may be somewhere in this function replaceImportsFromStaticInJsCode after webpack build the chunks.
"dependencies": {
    "@mui/material": "^5.12.3",
    "@reduxjs/toolkit": "^1.9.5",
    "axios": "^1.4.0",
    "classnames": "^2.3.2",
    "keycloakify": "^7.11.6",
    "notistack": "^3.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.43.9",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.11.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@craco/craco": "^7.1.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/grecaptcha": "^3.0.4",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.25",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.1",
    "@types/react-slick": "^0.23.10",
    "@types/redux-mock-store": "^1.0.3",
    "autoprefixer": "^9.0.0",
    "husky": "^8.0.3",
    "react-scripts": "^5.0.1",
    "redux-mock-store": "^1.5.4",
    "regenerator-runtime": "^0.14.0",
    "sass": "^1.62.1",
    "sass-alias": "^2.0.1",
    "ts-jest": "^29.1.0",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },

**Comment by garronej** [comment]
Hi @AliaksandrKazerski,  

> Hi. First of all, thank you for your package and effort.

Thanks!

I'll need a reproduction repo with reproduction step to assist you.  
I also encourage you tu use the latest version of Keycloakify. I don't really have the bandwith to publish fixes for older version.

**Comment by AliaksandrKazerski** [comment]
Update to the latest version resolved my issue. Thanks.

**Comment by garronej** [comment]
Geat thanks for the feedback!
