### ISSUE TITLE
After jar file build, login theme ui changes no reflected

### ISSUE THREAD

**Issue by lavanya15142** [keycloakify/keycloakify#454]
build options using build jar file successfully. But my login theme css changes are not reflect. Only build default theme.

**Comment by garronej** [comment]
Hello @lavanya15142,  

Try loading the default jar that comes with the starter project see if you see it appear in the dropdown.  

https://github.com/keycloakify/keycloakify-starter/releases/download/v4.9.0/keycloak-theme.jar
