### ISSUE TITLE
Pages using Template from import instead of PageProps

### ISSUE THREAD

**Issue by BlackVoid** [keycloakify/keycloakify#459]
The following pages are importing "Template" using a relative import instead of using Template from PageProps:

- src/login/pages/LoginDeviceVerifyUserCode.tsx
- src/login/pages/LoginOauthGrant.tsx

This means that these pages needs to be copied to any project which customizes the Template, even though no other modifications are done on the pages.

**Comment by garronej** [comment]
Hey @BlackVoid, good catch!
