### ISSUE TITLE
After build, can not find the custom theme in theme list

### ISSUE THREAD

**Issue by huanlaivan** [keycloakify/keycloakify#468]
After run ```yarn build-keycloak-theme``` I go to the ```build_keycloak``` folder and run file ```start_keycloak_testing_container.sh``` to test it but when I go to the theme config in realm I can't find my theme.
![image](https://github.com/keycloakify/keycloakify/assets/79571066/dc946a25-0693-423b-8797-72527cef97ae)

**Comment by garronej** [comment]
Hi @huanlaivan,  

I just tried to make sure with the latest version of the starter. Works as expected  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/misc/Screen%20Recording%202023-12-06%20at%2006.17.41.mov  

Can you give me some more insight on what you are dogin?

**Comment by huanlaivan** [comment]
Hi @garronej, My custom theme not working so I try to run ```keycloakify-starter``` repo to test new version but it's still now work. I recorded my steps and attached it below
[keycloak-issue.webm](https://github.com/keycloakify/keycloakify/assets/79571066/56638180-de58-41ca-b813-8304b74ed4a1)

**Comment by garronej** [comment]
@huanlaivan thanks for the aditional info but the video is corrupted.  I can't read it past a few second.  

What I can already see is that you are using cygwin.  
I can try to make it work with cygwin but this environement will never be officially supporter.  
I used it for years, it's usefull but it's a reard in between windows and unix environement.  

Please try to upload the video again. In the meantime you can use WSL to build you theme.

**Comment by huanlaivan** [comment]
Hi @garronej, thank you for support me. I don't know why it not work on my window pc. When I try use my mac and linux (WSL) it worked. Maybe something is corrupted with my window pc.

**Comment by garronej** [comment]
Keycloakify 10 is now fully cross platform
