### ISSUE TITLE
Where can i get and customize the theme of the rest of the account pages

### ISSUE THREAD

**Issue by johnifemezuo** [keycloakify/keycloakify#469]
I downloaded the Keycloakify starter project (version 9.1.4 and updated its dependencies). The project came with account and login folder which has the code and implementations for account and login pages to customize and it works fine. 

Now i wish to customize the rest of the pages on the account page. Pages like the session,  authenticator, applications, device activity and more. I can`t seem to find these pages on the keycloakify project or how to build or implement these page on the docs.

![image](https://github.com/keycloakify/keycloakify/assets/49494778/d4baafd1-250e-48f5-babc-45f5766e49f3)

I can create a new page using react on the project but i need the implementation that works with the above mentioned pages.

Please if i can get a quick response to this i will really  appreciate. thanks.

**Comment by garronej** [comment]
Hello @johnifemezuo,  

Don't worry, you can implement the missing pages. Just follow the instruction here: https://docs.keycloakify.dev/limitations  

Hopes it helps,

**Comment by johnifemezuo** [comment]
Thanks for the quick reply @garronej i will check it out and reply back on my progress.

**Comment by johnifemezuo** [comment]
@garronej after reading the docs. it recommended this code to run `npx -p keycloakify download-builtin-keycloak-theme` to install all the other implemented page i need but  they are in  ftl. any recommendation on how to convert these ftl pages to react.

**Comment by garronej** [comment]
Hello @johnifemezuo,

I encourage you to read the doc carefully again.  
The commend you are referring to is for copy pasting pages that have already be converted to React in your project.  
You are not in this cases. The pages you need aren't implemented yet.  
Read carfully, you'll find all the information you need to implement them. It's not hard. Just a bit boring

**Comment by brueckner** [comment]
Hey @garronej , thanks for your work on this so far! The dev setup is really nice to use.

However, I am struggeling with the same issue as the OP (disclaimer: not too familiar with react unfortunately).

You mentioned the instructions on the [Limitations page](https://docs.keycloakify.dev/limitations) in the docs and I've seen the [section about self-implementation](https://docs.keycloakify.dev/limitations#i-have-established-that-a-page-that-i-need-isnt-supported-out-of-the-box-by-keycloakify-now-what). It's still unclear to me how to move forward at this point.

As far as I understand, we need to basically convert existing `.ftl` files, for example the `totp.ftl` to a proper react component, along the lines of the provided example page `MyExtraPage1.tsx`. In case of the [Authenticator page (totp.tpl)](https://github.com/keycloak/keycloak/blob/99774b3f7a776476e7f04e472e13e3915971a6fb/themes/src/main/resources/theme/base/account/totp.ftl), I am unclear about how to access the data required for the page. Could you maybe roughly outline how this is supposed to work?

Or... is there a simpler way of using a fallback or something, if the exact styling doesn't matter too much?

Better yet, are these pages going to be implemented any time soon?

**Comment by garronej** [comment]
Hey @brueckner,  
You've grasped the key ideas!  
The data are automatically available on the windows.kcContext.  
You just need to extends the typings if you want type safety.  
In the doc I give a PR as an example that adds support for a page. You can use this as a reference to help you move forward with this.  
You can also try GPT4 for converting ftl into react if you provide enough context.
