### ISSUE TITLE
Recaptcha doesn't work

### ISSUE THREAD

**Issue by D-Simona-G** [keycloakify/keycloakify#470]
Recaptcha doesn't work with the custom Keycloakify theme I made, despite the property "recaptchaRequired" being true & "recaptchaSiteKey" having the appropriate value (using Google Recaptcha). The html element itself appears in the DOM, but for some reason it's not "populated" as expected.

![Screenshot 2023-12-12 001121](https://github.com/keycloakify/keycloakify/assets/120456967/3f65816b-3e64-4bf5-aefd-1964a5494964)

If for the same client, I swap the Keycloakify theme to a keycloak built-in one, it works completely fine. I have used the starter project (latest Keycloakify version) to build a Keycloak standalone theme, not an app, thus not sure if that has anything to do with it, although it shouldn't pose any problem.

I'd really appreciate any pointer/idea on how to solve this/why this might be happening. TIA.

**Comment by garronej** [comment]
Hello @D-Simona-G,  

If you try with [the theme of the starter](https://github.com/keycloakify/keycloakify-starter/releases/download/v5.0.5/retrocompat-keycloak-theme.jar) does it work?

**Comment by D-Simona-G** [comment]
thanks for your prompt reply! 

I did try both with your suggestion and with a freshly built one from the keycloakify-starter repo (without any of my modifications). And it doesn't work, it's the same situation that I showed in my above screenshot.

**Comment by garronej** [comment]
Well then I guess it means that there's a bug in this page.  

I didn't implement it myself.  

I encourage you to copy over the page to your project and try fixing it, it's usually quite simple since the base Keycloak page are very basic.   

If you find the bug you are very wellcome to submit a pull request or report your solution here.

**Comment by D-Simona-G** [comment]
Working on it. If I do manage to fix it I will submit a PR, cheers!

**Comment by D-Simona-G** [comment]
Sorry for late reply, been quite busy, but I found and fixed the bug on my end. The problem stems from client-side navigation and component lifecycle which was interfering with the correct loading/rendering of the reCaptcha script. E.g., navigating from the the Login page to Register page would result in the script not rendering, but whilst on Register page, if you'd "hard" refresh the browser or clear cache, it would eventually render. On subsequent refreshes though, it would again not render. 

Initially, I installed a small package called Reaptcha, to test my theory and that solved all the issues. But figured that some people might not even use reCaptcha feature so adding one more dependency wasn't necessarily justified + it was a bit too much for what was needed imo. 
So I ended up using an useEffect hook in the RegisterUserProfile.tsx that manages the reCaptcha script.

If this sounds ok to you, I am happy to create a PR. If so, on which repo should it be?

**Comment by garronej** [comment]
Hey @D-Simona-G,

Thank you for the thorough explanation. Yes, please create the pull request. While I can't guarantee that I'll merge it as-is, I might need to make some adjustments. In any case, it will be a very valuable reference for people encountering the same issue as you.

**Comment by FINDarkside** [comment]
For anyone else stumbling on this, after fiddling with [react-google-recaptcha](https://www.npmjs.com/package/react-google-recaptcha) and some attempts to fix it since it also doesn't handle re-renders properly, I ended just doing this in KcApp.tsx

```ts
const [initialPage] = useState(kcContext.pageId);
useEffect(() => {
  // To fix issues with recaptcha
  if (kcContext.pageId !== initialPage) location.reload();
}, [initialPage]);
```

**Comment by AlexisZankowitch** [comment]
I also had a similar issue on the Register page. Using the fix proposed in the PR solved it. Thank you @D-Simona-G

**Comment by garronej** [comment]
Thanks for reporting @AlexisZankowitch,  
The next release will have this fixed
