### ISSUE TITLE
Missing page title

### ISSUE THREAD

**Issue by BlackVoid** [keycloakify/keycloakify#473]
The title is always "React App" and is never set to anything else, perhaps it would be good to have it in line with the default page titles?

Maybe implement it with something like [this](https://stackoverflow.com/questions/46160461/how-do-you-set-the-document-title-in-react)?
```
import React, { useEffect } from 'react';

function Example() {
  useEffect(() => {
    document.title = 'My Page Title';
  }, []);
}
```

**Comment by garronej** [comment]
Good idea!  

It there fitting page titles in the defaut Keycloak translations?

**Comment by BlackVoid** [comment]
Just had a look and yes, there is a [default translation](https://github.com/keycloak/keycloak/blob/aa75fef6e64ba70f14647251a67ce7c2d2f70a28/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L26C1-L26C1) and a single title that's used [across all pages](https://github.com/keycloak/keycloak/blob/aa75fef6e64ba70f14647251a67ce7c2d2f70a28/themes/src/main/resources/theme/base/login/template.ftl#L15C5-L15C5), so I'll create a PR for that.
