### ISSUE TITLE
Admin theme discussion

### ISSUE THREAD

**Issue by D-Simona-G** [keycloakify/keycloakify#477]
This is not an issue per se, just would really appreciate your input and expertise. I know the Admin theme is not a priority for Keycloakify at the moment.

I need for my project to override some minimal functionality & visual aspect of the Admin pages(specifically for users & groups pages) of my Keycloak v23 server, but seeing the admin-ui is not based on .ftl templates anymore, I am not sure how I would go around doing that in a way that is integrated with the rest of my Keycloakify-based theme. 

Do you have any pointers/ideas on where to start and what approach one would use to achieve it? I'd be really grateful for any pointer/suggestion. TIA!

**Comment by garronej** [comment]
Hello @D-Simona-G,   

First of all, thanks for your PR on recapcha, didn't get the time to review it yet but I will.  
About the admin theme it's a tough problem.  
It's a completely different system. Keycloakify focues on the user facing pages.  
Maybe, if the changes you need are light you could just get by using a custom css and js files that you would include in the head?

**Comment by D-Simona-G** [comment]
Yea, it looks like it's not going to be a straightforward process. 

Thanks for the pointer! Will try it.

Good job with the project, it's appreciated.

**Comment by garronej** [comment]
Hello @D-Simona-G,  

Probalbly way too late for your project but you can now customize the Admin UI witn keycloakify. I'm writing the documentation.
