### ISSUE TITLE
FTL code inside of index.html is finnicky

### ISSUE THREAD

**Issue by ferretwithaberet** [keycloakify/keycloakify#479]
Due to the build process of keycloakify, the `index.html` file is first given to the javascript bundler, then to the FTL template engine. This causes the javascript bundler to fail building due to invalid html, because it tries to threat FTL tags as HTML elements. Considering this `index.html` content:
```ftl
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="icon" href="/favicon.ico" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  
  <#if client.name??>
    <title>${client.name}</title>
  <#else>
    <title>${client.clientId}</title>
  </#if>
</head>

<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
</body>

</html>
```
the bundler will fail to parse `<#if>`, `<#else>` and `</#if>` and error out.

I do not know how this could be fixed, the FTL tags can be used inside of HTML attributes(as the bundler will parse them as strings), but that limits their usefulness.

**Example of using FTL tags inside of an HTML attribute:**
```ftl
<meta name="og:title" content="<#if client.name??>${client.name}<#else>${client.clientId}</#if>" />
```

**Edit:** I am leaving this issue here mostly as some sort of documentation over this behavior for other users of this project. I do not expect it to be an easy fix, nor do I expect it to be done soon. Unless other users deem this as necessary, I do not think this should be threated with high priority.

**Comment by mitchwadair** [comment]
I feel like using FTL tags in your `index.html` is a bit of an anti-pattern in regards to a library like this, where you are moving that conditional logic to a JS framework instead. If you want conditional logic, do it with your React components. In the example you provided:
```ts
// ... page boilerplate

const { client } = kcContext;

if (client.name) {
    document.title = client.name;
} else {
    document.title = client.clientId;
}

// ... rest of component
```

**Comment by garronej** [comment]
@ferretwithaberet  I mean, I see the appeal of wanting to have some things in the html that the server respond.  
But I though about it and I didn't find any way to make it work that isn't hacky.  
If you provide me with ftl, it's not HTML so I have no way the manipulate it the way I need to.  
But realy I think there is only very few usecases where the solution @mitchwadair sugests isn't acceptable.  
If you really need something as soon as possible you can hardcod a <script /> tag in you header that uses the window.kcContext to perform some DOM manipulation like inserting some statement in the head.  
Since SEO is irellevent for an OIDC login page I think it's perfectly acceptable from the point of view of the user experience.

**Comment by ferretwithaberet** [comment]
> I feel like using FTL tags in your `index.html` is a bit of an anti-pattern in regards to a library like this, where you are moving that conditional logic to a JS framework instead. If you want conditional logic, do it with your React components. In the example you provided:
> 
> ```ts
> // ... page boilerplate
> 
> const { client } = kcContext;
> 
> if (client.name) {
>     document.title = client.name;
> } else {
>     document.title = client.clientId;
> }
> 
> // ... rest of component
> ```

Agreed, but that cannot be done with tags that need to be in the source HTML of the page, as web scrapers will not render the page to get the page's metadata.

> @ferretwithaberet I mean, I see the appeal of wanting to have some things in the html that the server respond. But I though about it and I didn't find any way to make it work that isn't hacky. If you provide me with ftl, it's not HTML so I have no way the manipulate it the way I need to. But realy I think there is only very few usecases where the solution @mitchwadair sugests isn't acceptable. If you really need something as soon as possible you can hardcod a <script /> tag in you header that uses the window.kcContext to perform some DOM manipulation like inserting some statement in the head. Since SEO is irellevent for an OIDC login page I think it's perfectly acceptable from the point of view of the user experience.

Also agreed, I have mostly created this issue as a sort of temporary documentation for other users of this library, this shoud however be documented in the official documentation.
Regarding how this could be fixed, a bundler plugin that would ignore part of the index.html, then inject it again in the output could maybe work.
Something like:
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="icon" href="/favicon.ico" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  
  <!-- @bundler_ignore
  <#if client.name??>
    <title>${client.name}</title>
  <#else>
    <title>${client.clientId}</title>
  </#if>
  -->
</head>

<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
</body>

</html>
```
then the commented part could be reinjected after the build step.

Such hacky solutions would be alright in my opinion, as they are opt-in (for example, in this case, by installing a bundler plugin).

To end this response, I want to mention again that I found my solution for my use-case, I do not depend on this issue being fixed. I just wanted to propose possible fixes/mitigations for the aforementioned issue. I will leave this issue open at the moment until this behavior is documented or fixed.

**Comment by garronej** [comment]
Yes agreed!  
I like the sollution with special comments.  

By the way, it's somewhat of a hidden feature but I've implemented something simmilar to enable Keycloakify to ignore some parts of the index.html file.  
It's usefull when you have a single codebase for both your theme and your SPA.  

Example here:  

https://github.com/InseeFrLab/onyxia/blob/4e0d66910aaf259f3eaf62bc0845956f78efd127/web/public/index.html#L79-L81

See keycloakify ignore start and keycloakify ignore end
