### ISSUE TITLE
Question: How to add a redirect uri to register page?

### ISSUE THREAD

**Issue by madroneropaulo** [keycloakify/keycloakify#480]
I'm using this code to get to the registration page
`<Link href={url.registrationUrl}>Create Account</Link>`
It's a regular <a> tag wrapped.
How can I make it so that when the user signs up in that link, it gets redirected to a specific url in my app? 
Thanks in advance!

**Comment by garronej** [comment]
Hello @madroneropaulo,  

I'm not sure I understand the question.  
Can you elaborate?

**Comment by madroneropaulo** [comment]
Sure. Let's use the keycloakify-starter project as an example:
in the Login.tsx page this is how we set the "create account" link
```
<div id="kc-registration">
                        <span>
                            {msg("noAccount")}
                            <a tabIndex={6} href={url.registrationUrl}>
                                {msg("doRegister")}
                            </a>
                        </span>
                    </div>
```
That url takes the user to the register page, but a "plain" register page with no way to control the redirect_uri param after the user registers. I tried just doing this:
```
<div id="kc-registration">
                        <span>
                            {msg("noAccount")}
                            <a tabIndex={6} href={url.registrationUrl + '&redirect_uri=bla'}>
                                {msg("doRegister")}
                            </a>
                        </span>
                    </div>
```
But when the users register they're not taken to that uri specified there.

**Comment by garronej** [comment]
Gotcha,  
I'm afraid that the redirect_uri is a query parameter that can only be set by the client that redirect to the login page.  
It most likely can't be overwriten during the login/register cinematic.  

With [oidc-spa](https://docs.oidc-spa.dev/) you would do something like:  

```tsx
        // Replace the href without reloading the page.
        // This is a way to make oidc-spa know where to redirect the user
        // if the authentication process is successful.
        history.pushState({}, "", "https://your-post-login-url.com&some_arg=foo");

        await oidc.login({ doesCurrentHrefRequiresAuth: true });
```  

You also have to make sur that you have allowed `https://your-post-login-url.com*` as post login redirect.  

But I guess it most likely doesn't match your usecase. You probably want to add some info about what has been going on during the login procces back to your client.  

I think the only approach that the OIDC protocoll allow here is to have custom user profile attribute that you would include in the idToken.  
Like is done with `favourite pet` in the project starter. See: https://docs.keycloakify.dev/realtime-input-validation#getting-your-custom-user-attribute-to-be-included-in-the-jwt
