### ISSUE TITLE
New public/keycloak-resources/login/resources/img files are not added to docker container resources path

### ISSUE THREAD

**Issue by jithkaringada-corp** [keycloakify/keycloakify#484]
New public/keycloak-resources/login/resources/img files are not added to docker container resources path
I added a logo image to the Template.tsx and added the png file in the public/keycloak-resources/login/resources/img directory.
If I use storybook or yarn start, I can see my image/logo render, but when I build the theme and add it to my keycloak instance, the logo does not render because it cannot find the image. I did an exec shell into the docker container and I can see all the older image files but not the logo image file I added.

**Comment by garronej** [comment]
Hello @jithkaringada-corp,  

`/keycloak-resources/login/resources/img` is only for making available the resources that are available in Keycloak in Storybook.  
If you want to use custom resources, just import them as you would if you where working on a regular React app:  

Put, for example your image in `src/login/assets/my-image.png`  

And import it like:  

`src/login/Template.tsx`
```tsx
import myImagePngUrl from "./assets/my-image.png";

<img src={myImagePngUrl} />
```

**Comment by jithkaringada-corp** [comment]
I tried what you had suggested and it still does not find the image when I build the keycloak theme using 
yarn build-keycloak-theme and start a docker container using ./build_keycloak/start_keycloak_testing_container.sh. I followed the instructions after running yarn build-keycloak-theme. I get a 404 NOT FOUND on the resource according to the Web Developer Tools -> Network (http://localhost:8080/resources/9yodt/login/custom-theme/img/logo_small.png). After placing it in the assets directory exactly as you had specified, is the path from the Network tab expected? I tried to docker shell again and don't see the logo_small.png in the /opt/keycloak/themes/custom-theme/login/resources/img. Is this where the asset resource expected to land? It all works well when I run 'yarn start' or storybook.

**Comment by garronej** [comment]
Hi @jithkaringada-corp,  
Without seeing your repo I can't tell you precisely what's going wrong.  
Nevertheless, I updated the starter project to include an example:  
Here is the commit: https://github.com/keycloakify/keycloakify-starter/commit/c3e706746ac2b347d85bcae72bdfa394ccb6d1b0  

You can see it live by navigating to the deployment of th starter project https://starter.keycloakify.dev and clicking on login.  

<img width="1482" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/6b6453d9-be4f-416d-ad08-53cd879e894c">  

I hope it helps!

**Comment by garronej** [comment]
Maybe just try `rm -rf build_keycloak && yarn build-keycloak-theme`

**Comment by jithkaringada-corp** [comment]
This worked great - all I needed to do was your last comment
rm -rf build_keycloak && yarn build-keycloak-theme
I should have attempted that before, but your screenshot of the resource path it was using gave me confidence that would work. Thank you. I do have another question now but I will post it as another issue.

**Comment by garronej** [comment]
Great to hear that the problem is solved!  
Cache is very hard to manage, on the one hand I would like to prevent problems like this by making Keycloakify perform a clean build each time but having cache significantly improve incremental builds and many users works like this.  
It's hard to know when the cache should be invalidated.
