### ISSUE TITLE
When I use keycloak theme as a standalone, all the resources of the theme cannot be found

### ISSUE THREAD

**Issue by jithkaringada-corp** [keycloakify/keycloakify#486]
I followed the instructions in the https://docs.keycloakify.dev/ videos. However, the videos do not capture how to ONLY get the theme uploaded to a keycloak instance. I want the theme to be standalone because I have my own NextJS/React app. I followed instructions in https://github.com/keycloakify/keycloakify-starter, particularly the "I only want a Keycloak theme" section. After following those instructions I ran [yarn build-keycloak-theme]. I made sure to get the resulting jar file into the /opt/keycloak/providers path and did a /opt/keycloak/bin/kc.sh build (following the video again). Are there clearer instructions for getting from keycloak-starter (that has the React SPA + keycloak theme) to just the keycloak theme that we copy over to the docker container?

Also what URL do I use to get directly to the login page of the keycloak instance for the realm I set the login page for (probably a question for the keycloak community, but figured you would know) so that I can have an href from my React App directly to that sign in page?

**Comment by jithkaringada-corp** [comment]
Closing this issue. The instructions did work, I just had the wrong base path URL, and the redirect was appending a path that was wrong, so it was a Keycloak specific issue.

**Comment by garronej** [comment]
Thank you for taking the time to close
