### ISSUE TITLE
After type command in a keycloakify-starter: yarn build-keycloak-theme, get Windows Error: Error: ENOENT: no such file or directory, scandir 'H:\keycloak\ProjectFolder\keycloak-client-themes\build_keycloak\src\main\resources\theme\keycloakify-starter\tmp_suLeKsxId_c5f68d7a\keycloak\account\resources'

### ISSUE THREAD

**Issue by lucasliown** [keycloakify/keycloakify#490]
Node version:v18.17.0
Yarn version:1.22.19
![image](https://github.com/keycloakify/keycloakify/assets/111624902/a0589fa8-7e56-483d-80f3-649eb612c61a)

**Comment by garronej** [comment]
Hello @lucasliown,  
Try `rm -rf node_modules build_keycloak` any try again.  
If the problem persists, use WSL until it's fixed.

**Comment by lucasliown** [comment]
Thanks @garronej. I built theme in WSL Dev container.
