### ISSUE TITLE
Options to remove unnecessary resources from build_keycloak

### ISSUE THREAD

**Issue by RhysOnlyBetter** [keycloakify/keycloakify#497]
Hi,

I'm developing a standalone keycloak theme using the setup described in the starter [here](https://github.com/keycloakify/keycloakify-starter#i-only-want-a-keycloak-theme). I'm not using the `.jar` file, just importing the theme directly from the theme folder in `build_keycloak`. 

Since I'm using a completely different component library/css etc than the starter app I've removed all dependencies to zocial, pattennfly etc from the package, and removed `"postinstall": "copy-keycloak-resources-to-public",` from the package.json scripts.  

I've noticed the bundle size is still being greatly inflated greatly by the `resources/resources_common` folder, which contains zocial, jquery and patternfly files. I seem to be able to remove this folder without any adverse effects. Are these files necessary for anything I'm unaware of? And if not is there an option to automatically exclude them from the theme files?

Thanks in advance and I really appreciate the project!

**Comment by garronej** [comment]
Helllo @RhysOnlyBetter,  
Yes, you can delete everything you don't use!  
I've made some pretty advanced attempt involving meta programming to automatically detect what assets from the base Keycloak theme are used and inclue only thoses but it actually seems to cause more issues than anything else.  

Before removing the default assets, you have to be aware that there are a lot of pages in Keycloak. For the ones that you do not customize Keycloakify will fallback to the default pages mounted within your custom template.  
Before removing everthing makes sure that every pages renders correctly without the base assets.  

You can acheive this by uncommenting  this: https://github.com/keycloakify/keycloakify-starter/blob/b0ea463f50e6fb3a9a83fb790cd500c3145323ea/src/keycloak-theme/login/kcContext.ts#L96 and trying with every pages.  
The assets that you would need to manually delete in this testing scenario are in /public/keycloak-resources.  

Hope it helps.

**Comment by RhysOnlyBetter** [comment]
Thanks a lot @garronej, much appreciated
