### ISSUE TITLE
Keycloakify Account Theme Calling AccountFormService

### ISSUE THREAD

**Issue by adhurjaty** [keycloakify/keycloakify#505]
## Summary

I am using the account theme with Keycloakify. The react code is displaying as expected, but when I try to create an SPI to pass other server-side variables to the frontend (by setting a new `AccountResourceProvider`), there's no effect. I'm looking at the logs (running locally from docker) and I'm seeing log statements like:

```
INFO  [org.keycloak.services.resources.account.AccountFormService] (executor-thread-1) accountPage
```

Looking at the Keycloak source code, the `AccountFormService` hasn't existed since version 21.1. I'm using Keycloak version 23.0.3. How is Keycloakify calling this old code?

### Keycloak Version

23.0.3

### Keycloakify Version

9.3.1

### Steps to reproduce

1. run `yarn run build-keycloak-theme`
2. copy the *.jar file to the Keycloak root and build
3. select 'mytheme' as the account theme for the realm
4. login/impersonate a user
5. view logs and see the message from an old build of Keycloak

### package.json

```
"scripts": {
    "postinstall": "copy-keycloak-resources-to-public",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "build-keycloak-theme": "yarn build && keycloakify",
    "storybook": "start-storybook -p 6006",
    "test": "jest"
  },
  "keycloakify": {
    "themeName": "mytheme",
    "doBuildRetrocompatAccountTheme": false
  },
"dependencies": {
    ...
    "keycloak-js": "23.0.3",
    "keycloakify": "9.3.1",
    ...
  },

**Comment by adhurjaty** [comment]
Looks like I just needed to use the mytheme_retrocompat theme

**Comment by garronej** [comment]
Ohhhhh! Damn I understand!!! I left "doBuildRetrocompatAccountTheme" to false in the starter!  
That must be why we're losing stars!

**Comment by garronej** [comment]
Thanks for reporting!
