### ISSUE TITLE
[Docs] Typo in v8 -> v9 migration guide

### ISSUE THREAD

**Issue by CamBuscher** [keycloakify/keycloakify#506]
Hey folks, real quick, I just noticed a typo in the migration docs and it caused me to overlook a dependency for a moment:

[Link to docs](https://docs.keycloakify.dev/migration-guides/v8-greater-than-v9)

Currently it says:
```You now must have nvm (Maven, brew install maven) ```

It should say:
```You now must have mvn (Maven, brew install maven) ```

**Comment by garronej** [comment]
Oh, I understand now!  
Thank you so much for bringing this to my attention. I mixed up the node version manager.  
Recently, Keycloakify has lost 4 stars, which generally indicates some level of frustration. This might be at the heart of the issue.
