### ISSUE TITLE
Can Signed in User information be accessed in `login-oauth-grant` file?

### ISSUE THREAD

**Issue by pavandv** [keycloakify/keycloakify#511]
Hello, Good day to you sir.

I have a requirement where I have to access the information of signed in user in the `login-oauth-grant` page. Currently, `kcContext#login` gives an empty object and I'm wondering if this can be populated with Signed in User info.

I have gone through `ftl_object_to_js_code_declaring_an_object.ftl` to understand if there is a way to get the info, but I didn't find any information related to login information.

Thank you for this awesome project :)

**Comment by garronej** [comment]
Hello @pavandv,  

Unfotunatly I think it's impossible. Keycloak does not provide the user information in the user facing pages.   
The `window.kcContext` contains everything Keycloak exposes to the FreeMarker context. The `ftl_object_to_js_code_declaring_an_object.ftl` loops over the FTL context and transforms it into the declaration of a global javascript object.  
If what's you're looking isn't on the kcContext then it means the information is not available.  

I'd be happy to be prouven wrong though!
