### ISSUE TITLE
realmRolesAvailable seem to be missing from kcContext

### ISSUE THREAD

**Issue by giorgoslytos** [keycloakify/keycloakify#512]
I am working on the addition of extra account pages and I came up across a potential issue in the `Applications` page, which corresponds to the following [Keycloak page](https://github.com/keycloak/keycloak/blob/15.1.1/themes/src/main/resources/theme/base/account/applications.ftl) page.

In the `Applications` page `realmRolesAvailable` and `resourceRolesAvailable` are merged in the `Available Roles` column.

The problem is that the `realmRolesAvailable` property of the `applications` property of `kcContext` return always [{}] when it should be returning data that include the information of the key `role_offline-access` ("Offline access"), which is nowhere available in the kcContext.

Desired Behavior:
![image](https://github.com/keycloakify/keycloakify/assets/50946162/8213b785-937c-4b15-b07f-47240c0f8e60)

Current Behavior:
![image](https://github.com/keycloakify/keycloakify/assets/50946162/fc30cd9b-d0de-4558-8d67-e723af1c0d3c)

**Comment by garronej** [comment]
Hum, thanks for reporting.  
We always have the ability to implement custom cases for some pages.  
However let's see what the HTML says first.  
Could you copy past the rendered HTML on the page?

**Comment by giorgoslytos** [comment]
Sure! Here it is.
```
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <td><span>Application</span></td>
            <td><span>Available Roles</span></td>
            <td><span>Granted Permissions</span></td>
            <td><span>Additional Grants</span></td>
            <td><span>Action</span></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a href="http://127.0.0.1:8080/realms/master/account/"><span>Account</span></a>
            </td>
            <td>
                <span
                    ><span
                        ><span>View profile</span><span>in</span> <strong><span>Account</span></strong
                        >, </span
                    ><span
                        ><span>Manage account links</span><span>in</span> <strong><span>Account</span></strong
                        >, </span
                    ><span
                        ><span>Manage account</span><span>in</span> <strong><span>Account</span></strong></span
                    ></span
                >
            </td>
            <td>
                <strong><span>Full Access</span></strong>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <a href="http://127.0.0.1:8080/realms/master/account/"><span>Account Console</span></a>
            </td>
            <td>
                <span
                    ><span
                        ><span>Manage account links</span><span>in</span> <strong><span>Account</span></strong
                        >, </span
                    ><span
                        ><span>Manage account</span><span>in</span> <strong><span>Account</span></strong></span
                    ></span
                >
            </td>
            <td>
                <strong><span>Full Access</span></strong>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><span>Admin CLI</span></td>
            <td></td>
            <td>
                <strong><span>Full Access</span></strong>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <a href="http://127.0.0.1:8080/admin/master/console/"><span>security admin console</span></a>
            </td>
            <td></td>
            <td>
                <strong><span>Full Access</span></strong>
            </td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
```

**Comment by garronej** [comment]
@giorgoslytos I mean what's in th `<head />`

**Comment by garronej** [comment]
Ok I see!  
I've removed all `applications.applications[].client.realm.*` because serializing all the `data_model` resulted in a 12Mb pages aparently!!!  
See issue: https://github.com/keycloakify/keycloakify/discussions/432#discussioncomment-7332729  

So here it appears that we should implement a finer grained filter.  

This is the current filter in place:  https://github.com/keycloakify/keycloakify/blob/2a88e6802f99f40f82bb67f20a44b80fc82d8d19/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L490-L496  

If you could tell me precisely, according to you, what should be included and what should be excluded that would help greatly.

**Comment by giorgoslytos** [comment]
Great!
I am a little busy at this moment, but I will try to provide you my insights as soon as I can!

**Comment by giorgoslytos** [comment]
It seems that the properties of `realmRolesAvailable` that are used in the template of `applications.ftl` are `name` and `description`

**Comment by garronej** [comment]
Thanks for the investigation.  
I'll do it asap but I can't today.

**Comment by garronej** [comment]
I'm on it...

**Comment by garronej** [comment]
It's fixed for good! 👍🏻  
I identified the problematic part in the context of the applications.ftl page and excluded thoses parts from being transfered over to the js context.  
All the rest will be present.
