### ISSUE TITLE
Keycloak 24

### ISSUE THREAD

**Issue by garronej** [keycloakify/keycloakify#517]
Keycloak 24 has just been released:  

https://github.com/keycloak/keycloak/releases/tag/24.0.0

There are a few changes to apply to the component library and maybe to the types definitions:  

https://www.keycloak.org/docs/24.0.0/upgrading/#migrating-templates

**Comment by theosanderson** [comment]
We will want to pin keycloak after this. Generally I'm a bit afraid of ever upgrading keycloak due to potential migration problems for users deploying loculus.

**Comment by garronej** [comment]
Ok, let's get this done!  

<img width="436" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/cdbc2146-e49d-4f2b-8fcf-61b546a23cb8">

#533

**Comment by elyas-bhy** [comment]
@garronej what is the ETA on this?

**Comment by garronej** [comment]
Hi @elyas-bhy,  
I'd say 10 days. There is A LOT to do but it will be an overall update of all the component to match the latest version of the default Keycloak theme.  

I can't promise anything though. It might land sooner or later. The project have currently no funding. I'm working on it on my free time.

**Comment by garronej** [comment]
follow progress here: https://github.com/keycloakify/keycloakify/pull/538

**Comment by garronej** [comment]
Keycloakify 10 has been released 🎉
