### ISSUE TITLE
Way to migrate from .ftl to reactjs

### ISSUE THREAD

**Issue by salonsosofinco** [keycloakify/keycloakify#518]
Hello!
First of all, thanks for the tool, looks amazing.

I want to start using it and I have the doubt of how to migrate my custom templates, that I created previously on .ftl to react. Is there a command to do it? Is it possible?

I have searched it on the documentation but I didnt find it.

Thanks!

**Comment by garronej** [comment]
Hello @salonsosofinco,  

Migrating is not an automatic process however Keycloakify isn't reinventing the wheel. The FreeMarker context available on the backend is made available with Keycloakify unde `window.kcContext`.  
The markups just need to be updated from HTML templated with FTL to React using the kcContext.  
All the component provided out of the box are a one to one translation in react of the official theme.  

So my advise for you is to stard playing with the keycloakify starter project. Read the comments and the readme. Soon enough you should understand the similarity and be able to migrate your theme.  

You may need to use this option: https://docs.keycloakify.dev/build-options#extrathemeproperties  

If you need help to debug you can join our discord channel: https://discord.gg/kYFZG7fQmn

**Comment by salonsosofinco** [comment]
Thanks for the quick response, I will follow the advice.

**Comment by garronej** [comment]
Cool.  
You might also need to move over some resources to your build with https://docs.keycloakify.dev/build-options#postbuild-hook  

I don't know maybe maybe not, but it can help you getting it done with minimal refactor efforts.

**Comment by tonythomas1** [comment]
> Hello! First of all, thanks for the tool, looks amazing.
> 
> I want to start using it and I have the doubt of how to migrate my custom templates, that I created previously on .ftl to react. Is there a command to do it? Is it possible?
> 
> I have searched it on the documentation but I didnt find it



> 
> 
Hey were u able to migrate your ftl files into react eventually, I was looking to do the same thing. 
Any tips would help, Thanks!

**Comment by garronej** [comment]
@tonythomas1 It's much much easyer than it uses to be now with IA. With copilot and/or ChatGPT.

I've freshly converted **all** the builtin pages to react a few days ago.  
It hasn't been merged yet but you can use it as a starting point:  

- https://github.com/keycloakify/keycloakify/tree/keycloak_24/src/login/pages
- correspond to: https://github.com/keycloak/keycloak/tree/24.0.4/themes/src/main/resources/theme/base/login  

Hower I would advise you to halt developement until I release Keycloakify v10
