### ISSUE TITLE
Keycloakify >=9.5.0 hangs indefinitely when run through `yarn build-keycloak-theme`

### ISSUE THREAD

**Issue by corneliusroemer** [keycloakify/keycloakify#519]
When bumping keycloakify from 9.4.4 to anything 9.5.0 and above including 9.6.0, keycloakify hangs indefinitely at the `keycloakify` stage in my docker builds - in particular it hangs during the `yarn build-keycloak-theme` step at the `keycloakify` step (after successfully executing `react-scripts build && rimraf build/keycloak-resources`).

Things worked fine up to 9.4.4 - there's nothing in the logs that gives indications what might be going on, no errors/info. It just doesn't do anything for 40+ minutes, rather than 20s.

I tried to find out whether there are CLI options I can pass to keycloakify to get it to give more details in log, but there doesn't seem to be a verbosity option unfortunately.

Does anyone else face this issue? What could be the root cause? How could I debug and possibly fix it?

The dockerfile I use is (up to the point where it hangs):

```Dockerfile
FROM node:21-bookworm as builder

USER root
RUN apt-get update && apt-get install -y maven

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build-keycloak-theme
```

This is quite similar to the Dockerfile from the docs: https://docs.keycloakify.dev/importing-your-theme-in-keycloak

**Comment by garronej** [comment]
Hello @corneliusroemer,   

Sorry about the bad experience.  
I assume you're using CRA?  
Can I have the keycloakify option that you use in your `package.json`?  

Thanks

**Comment by garronej** [comment]
I can reproduce, I'll fix

**Comment by garronej** [comment]
Ok it's fixed in 9.6.1

**Comment by garronej** [comment]
The version is being deployed.  

Sorry I implemented a vite specific feature that I forgot to disable when Keycloakify is building a Webpack project.

**Comment by garronej** [comment]
Thanks for reporting!

**Comment by corneliusroemer** [comment]
I'm happy that it wasn't just me not doing something the right way! That was a very quick fix!

We're based off https://github.com/keycloakify/keycloakify-starter, using config pretty much as described under the "I only want a keycloak theme"

**Comment by corneliusroemer** [comment]
Thanks for the pointer! I can confirm that 9.6.1 now no longer hangs, so bug is fixed!
