### ISSUE TITLE
How to customize WebauthnRegister (webauthn-register.ftl) using Keycloaktify?

### ISSUE THREAD

**Issue by muhammadaskar** [keycloakify/keycloakify#521]
I want to custom webauthn-register.ftl using React Keycloaktify, but in Keycloaktify does not yet provide a custom webauthn-register.ftl

**Comment by garronej** [comment]
Hello @muhammadaskar,  

For pages that are not yet supported we provide two path:  
- Add support for the missing page in your project  
- Submitting a pull request to Keycloakify (It's quite straightforward and it would benefit the community)  

It's explained here: https://docs.keycloakify.dev/limitations#some-pages-still-have-the-default-theme.-why  

You can join us on discord if you need assistance: https://discord.gg/kYFZG7fQmn

**Comment by muhammadaskar** [comment]
Hello @garronej ,

Thanks for quick response. I will try
