### ISSUE TITLE
Can't import login theme resources from Keycloak default theme

### ISSUE THREAD

**Issue by huyenvu2101** [keycloakify/keycloakify#522]
I'm trying to create a custom theme for Keycloak using the newest Keycloak-starter version. The default setting for loginThemeResourcesFromKeycloakVersion is 11.0.3, but when I change it to the version (19.0.1) in my `vite.config.ts` file, the theme doesn't work as expected.

**What I've done:**
- Updated Keycloak-starter to the latest version and follow the migration guides [CRA to Vite](https://docs.keycloakify.dev/migration-guides/cra-greater-than-vite) 
- Set loginThemeResourcesFromKeycloakVersion to 19.0.1 in vite.config.ts.
- Used default theme resources in Template.tsx

When I try to access the CSS files listed in styles, I receive a 404 error. This worked correctly in a previous version of CRA

**Relevant code:**
`vite.config.ts`:
```
export default defineConfig({
  plugins: [
    react(), 
    commonjs(), 
    keycloakify({
      themeName: "MY",
      loginThemeResourcesFromKeycloakVersion: "19.0.3",
      extraThemeProperties: [
        "locales=en,vi"
      ]
    })
  ]
})
```
`Template.tsx:`
```
   const { isReady } = usePrepareTemplate({
        "doFetchDefaultThemeResources": doUseDefaultCss,
        "styles": [
            `${url.resourcesCommonPath}/web_modules/@patternfly/react-core/dist/styles/base.css`,
            `${url.resourcesCommonPath}/web_modules/@patternfly/react-core/dist/styles/app.css`,
            `${url.resourcesCommonPath}/node_modules/patternfly/dist/css/patternfly.min.css`,
            `${url.resourcesCommonPath}/node_modules/patternfly/dist/css/patternfly-additions.min.css`,
            `${url.resourcesCommonPath}/lib/pficon/pficon.css`,
        ]
```

Please tell what did I miss :(

**Comment by garronej** [comment]
Hey @huyenvu2101,  

Sorry I removed to much in the last refactor. I fixed it, update Keycloakify to the latest version it should work!

**Comment by huyenvu2101** [comment]
@garronej thank you for supporting, anyway I fixed it by set `doUseDefaultCss=false`, Idk why but It's work

**Comment by garronej** [comment]
> I updated keycloakify to 9.6.2 but there are no differences  

I think you've not updated. I'm positive that in 9.6.1 there's no `web_modules` with the Keycloak assets from 19.0.1 but in `9.6.2`. Maybe you though you updated but actually you didn't, maybe you could try removing the `node_modules`.  

![image](https://github.com/keycloakify/keycloakify/assets/6702424/e7a5770b-f791-4dec-bbe9-9bcce28fe8ed)
 

> I try another way by seting doUseDefaultCss=false  

If you set `doFetchDefaultThemeResources` to false, no css from the default theme will be loaded at all... So while you won't get the 404 you'll probably have pages that don't render properly unles you've fully redone the tyling.

**Comment by huyenvu2101** [comment]
I removed the `node_modules` and try again. You're right there is `web_modules` within the Keycloak assets from 19.0.1 but the `lib` is still missed  since there is a `lib` folder in Keycloak 19.0.1 theme `${url.resourcesCommonPath}/lib/pficon/pficon.css`
