### ISSUE TITLE
Why when i login using 2FA using security key can't logged in?

### ISSUE THREAD

**Issue by muhammadaskar** [keycloakify/keycloakify#524]
Hello. i get issue from WebauthnAuthenticate.tsx. When i login using 2FA security key i can't logged in and i get error from console: 

Uncaught 
Object { error: "access_denied", error_description: undefined }
​error: "access_denied"
error_description: undefined

<img width="1440" alt="Screenshot 2024-03-18 at 14 50 24" src="https://github.com/keycloakify/keycloakify/assets/48124631/be8a1f26-650b-4501-940f-ae1b1a9a2ba6">

**Comment by garronej** [comment]
Hello @muhammadaskar,  

Yes, there's a known bug in the `WebauthnAuthenticate.tsx` page that I didn't find time to fix.  

You can checkout this PR from @D-Simona-G that fixes it:  https://github.com/keycloakify/keycloakify/pull/488

**Comment by muhammadaskar** [comment]
Hello @garronej . Thanks.

I'm sorry PR from @D-Simona-G which fixed it: https://github.com/keycloakify/keycloakify/pull/488 was different to WebauthnAuthenticate.tsx.

**Comment by muhammadaskar** [comment]
can i implement ftl page [https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl](url) in keycloaktify? or any suggestion?

**Comment by garronej** [comment]
Hello @muhammadaskar,  

Yes please! We would love to merge a PR adding this page. If you can't make a PR don't worry you can do that only for your project.  
Anyway it's not very complicated the process is documented here:  

https://docs.keycloakify.dev/limitations#some-pages-still-have-the-default-theme.-why

**Comment by garronej** [comment]
This page and all the others are now featured by default: https://storybook.keycloakify.dev/?path=/story/login-webauthn-authenticate-ftl--default
