### ISSUE TITLE
interceptor and mock ftl file creation

### ISSUE THREAD

**Issue by igrevkr** [keycloakify/keycloakify#527]
Hi, I'm Aiden from South Korea.
We are using keycloak and keycloakify for a new login page this time.
I appreciate for the time and effort for this project.

1. filter
I want to use only the login.ftl file, 
is there anyway that if users try to go to other pages, systems forward to the only login.ftl?

2. mock ftl file
Through keycloakify, we modify tsx codes to generate ftl file for keycloak.
Can I just make someting.ftl file directly and export it to the dist_keycloak path?

**Comment by garronej** [comment]
Hello, thanks for the kinds words,  

> is there anyway that if users try to go to other pages, systems forward to the only login.ftl?

Yes you can but you probably don't want to.  
Please provide a more detailed descriptioin of what user experience you're trying to acheive and I'll try steer you in the right direction.  

> Can I just make someting.ftl file directly and export it to the dist_keycloak path?  

Again, yes, Keycloakify will let you generate a `someting.ftl` file.  

![image](https://github.com/keycloakify/keycloakify/assets/6702424/726a7803-2871-4667-ba85-7f6703925730)
https://docs.keycloakify.dev/limitations  

But you probably don't want to do that. You'd have to write some Java plugin for Keycloak so it can use the the `something.ftl` file generated.  

If I where you I'd take a few hours experimenting with the starter project. Understands how things works, you'll get a better idea of how to acheive your goals.  

Feel free to join our discord for aditional support https://discord.gg/kYFZG7fQmn but it's always better to keep the dicution public.  

Best
