### ISSUE TITLE
how to specfiy Keycloak Version 20.0.1

### ISSUE THREAD

**Issue by Duncan-dsf** [keycloakify/keycloakify#528]
The latest version of the class object is java 17, does't match java 11 in keycloak 20.0.1.
<img width="1810" alt="image" src="https://github.com/keycloakify/keycloakify/assets/29371215/c52adc02-a357-417a-85a3-9eda392b27bc">

**Comment by garronej** [comment]
Hello @Duncan-dsf,  

For usage of your theme in Keycloak 20 you must use the `retrocompat-*.jar` jar generated by Keycloakify.  
https://docs.keycloakify.dev/migration-guides/v8-greater-than-v9
