### ISSUE TITLE
[Error screen] Back to application button

### ISSUE THREAD

**Issue by nguyenhuyhoang241298** [keycloakify/keycloakify#529]
Hello, Im creating a error screen. When it's deployed to the production, Back To Application button is not working. Can someone tell me the reason?
Many thanks.

This is my code
![image](https://github.com/keycloakify/keycloakify/assets/113531382/055a2249-cf5b-45d4-a27f-f8428badddec)

Versions: 
    "keycloakify": "^9.1.4",
    "oidc-spa": "^2.2.0",
    "powerhooks": "^0.26.8",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-icons": "^5.0.1",
    "tsafe": "^1.6.0"

**Comment by giorgoslytos** [comment]
@nguyenhuyhoang241298 Most probably the baseUrl is not configured in your Keycloak admin console for that client

**Comment by giorgoslytos** [comment]
@garronej @nguyenhuyhoang241298 There is also a chance that you might be facing this issue https://github.com/keycloakify/keycloakify/issues/532

**Comment by nguyenhuyhoang241298** [comment]
Thanks, I fixed my bug
