### ISSUE TITLE
How to overide default locale from keycloak

### ISSUE THREAD

**Issue by misterbit-pro** [keycloakify/keycloakify#531]
Hello,

I wanna know if there's a clean way to override the default locale from keycloak in the theme. As in the company I am working for we are using Keycloak as auth for an internal NextJS app an this app already saves the languge set by the user in a cookie. So its easy to just read out the cookie and then use the given langTag from the cookie to override the default locale and set this one as default at start.

What is a clean way to do that?

**Comment by garronej** [comment]
Hello @misterbit-pro,  

The clean way is to pass an extra query paramater when redirecting to Keycloak's login page:  
`ui_locales=en`  

See here how it's done with [oidc-spa](https://github.com/keycloakify/oidc-spa):  

https://github.com/keycloakify/keycloakify-starter/blob/4529ae8727489b8cdd6197ac512041ced14a4c62/src/App/oidc.ts#L17-L24  

You can also pass the parameter when calling the login method:  

```ts
login({
    doesCurrentHrefRequiresAuth: false,
    extraQueryParams: { ui_locales: "en" }
});
```  

https://github.com/keycloakify/keycloakify-starter/blob/4529ae8727489b8cdd6197ac512041ced14a4c62/src/App/App.tsx#L51-L54  

As you're working on a next app you'll probably be using NextAuth.js insted of oidc-spa but the core principle remain the same.  

In any case, this is not related to Keycloakify directly, this is a builtin Keycloak spec.

**Comment by misterbit-pro** [comment]
> Hello @misterbit-pro,  
> 
> The clean way is to pass an extra query paramater when redirecting to Keycloak's login page:  
> `ui_locales=en`  
> 
> See here how it's done with [oidc-spa](https://github.com/keycloakify/oidc-spa):  
> 
> https://github.com/keycloakify/keycloakify-starter/blob/4529ae8727489b8cdd6197ac512041ced14a4c62/src/App/oidc.ts#L17-L24  
> 
> You can also pass the parameter when calling the login method:  
> 
> ```ts
> login({
>     doesCurrentHrefRequiresAuth: false,
>     extraQueryParams: { ui_locales: "en" }
> });
> ```  
> 
> https://github.com/keycloakify/keycloakify-starter/blob/4529ae8727489b8cdd6197ac512041ced14a4c62/src/App/App.tsx#L51-L54  
> 
> As you're working on a next app you'll probably be using NextAuth.js insted of oidc-spa but the core principle remain the same.  
> 
> In any case, this is not related to Keycloakify directly, this is a builtin Keycloak spec.  

Ok I see thx, but there is no way to initilize i18n with a different language, as the usei18n hook is from keycloaify I saw. As I already have the cookie available this would be easy to do, otherwise I will add the query parameter as you say.

**Comment by garronej** [comment]
The thing is that there might be some translations that comes from the Keycloak server as well.  
The Keycloak server need to know which local is enabled, it's not enough to do the switch only on the frontend side.  

More info here: https://www.youtube.com/watch?v=D6tZcemReTI

**Comment by misterbit-pro** [comment]
I see then I will use the query param as discussed before. Thank for your help
