### ISSUE TITLE
Register User Profile Page was removed in Keycloak 24

### ISSUE THREAD

**Issue by khanhprolazay** [keycloakify/keycloakify#533]
Hi keycloakify team,

Based on Keycloak 24 migration, They render custom attributes directly in the register page (and two another pages).
![Screenshot from 2024-04-05 23-03-22](https://github.com/keycloakify/keycloakify/assets/91310395/ae48bc44-8d2c-455c-8ad0-bac95c96bde5)

Therefore, they removed register user profile page.
![Screenshot from 2024-04-05 23-08-55](https://github.com/keycloakify/keycloakify/assets/91310395/4e2a0a8e-101a-47b6-a53c-525cd6d16289)

You can read more detail via this [link](https://www.keycloak.org/docs/latest/upgrading/index.html#changes-to-freemarker-templates-to-render-pages-based-on-the-user-profile-and-realm)

When I add additional user attributes (phoneNumber), Keycloak 24 will render the register page, which in the theme, this page hasn't implemented the dynamic rendering mechanism yet.

When I use keycloak theme:
![Screenshot from 2024-04-05 23-27-15](https://github.com/keycloakify/keycloakify/assets/91310395/81c80cbf-d53d-44d8-bd33-60f3dce6e87f)

When I use theme build by Keycloakify:
![Screenshot from 2024-04-05 23-30-00](https://github.com/keycloakify/keycloakify/assets/91310395/7689b0e9-87b7-4d48-9dd0-5ac75e18f2e2)

Hope you find this well.

**Comment by garronej** [comment]
Hello @khanhprolazay,  
Yes thank you for reporting.  
We're aware of this, it need to be addressed.  
The challenging part is that this is a breaking change for every older Keycloak version.  
Maybe we will have to provide different template for different target version.  

In the meantime, remember that the components provided by Keycloakify can be overwrwiten. You don't need to use our components, you can freely modify or update them on your side.  

Best.

**Comment by HeileneMartin** [comment]
Hello @garronej,

We're currently utilizing keycloakify-starter in our project and have encountered an issue similar to what @khanhprolazay has previously reported.

Our challenge lies in overriding the Register component. Here's what we've attempted so far:

We tried to add the UserProfileFormField component to our Register.tsx file. However, we ran into a problem where the context is asking for the 'profile' property, which seems to be part of the 'register-user-profile' context. Could you provide some guidance on how to correctly add this component?

We also attempted to create a custom field with the value {register.formData['user.attributes.phone']}. We're not sure if this is the correct approach, and would appreciate any advice you could give on this.

Here's an excerpt from our Register.tsx file for reference:

` <input
      type="text"
      id="user.attributes.phone"
      name="user.attributes.phone"
      value={(register.formData['user.attributes.phone']!'')}
    />`

Any assistance you could provide would be greatly appreciated.

Thank you in advance for your help.

**Comment by garronej** [comment]
Hello @HeileneMartin,  

It's in my top priority to work on this.  

> We tried to add the UserProfileFormField component to our Register.tsx file. However, we ran into a problem where the context is asking for the 'profile' property, which seems to be part of the 'register-user-profile' context. Could you provide some guidance on how to correctly add this component?  

I think the `profile` should actually be on the kcContext, it's just that the type definition are not up to date. you can use `kcContext as any` or oveload the type definition in your kcContext.ts file.

**Comment by HeileneMartin** [comment]
Hello @garronej 

Thank you for your quick response to this. I've been trying to get this working for the last couple of days. 

I've logged the kcContext to the console which showed my test field that I created in KeyCloak. The following code worked and recorded the input value I entered on submitting the form :

`<div>
                          <div>
                            <input
                              type="text"
                              id="test"
                              name="test"
                              value={
                                (register.formData as { [key: string]: string })[
                                  'user.attributes.test'
                                ]
                              }
                            />
                          </div>
                        </div>`

**Comment by garronej** [comment]
@HeileneMartin I'm sorry you had to go through this.  
I'm doing my best to keep Keycloakify up to date but Keycloak 24 is a major breaking change.  
It's now imposible to have a theme that will work both on Keycloak prior to 24 and 24 and up. That's a shame.  

I'm glad you where able to make it work.

**Comment by garronej** [comment]
Follow progress here: https://github.com/keycloakify/keycloakify/pull/538

**Comment by garronej** [comment]
All this have been fixed in Keycloakify 10
