### ISSUE TITLE
JAR building - problem with CSS

### ISSUE THREAD

**Issue by SpoljarecNikola** [keycloakify/keycloakify#536]
I made some changes in src/keycloak-theme/login/login.css. After building the theme with npm run build-keycloak-theme, I end up with dist_keycloak where, in dist_keycloak/src/main/resources/theme/keycloakify-starter/login/resources/css/login.css, I find some CSS that I don't want. It contains 20 lines less than my original CSS file, so I'm wondering where this file comes from. Even if I modify that file and run npm run build-keycloak-theme again, my changes get deleted. How can I have my own CSS code in that file? Thank you in advance.

**Comment by garronej** [comment]
Hello @SpoljarecNikola,  

`dist_keycloak/src/main/resources/theme/keycloakify-starter/login/resources/css/login.css` is the css of the default Keycloak theme.  

You can't modify it.  

You can prevent it from being loaded by commenting this line:  

https://github.com/keycloakify/keycloakify-starter/blob/4da6993761bfd363781834193ca06d4a71841805/src/keycloak-theme/login/Template.tsx#L42  

You can allso prevent all default css to be loaded by setting the template props `doUseDefaultCss` to false for some or all pages.  

https://github.com/keycloakify/keycloakify-starter/blob/4da6993761bfd363781834193ca06d4a71841805/src/keycloak-theme/login/KcApp.tsx#L62

I advise agaist it though.  

What you probably want to do it to overwrite the default style by modifying:  

https://github.com/keycloakify/keycloakify-starter/blob/main/src/keycloak-theme/login/KcApp.css  

That is imported here:  

https://github.com/keycloakify/keycloakify-starter/blob/4da6993761bfd363781834193ca06d4a71841805/src/keycloak-theme/login/KcApp.tsx#L1  

As this is more of a support request that an issue I'll close this as resolved.  

Best
