### ISSUE TITLE
When I run yarn build-keycloak-theme I got an error and I didn't generate the .jar file

### ISSUE THREAD

**Issue by maxtrodaro** [keycloakify/keycloakify#541]
When I try to generate my .jar file with the build-keycloak-theme, can you help me?

<img width="989" alt="Screenshot 2024-04-19 at 12 24 56" src="https://github.com/keycloakify/keycloakify/assets/46817375/8e73a8f4-0ee5-426e-a926-c9bc40e41691">
<img width="522" alt="Screenshot 2024-04-19 at 12 25 09" src="https://github.com/keycloakify/keycloakify/assets/46817375/28df8365-d310-49d4-a606-0af790f86265">

**Comment by garronej** [comment]
Hello @maxtrodaro,  
I'll need more information about your environement. Your configuration. What version of Keycloakify you are using. ect.

**Comment by maxtrodaro** [comment]
Node version: 18.20.0
Keycloak: 21.0.0
Yarn: 1.22.22
Keycloakify: 9.6.6

I cloned the keycloakify-starter project [here](https://github.com/keycloakify/keycloakify-starter). Storybook, locally and `yarn build` it works perfectly. Just when I use build-keycloak-theme I got this error.

**Comment by garronej** [comment]
Looks like you are using https://www.npmjs.com/package/mvn?activeTab=readme.  

Please (assuming you are on mac)

```bash
npm uninstall -g mvn
brew install nvm
```

It should work after that

**Comment by maxtrodaro** [comment]
It works! Many thanks!
