### ISSUE TITLE
adding a custom css file and importing it

### ISSUE THREAD

**Issue by loralameh** [keycloakify/keycloakify#543]
I am using the Starter/demo project for Keycloakify

i want to customize a login page similar to the default keycloak login page but i need to customize some global colors. so i added a login.css file in the public directory which is a copy of the default login.css found in (public/keycloak-resources/login/resources/css/login.css) but with some changes.

![Screenshot 2024-04-23 141205](https://github.com/keycloakify/keycloakify/assets/66212592/bfe4594e-705d-4d47-ac62-9b07a73118c1)

i am trying to import it in the same manner as the starter imports its default styles 
code in src/login/Template.tsx
```
const { isReady } = usePrepareTemplate({
  doFetchDefaultThemeResources: doUseDefaultCss,
  styles: [
    `${url.resourcesCommonPath}/node_modules/patternfly/dist/css/patternfly.min.css`,
    `${url.resourcesCommonPath}/node_modules/patternfly/dist/css/patternfly-additions.min.css`,
    `${url.resourcesCommonPath}/lib/zocial/zocial.css`,
    `./assets/login.css`
  ]
});
```
this is working in well in the storybook however this is not working in keycloak as the public path seems to to different.

so I am wondering where to place my css file and how to import it

**Comment by garronej** [comment]
Hello @loralameh,  

This isn't like this that you add your custom style.  

The `usePrepareTemplate` hook is only for importing builtin assets that comes with Keycloak.  
For anything else you would do just as you do for a regular React App.  

You can for example put `login.css` in `src/keycloak-theme/login/assets`
And import it like this:  

`src/keycloak-resources/login/Template.tsx`
```tsx
import "./login.css"
```
https://docs.keycloakify.dev/importing-assets

**Comment by loralameh** [comment]
thanks for your reply 👍 that solved my confusion
