### ISSUE TITLE
idp-review-user-profile.flt page not updating

### ISSUE THREAD

**Issue by HeileneMartin** [keycloakify/keycloakify#544]
Hi there, we've made changes to the idp review page but keycloak is not picking up these changes. 

I'm working with the starter kit and grabbed the file from the KeyCloakify git repository - 

https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/IdpReviewUserProfile.tsx

I've updated the login kcContext to include the page in the kcContextExtention. 

I've made a small change to the page however this is not be reflected on the rendered page when signing in with idp and additional info is required. 

Are these pages being replaces similar to the register-user-profile page?

**Comment by garronej** [comment]
Hello @HeileneMartin,  

The `idp-review-user-profile.ftl` hasn't be remove or renamed in Keycloak 24: https://github.com/keycloak/keycloak/blob/24.0.3/themes/src/main/resources/theme/base/login/idp-review-user-profile.ftl  

Can you try and open your terminal on the page where you do not see the changes, and type console.log(kcContext).  
Tell me what you get. In particular kcContext.pageId. Thanks.

**Comment by HeileneMartin** [comment]
Hi @garronej 

Thanks for the quick response. The console log shows the idp page. 

![image](https://github.com/keycloakify/keycloakify/assets/71242249/2dd00697-d021-4c96-bc69-a2d41d181bea)

**Comment by garronej** [comment]
Are you sure it's not falling back to the default?  
Maybe you've forgot to add a case to the `src/login/KcApp.tsx` router?  

https://github.com/keycloakify/keycloakify-starter/blob/3a3b112d01ef286f3e6763ea9c12d5d22a29ab4b/src/keycloak-theme/login/KcApp.tsx#L47-L50

**Comment by HeileneMartin** [comment]
:grimacing: - I missed that. This is working now as expected. Thanks
