### ISSUE TITLE
Infinite "Loading the Admin UI" with 404 "Not found" errors when running ./dist_keycloak/start_keycloak_testing_container.sh

### ISSUE THREAD

**Issue by stzagkarak** [keycloakify/keycloakify#545]
Keycloak version 23.0.6

Hi, I just started tinkering with the starter project in order to create a custom theme. 

Just for testing, I replaced the return of Template.tsx to `<div>Hello</div>` and made other appropriate adjustments for errors to stop appearing due to this change. The "Hello" is apparent in storybook stories with no errors. Running `yarn build-keycloak-theme` completes and the appropriate files are created in `dist` and `dist_keycloak`. 

When I run the keycloak testing container no errors show up in the logs but the admin UI fails to load. 
![image](https://github.com/keycloakify/keycloakify/assets/113338595/0223055b-cbae-4612-9e38-1a8f18c7f759)

Building and running a clean project works fine.

What could I be doing wrong?

**Comment by garronej** [comment]
Hello @stzagkarak,  

Maybe just do:  

```bash
rm -rf node_modules dist dist_keycloak
yarn install
yarn build-keycloak-them
```

Then try to run the testing container again.

**Comment by stzagkarak** [comment]
Hi, thanks for the quick response! 

Yep, re-installing dependencies did the trick. Weird behavior. 

Thanks again!

**Comment by garronej** [comment]
Yeah this appened to me one time. I don't remember exactly was the root of the issue but I remeber it was an edge case that could be fixed just by re installing.

**Comment by garronej** [comment]
I found the actual bug. It will be fixed on v10. Sorry for discarding this.
