### ISSUE TITLE
Support Keycloak defined message bundles

### ISSUE THREAD

**Issue by hmz22** [keycloakify/keycloakify#549]
I create my own them with this library and use sample [keycloakify-starter](https://github.com/keycloakify/keycloakify-starter)
after build and copy jar file to keycloak /opt/keycloak/providers directory and restart it and in theme menu select it and theme work but when go to localization tab and change displayName but don't effect and not change why?
![Screenshot 2024-05-15 105203](https://github.com/keycloakify/keycloakify/assets/36853974/42e74be6-260a-4bd9-b83a-8f195f9479a3)
![Screenshot 2024-05-15 105151](https://github.com/keycloakify/keycloakify/assets/36853974/93e51798-f311-487b-a9bd-415445fd45d7)
![Screenshot 2024-05-15 105219](https://github.com/keycloakify/keycloakify/assets/36853974/7506a36c-25d9-4c63-833b-e56342af8efe)
![Screenshot 2024-05-15 105233](https://github.com/keycloakify/keycloakify/assets/36853974/b3c8ba08-e222-472b-8145-cc50ed12d18a)
![Screenshot 2024-05-15 105335](https://github.com/keycloakify/keycloakify/assets/36853974/f7b6a314-91ae-43b3-9077-add2a3198598)

**Comment by garronej** [comment]
Hello @hmz22,  

Keycloakify features an i18n system of it's own.  
It greatly improve the maintnability and ease of use compared to editing the message directly from the Keycloak UI.  
It's also much easyer to debug locally.  

See: https://docs.keycloakify.dev/adding-text-keys  

https://www.youtube.com/watch?v=D6tZcemReTI  


Best

**Comment by hmz22** [comment]
so u say they didn't work in keycloak and must just use keycloakify i18n?

**Comment by garronej** [comment]
Yes.  

But look at it this way, when you develop a theme, you want it to be self contained. Not having half of the configuration as server params.  
Also, testing the theme locally outside of Keycloak would be very difficult if we had to pull the i18n resources from the server.  

In you case:  

`src/keycloak-theme/login/i18n.ts`
```ts
import { createUseI18n } from "keycloakify/login";

export const { useI18n } = createUseI18n({
    en: {
       nationalCode: "National Code",
       fatherName: "Father Name"
    },
    ar: {
        nationalCode: "الرمز الوطني",
        fatherName: "اسم الأب"
    },
    // ... other languages
});

export type I18n = NonNullable<ReturnType<typeof useI18n>>;
```

**Comment by garronej** [comment]
After second though there might be some valid usecase for this.  
I could implement it if pepoles needs it...

**Comment by garronej** [comment]
Yes I think this is something that should be supported.

**Comment by garronej** [comment]
I realized that this is infact high priortiy.

**Comment by garronej** [comment]
Ok, it's done. It will work in Keycloakify 10.

**Comment by garronej** [comment]
I'm glad I implemented this since now in Keycloak 25 it's mandatory to add a translation for the display name to be able to createa new user profile attribute. 
<img width="1138" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/faeecf01-ee2f-497d-a1c8-16768d345da0">
