### ISSUE TITLE
Help for getting started

### ISSUE THREAD

**Issue by Ryukote** [keycloakify/keycloakify#552]
I am trying to use keycloakify to make custom theme. For start, I want to connect it with the realm, so I can test if I can login or not with the realm user. What I have done is changed keycloakUrl, keycloakRealm and keycloakClientId in oidc.ts file, but when I enter username (email) and password and hit login, the only request it trigger is http://localhost:6006/index.json and nothing else. What should I do in order to enable login to my realm and get access token back as I do get from original login theme?

Thank you

**Comment by garronej** [comment]
Ok it depends, what are you building exactly?  
Just a Keycloak theme?  
Like your company have a Keycloak and your job is to customize the theme is that it?

**Comment by Ryukote** [comment]
Yes

**Comment by garronej** [comment]
I see.  
You can't "connect" to a Keycloak per say. You have to load the jar generated by Keycloakify into your Keycloak by following theses instructions:  https://docs.keycloakify.dev/importing-your-theme-in-keycloak  

If you just want to test in a local Keycloak you can run the command `./dist_keycloak/start_keycloak_testing_container.sh` the command and instructions are printed to the console after you run `yarn build-keycloak-theme`

**Comment by Ryukote** [comment]
So, you want to say that what I did is ok (changing values in oidc.ts file) and all I need to do is build the theme and upload it to keycloak? I did that already, but I don't get anything out of it.

**Comment by Ryukote** [comment]
Ah ok I get it. I have followed instructions for removing src/App and moving other stuff to it after that. I still don't get anything after I click login. If I use url.loginAction in action on the form, it stays on the login form and doesn't trigger any request under network in F12. If I change that to http://localhost:3399 where my app is up and running it says "This localhost page can't be found" with 404 error, but when I refresh that site, it opens my app, but I don't get access token. I am confused. I will give you the code I have on some playground. I would be happy if you can check that out. Also, do I need to specify something very specific in client configuration?

**Comment by garronej** [comment]
You are in development mode outside keycloak.  
The dev mode is just a dummy mode that enables you to see how the pages looks like so you can work on the design. That's it.  
It's like if you were playing flight simulator and got surprised you did't move ^^

Check this video try to reproduce this https://youtu.be/WMyGZNHQkjU?si=ZlI43saxCxzVepx7

**Comment by garronej** [comment]
Ok, I see.  

You are using mock data in production: 
https://github.com/Ryukote/keycloakify-test/blob/c9d58f9f8b29bff4509c0273b2ebcbc95153f692/src/login/kcContext.ts#L100  

This line must me commented.  

There should be a big red id in the console about it like:
