### ISSUE TITLE
Some languages do not have labels, it appears to be the iso code.

### ISSUE THREAD

**Issue by MuratKaragozgil** [keycloakify/keycloakify#554]
This is the custom template that i develop with keycloakify-start project. But Portugese doesn't seem pretty. I couldn't find the label of these languages on Keycloakify-starter and keycloakify project. How can i change these language labels ?

![CleanShot 2024-05-17 at 12 40 09](https://github.com/keycloakify/keycloakify/assets/8644827/f7b63096-54d8-4e3d-b19b-7972edfe5619)

Keycloak version -> 23.0.6
Keycloakify version -> 9.6.7

**Comment by garronej** [comment]
Thank you for reporting, I'll have a look at it this week end

**Comment by MuratKaragozgil** [comment]
@garronej Any news ? I really have no idea why this is happening. I changed my Keycloak version. Still not resolved.

**Comment by garronej** [comment]
Hello @MuratKaragozgil,  
Sorry I said that I'd look at this in the week end but I'm realy under for the Keycloakify 10 release.  

It's a typo in Keycloak resources. Only for the brazilian language label.  
In the language resources they defined the key `locale_pt_BR` but it should be `locale_pt-BR`.
I'll submit a PR to fix it.  

In the meantime you can fix it in your Keycloakify theme by doing:  

`src/keycloak-theme/login/i18n.ts`
```ts
import { createUseI18n } from "keycloakify/login";

export const { useI18n } = createUseI18n({
    en: {
       "locale_pt-BR": "portuguès (Brasil)",
    },
    // ... if you don't have any other custom translation you can just use english.  
    // otherwise copy paste the key/value in every langage.  
});

export type I18n = NonNullable<ReturnType<typeof useI18n>>;
```

**Comment by MuratKaragozgil** [comment]
Really appreciate that ! Thank you.

**Comment by garronej** [comment]
You're welcome, thank you for reporting.  
I implemented a patch, it will be fixed in Keycloakify v10
