### ISSUE TITLE
Base path not supported?

### ISSUE THREAD

**Issue by JumpAttacker** [keycloakify/keycloakify#556]
Im hosting my keycloak server with basepath = /sso behind reverse proxy

https://a.uguu.se/dMmLXTll.png

and when i try to open image i cant find it and got an error
{"error":"Unable to find matching target resource method","error_description":"For more on this error consult the server log at the debug level."}

https://my-http-server.com/sso/keycloakify-logo.png

also already enable
base: '/sso/',
in vite config

https://a.uguu.se/XvRjSKrt.png

seems import.meta.env.BASE_URL is working, but vite not working correctly with dat baseurl
https://a.uguu.se/WqZFGpuj.png

**Comment by garronej** [comment]
Hello @JumpAttacker,  

Yes, hosting on a subpath is indeed supported.  
However there is a missunderstanding on how keycloak serves resources.  
You can't predict ahead of time where the assets will be.  
You can only know it at runtime in the `kcContext`:  

![image](https://github.com/keycloakify/keycloakify/assets/6702424/384e1988-f86b-4008-b959-8bc9b9219f37)

![image](https://github.com/keycloakify/keycloakify/assets/6702424/60afce25-a495-437c-bd28-41daa8b78e24)


Do not put `base: '/sso/'` in your Vite config. This would be relevent only if you where building a React App that shared the same codebase with the Keycloak theme and it was hosted under like: `https://dasboard.my-company.com/soo` which doesn't make sense. Why would you host anything else but a login page uner `/sso`....  

By the way, I can't see the images you send.   

Best

**Comment by garronej** [comment]
See example here: https://docs.keycloakify.dev/customization-strategies/component-level-customization/in-react-components
