### ISSUE TITLE
User session count limiter with dedicated page

### ISSUE THREAD

**Issue by smietanka** [keycloakify/keycloakify#557]
Hello I need to implement dedicated empty error page when I will get specific error from keycloak. I have set inside keycloak a dedicated flow with `User session count limiter`
![image](https://github.com/keycloakify/keycloakify/assets/17428659/cb986dc6-a2e3-4996-be8d-36201a83763e)

I would like to have a possibility to show this error page only for this specific error.
Now keycloak context contains `pageId: 'error.tfl'` with correct `summary` property in `message`, but also there is something inside `auth`:
![image](https://github.com/keycloakify/keycloakify/assets/17428659/081f18e6-42b9-421a-9fe6-605b2a3ea934)

In current state I would like to have something to distinguish (probably by authenticator inside `auth > authenticationSelections > authenticationExecution> authenticator`) but this is not inside keycloak context. 
This is my current state
![image](https://github.com/keycloakify/keycloakify/assets/17428659/14265a6b-16b9-417c-befa-4dd24aef5dfb)

Is there a way to achieve this distinguish?

**Comment by garronej** [comment]
Hello @smietanka,  

Well first of, the `KcContext` type definition is only an insight of what's usually in the `kcContext` at runtime. It's in no way exhaustive, we only define the properties that are actually used in the default pages.  

Now you have to way to go about what you'd like to do.  
First is to just don't care about type safety and use `(kcContext as any).auth...` for your test.  
But it you want to go the clean route you'd extend the type definition of the `KcContext` for the `error.ftl` page.  

`src/login/kcContext.ts`
```ts
import { createGetKcContext } from "keycloakify/login";

export type KcContextExtension =
	| { 
		pageId: "error.ftl"; 
		auth?: {
			authenticationSelections?: {
				authenticationExecution?: {
					authenticator?: string;
				}
			}[]
		}
	};

export const { getKcContext } = createGetKcContext<KcContextExtension>({
	mockData: [
	],
	mockProperties: {
		MY_ENV_VARIABLE: "Mocked value"
	}
});

export const { kcContext } = getKcContext({
	// Uncomment to test the login page for development.
	//mockPageId: "login.ftl",
});


export type KcContext = NonNullable<ReturnType<typeof getKcContext>["kcContext"]>;
```

With that TypeScript will let you access the properties you need:  

`src/login/KcApp.tsx`
```tsx
import "./KcApp.css";
import { lazy, Suspense } from "react";
import Fallback, { type PageProps } from "keycloakify/login";
import type { KcContext } from "./kcContext";
import { useI18n } from "./i18n";
import Template from "./Template";

const Error = lazy(() => import("keycloakify/login/pages/Error"));

const classes = {
} satisfies PageProps["classes"];

export default function KcApp(props: { kcContext: KcContext; }) {

    const { kcContext } = props;

    const i18n = useI18n({ kcContext });

    if (i18n === null) {
        return null;
    }

    return (
        <Suspense>
            {(() => {
                switch (kcContext.pageId) {
                    case "error.ftl":
                        return kcContext.auth?.authenticationSelections?.[0]?.authenticationExecution?.authenticator === "user-session-limits" ?
                            <h1>My custom error page</h1> :
                            <Error {...{ kcContext, i18n, classes }} Template={Template} doUseDefaultCss={true} />;
                    default: return <Fallback {...{ kcContext, i18n, classes }} Template={Template} doUseDefaultCss={true} />;
                }
            })()}
        </Suspense>
    );
}
```

This is good as it let you easyly create a test case for storybook:  

`src/login/pages/Error.stories.tsx`
```tsx
import { Meta, StoryObj } from '@storybook/react';
import { createPageStory } from "../createPageStory";

const { PageStory } = createPageStory({
    pageId: "error.ftl"
});

const meta = {
    title: "login/Error",
    component: PageStory,
} satisfies Meta<typeof PageStory>;

export default meta;
type Story = StoryObj<typeof meta>;


export const Default: Story = {
    render: () => <PageStory />,
};

export const ExceededNumberOfConcurrentSessionView: Story = {
    render: () => <PageStory kcContext={{
        auth: {
            authenticationSelections: [
                {
                    authenticationExecution: {
                        authenticator: "user-session-limits"
                    }
                }
            ]
        }
    }} />
};
```
