### ISSUE TITLE
Fontfamily "Inter" not working

### ISSUE THREAD

**Issue by fischer-philipp** [keycloakify/keycloakify#559]
Hi, I've setup a Keycloak instance running on version 9.6.7 of Keycloakify. I tried setting the font-family to the standard "Inter" google font, but can't get it working. Changing the font family to "inter" does nothing to the font and it seems that some sort of default keycloak font is being used. 

Here is a picture of the font, which is currently being displayed if I use "Inter" as fontfamily.

![image](https://github.com/keycloakify/keycloakify/assets/122534042/67c844cb-e7e8-419e-85af-a5c92cba8d7c)

Am I missing some sort of import statement or do I need to download the font for it to work?

**Comment by garronej** [comment]
Hello @fischer-philipp,  

Please share how you are importing the fonts. Ther error you're getting in the browser console and how you applies the font.

**Comment by garronej** [comment]
Ok I see why you got confused.  
When I say "out of the box" I mean that it work like in any other app. There's no extra step related to Keycloakify.  
I'll reformulate.

**Comment by fischer-philipp** [comment]
Okay perfect, thanks for the quick response!
