### ISSUE TITLE
Unable to add custom css files to this project?

### ISSUE THREAD

**Issue by KernelFrenzy** [keycloakify/keycloakify#563]
This seems like a silly issue, but I've tried on 3 different computers all with the same issue.

When I add a css file anywhere in the project, I cannot import it into Template.tsx.
However, if I use the keycloakify-starter application, this does work. And this works on all of my other front-end apps too.

I forked the most recent version of Keycloakify and I created a new branch with the change, 1 commit 2 changes.
https://github.com/KernelFrenzy/keycloakify/tree/feature/updating-theme

Any ideas?

**Comment by garronej** [comment]
Hello @KernelFrenzy,  

Yes, this is normal.  
So you have your own fork of Keycloakify? You know you can just copy paste the Keycloakify components into your projects? It's called ejecting and it has been design so there's nothing you need to change in the component for it to work.  
However if you really want to have your fork you need to make sure the css files are copied over to the distribution directory:  

https://github.com/keycloakify/keycloakify/blob/0796b3dedfc4f1799a33621375ec9d7178fcb5a9/package.json#L16  

The build system changes completely in Keycloakify 10 though and will be released any day now.  
https://github.com/keycloakify/keycloakify/pull/538

**Comment by KernelFrenzy** [comment]
Ah, perhaps I need to go back and read through the documents.
I assumed the Keycloakify-starter was just a small app to help you get started and potentially have the code based shared with the web app. And assumed they Keycloakify repo was the complete deal.

Nice, I probably won't be close to ready for deployment, so I'll mess about with the starter and just update before the planned deployment :)

**Comment by garronej** [comment]
Yeah no, Keycloakify is distributed as an npm module.  
I'll improve the documentation to make all this clearer
