### ISSUE TITLE
`keycloakify-starter` `eslintrc` migration to flat config

### ISSUE THREAD

**Issue by meierw** [keycloakify/keycloakify#566]
Hi.

I noticed that `.eslintrc.cjs` is used in [keycloakify-starter](https://github.com/keycloakify/keycloakify-starter/tree/keycloakify_10) , even the new `v10` branch.

Currently in eslint v9 flat config is the default, [and `eslintrc` is to be removed in v10](https://eslint.org/blog/2023/10/flat-config-rollout-plans/#eslintrc-removed-in-eslint-v10.0.0).

You should consider migrating to the new `eslint.config.js` flat config, so that people don't have to do that chore when beginning work with `keycloakify-starter`.

Some useful links for migration:
- https://eslint.org/docs/latest/use/configure/migration-guide
- https://eslint.org/blog/2024/05/eslint-configuration-migrator/

**Comment by garronej** [comment]
Noted!  
I should also update the .eslint config they are some remaining non standard rules that are personal preferences but the starter should be vanilla.

**Comment by garronej** [comment]
I'll be happy to merge a PR for this but I have other things more pressing.  

Thank you for reporting it though
