### ISSUE TITLE
Customizing other keycloak default pages like email verification etc

### ISSUE THREAD

**Issue by maxtsh** [keycloakify/keycloakify#568]
Hello, thank you for your hard and awesome work on keycloakify, it is helping me a lot.

I am curious, what is the proper way of changing other default key cloak pages like email verification or the list below, do we just need to add it in the keycloak-theme folder and in the login pages or is there any specific rule here.

![image](https://github.com/keycloakify/keycloakify/assets/38842256/620d3a6e-861f-41d8-af17-74d89f73d1d4)

I looked into the documentation and found nothing helping me on this topic, would really appreciate your respond and sorry if this question is covered somewhere I could not find.

Really appreciate your hard work.

**Comment by garronej** [comment]
Hello @maxtsh, thanks for the kind words

Sorry the documentation of v10 is still under construction.  
The key command you need to run in your keycloakify project is `npx keycloakify eject-page`

rellevent doc:  
https://docs.keycloakify.dev/customization-strategies/component-level-customization  
https://docs.keycloakify.dev/faq-and-help/how-do-i-add-extra-pages
