### ISSUE TITLE
getChangeLocalUrl function name to getChangeLocaleUrl

### ISSUE THREAD

**Issue by chloeshiauisme** [keycloakify/keycloakify#569]
Hello! Thanks so much for your work to update Keycloakify, super excited!

Small nit but should `getChangeLocalUrl` [here](https://github.com/keycloakify/keycloakify/pull/538/files#diff-947013c4f08711bca40f62ddb8771ea671ed5277ae7f9df29a9669123e7d79f8R31) be `getChangeLocaleUrl`?

**Comment by garronej** [comment]
Hey @chloeshiauisme,  

Thanks a lot!  

> Small nit but should getChangeLocalUrl [here](https://github.com/keycloakify/keycloakify/pull/538/files#diff-947013c4f08711bca40f62ddb8771ea671ed5277ae7f9df29a9669123e7d79f8R31) be getChangeLocaleUrl?  

Damn it, you're wright! It's going to be a breaking change.  

Thanks for reporting!

**Comment by chloeshiauisme** [comment]
Thanks so much for the quick change!
