### ISSUE TITLE
Keycloakify Extra Fields

### ISSUE THREAD

**Issue by MuratKaragozgil** [keycloakify/keycloakify#570]
Hello awesome community :)

I have a question for you. I have a registration page, as shown in the screenshot below:

![CleanShot 2024-06-25 at 15 30 53](https://github.com/keycloakify/keycloakify/assets/8644827/392acc35-806d-49bd-872a-5c52a84c3374)

I want to add a new hidden field to this registration page. This hidden field should capture a URL parameter that is passed to the registration page. When the user clicks the “Register” button, I need this hidden field value to be included in the registration data sent to the Keycloak flow so it can be handled on the backend.

Could someone guide me on how to achieve this?

Thank you in advance for your help!

Let me know if there are any additional details you’d like to include or if you need any further modifications.

**Comment by garronej** [comment]
Hello @MuratKaragozgil,  

Sorry for the late reply.  

Have you added a custom User Attribute in your Keycloak configuration?  

What version of Keycloakify are you currently using?

**Comment by maxtsh** [comment]
Hi.

I need the same functionality, I want to have two hidden fields for ID and Role and add them inside the registration data.

I am using keycloak 25.

**Comment by garronej** [comment]
Hello @maxtsh,  

Despide all the bells and wissle that Keycloakify introduce that make the developement experience akin to a modern client side application, at the end of the day, login pages are meerly OG HTML forms.  

So you see, when you press submit it just sends a POST request to the action url specified as attribute of the <form /> element.  
As long as you have in your form, some `<input />` elements with the correct name it they will be send in the request body.  

But to make sure we are on the same page?  
Have you added User Profile Attributes via the Keycloak Admin Console like here with favourite_pet?  

<img width="2056" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/502ae517-7b62-418c-a4a8-78e100f7c46f">

<img width="1883" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/bd7ddbf9-bdb7-485b-856d-f86568f9a49e">

If you have, they should automatically appear on your register form (because present in kcContext.profile.attributesByName):  

<img width="2056" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/a5777ce8-714b-4183-91ea-147af8d3ebf3">

So the only thing left for you to do should be to hide thoses field with CSS and maybe programatically select a default.

**Comment by maxtsh** [comment]
> Hello @maxtsh,
> 
> Despide all the bells and wissle that Keycloakify introduce that make the developement experience akin to a modern client side application, at the end of the day, login pages are meerly OG HTML forms.
> 
> So you see, when you press submit it just sends a POST request to the action url specified as attribute of the
> 
> element.
> As long as you have in your form, some `<input />` elements with the correct name it they will be send in the request body.
> But to make sure we are on the same page? Have you added User Profile Attributes via the Keycloak Admin Console like here with favourite_pet?
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/6702424/347836335-502ae517-7b62-418c-a4a8-78e100f7c46f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDU0NTAsIm5iZiI6MTcyMDcwNTE1MCwicGF0aCI6Ii82NzAyNDI0LzM0NzgzNjMzNS01MDJhZTUxNy03YjYyLTQxOGMtYTRhOC03OGUxMDBmN2M0NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTMzOTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjczZDZjMWNlZDdmNmM2Zjg4N2E0ODZkNzg1YTYwZTU3ZDY3ZDE0N2YwYmY3ZDFjNzE4ZTcxZmNkYjc4YmYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4qsCaUgKzifMqG7VojU3uOpE3V_sZxv1J4_hy9EiQq4"> <img alt="image" width="1883" src="https://private-user-images.githubusercontent.com/6702424/347836430-bd7ddbf9-bdb7-485b-856d-f86568f9a49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDU0NTAsIm5iZiI6MTcyMDcwNTE1MCwicGF0aCI6Ii82NzAyNDI0LzM0NzgzNjQzMC1iZDdkZGJmOS1iZGI3LTQ4NWItODU2ZC1mODY1NjhmOWE0OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTMzOTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI4ZjJmYWM4MjUwNGVhZDZmODY1OGUzNWMzMWRjZThlZDI3NTY1MDM4MjU5YWFhNjliYjZlYWE3OTVhMWI2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G0I235hAjyJK0TUikafhinZcUhjzgeDhwTWyAbxk6IU">
> If you have, they should automatically appear on your register form (because present in kcContext.profile.attributesByName):
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/6702424/347837044-a5777ce8-714b-4183-91ea-147af8d3ebf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDU0NTAsIm5iZiI6MTcyMDcwNTE1MCwicGF0aCI6Ii82NzAyNDI0LzM0NzgzNzA0NC1hNTc3N2NlOC03MTRiLTQxODMtOTFlYS0xNDdhZjhkM2ViZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTMzOTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU4NDk0MTdlNzdmMzcwYmM2MWExMDQ2NDhiMjRmN2IwNTA4NjU3ZGQ3OGQ2NzVkOWVlOGFhZGZkNjQxOTQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CGaKZ3Dq5arOgOIq5FpPqEmsiM4ZAqpvcD0zI6g5GA0">
> So the only thing left for you to do should be to hide thoses field with CSS and maybe programatically select a default.

Thanks a lot man, it now works fine, my problem was that I was manipulating the value onSubmit event with refs in React which seems to to inject the values and you need to set the value directly to the input, anyways I really appreciate your great work here, keep it up @garronej .
