### ISSUE TITLE
Keycloakify v10 unable to test in Keycloak container

### ISSUE THREAD

**Issue by jamesdh** [keycloakify/keycloakify#576]
This is a continuation of https://github.com/keycloakify/keycloakify/pull/538#issuecomment-2203941056. I didn't want to pollute that PR any further!

When running latest starter template within Keycloak docker (e.g. npx keycloakify start-keycloak) it just spits out a blank page with the following error:

> You've modified the configuration of the Keycloak server in a way that is incompatible with[this test application](https://github.com/keycloakify/my-theme.keycloakify.dev).

...and contains the following in the console:

> [Error] Not allowed to request resource
[Error] Fetch API cannot load http://localhost:8080/realms/myrealm/.well-known/openid-configuration due to access control checks.
[Error] OIDC initialization error: Bad configuration. Timed out after 5000ms
Maybe something to look into? I couldn't see anything in the config that would cause that.

I've validated port 8080 is open and the Keycloak container is correctly binding to it. 

This is on macOS 14.5. Using yarn 1.22 since no version is specified in package.json and hence corepack uses that by default.

**Comment by garronej** [comment]
Damn this is the exact same config I'm using... 
Are you on apple Silicon?  
Can we jump on a quick call on discord to see what's up?  
https://discord.gg/mJdYJSdcm4

**Comment by garronej** [comment]
Oh wait, I can reproduce with safari

**Comment by jamesdh** [comment]
@garronej it's Safari vs Chrome 🤣 I just tried it in Chrome and it works. Safari must be more restrictive regarding CORS or redirect URL's or some such thing.

**Comment by jamesdh** [comment]
> Oh wait, I can reproduce with safari

lol..yep!

**Comment by garronej** [comment]
It's a security feature of safari. I'll try and see if I can go around it, it should work with other browsers though.  
And it goes without saying that this problem only affect the test app that redirects to your locally running keycloak test instance.

**Comment by garronej** [comment]
Damn... there's no way around it :( to make it work on safari I'll have to spin another server locally just for this test app.

**Comment by garronej** [comment]
can you confirm that it works with Chrome and Firefox?

**Comment by garronej** [comment]
Well I've updated https://github.com/keycloakify/my-theme.keycloakify.dev/ so that it display an alert when using Safari.  

<img width="1186" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/0c6ea9c6-bf47-42ea-83bb-196863d9d59b">  

It's not ideal but the Safary security policies being what they are the only workaround would be to to locally serve [keycloakify/my-theme.keycloakify.dev](https://github.com/keycloakify/my-theme.keycloakify.dev/) when running `npx keycloakify start-dev` so I'll settle with the alert at least for now.

**Comment by jamesdh** [comment]
Thanks @garronej! This seems like a good enough solution. Glad we were able to figure out the cause!

**Comment by garronej** [comment]
Thanks for helping me figure this out!
