### ISSUE TITLE
Problem with Keycloak PrivacyIDEA Provider

### ISSUE THREAD

**Issue by Nupke** [keycloakify/keycloakify#580]
We encountered a problem with the  [Keycloak PrivacyIDEA provider ]( https://github.com/privacyidea/keycloak-provider.) The library keycloakify does not support the template **privacyIDEA.ftl** because this template is not included in the list, causing issues with its processing in keycloakify.

**Steps to Reproduce:**
Use the Keycloak PrivacyIDEA provider.
Attempt to process the privacyIDEA.ftl template with keycloakify.
Expected Behavior:
The privacyIDEA.ftl template should be processed correctly by keycloakify.

**Actual Behavior:**
keycloakify fails to process the privacyIDEA.ftl template because it is not included in the supported template list.

**Comment by garronej** [comment]
Hello @Nupke,  

No issue! You can create an privacyIDEA.ftl page with Keycloakify!  
https://docs.keycloakify.dev/faq-and-help/integration-with-custom-keycloak-extention  

Don't hesitate to ask is you have questions

**Comment by deincodeverbesserer93** [comment]
@Nupke , did you have no Problem with the Form Tag for the otp method?

**Comment by deincodeverbesserer93** [comment]
Hello,
i have included the privacyIDEA.ftl successfully as privacyIDEA.tsx like your example with SMS but when i start keycloak with privacyIDEA. The default ftl from privacyIDEA shows up.

When i look into the jar file with:

`jar -xf ../keycloak-theme-for-kc-25-and-above.jar`

The privacyIDEA.ftl is not in the login-theme Folder as javascript file.

**Comment by garronej** [comment]
@deincodeverbesserer93 Show me your `src/login/KcContext.ts`

**Comment by garronej** [comment]
PS: You don't have to extract the jar, you can just run `npx keycloakify start-keycloak` and look in the `dist_keycloak/theme` directory

**Comment by deincodeverbesserer93** [comment]
To your information i use currently v10 in v9 was no problem.

This is my `src/login/kcContext.ts`

```/* eslint-disable @typescript-eslint/ban-types */
import type { ExtendKcContext } from "keycloakify/login";
import type { KcEnvName, ThemeName } from "../kc.gen";

export type KcContextExtension = {
    themeName: ThemeName;
    properties: Record<KcEnvName, string> & {};

};

export type KcContextExtensionPerPage = {
    "privacyIDEA.ftl": {
        // Your custom context here
        otpLogin: {
            userOtpCredentials: {
                id: string;
                userLabel: string;
            }[];
            selectedCredentialId?: string;
        };
    }
};

export type KcContext = ExtendKcContext<KcContextExtension, KcContextExtensionPerPage>;
```

**Comment by garronej** [comment]
Hey @deincodeverbesserer93,  

Unfrotunately, I wasn't able to reproduce... 

<img width="2056" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/0bf1b56c-41f9-4d28-b18f-08a662675a20">

What version of Keycloakify are you using? Make sure to use 10.0.0-rc.106 (the latest one)

**Comment by deincodeverbesserer93** [comment]
Hello @garronej ,
thanks for the fast help!. I used `10.0.0-rc.82` and updated to `10.0.0-rc.106`.
Now it's working.

**Comment by garronej** [comment]
Nice :)
