### ISSUE TITLE
Differences in select login method in v10-rc

### ISSUE THREAD

**Issue by TimDMorris** [keycloakify/keycloakify#582]
We're currently working with keycloakify 10.0.0-rc101 to make sure our theming will be ready for v25 keycloak.  We're in the shallow end of keycloakify and only doing theming via css but so far our experience has been great!  We are currently only seeing one template where there could be potential issues the select-authenticator.ftl.  In the keycloakify storybook our css overrides look great but in deployed keycloak in our test environments the template shows blank rows.

I'm just a front end/css guy but my backend team assure me they have checked their config and can't see anything out of place, so I thought it was worth raising this in case it is an actual template issue.

Like I say this is shallow end, we're just doing just css overrides so hard to see how it could be just the css driving this:

![select login method differences](https://github.com/keycloakify/keycloakify/assets/8735906/324c4239-ade5-4575-a4b7-642f65d1060f)

Let me know if I can add anything additional that would help clarify this.

**Comment by garronej** [comment]
Hello @TimDMorris,  

Thank you for the kind feedback.  
We're going to figure this out, if there's something to fix in Keycloakify, I'll fix it.  

Fist could you access the page on your keycloak instance, open the dev tools and type `kcContext.auth.authenticationSelections`

![image](https://github.com/keycloakify/keycloakify/assets/6702424/8e9dcb8b-a1ee-4d03-bd15-f0e5a4f8471d)

Then show me the result

**Comment by TimDMorris** [comment]
Hi @garronej thanks for the prompt reply, much appreciated!  This is what I see for kcContext.auth.authenticationSelections

If there is anything else that would be useful just let me know

<img width="994" alt="kcContext auth authenticationSelections" src="https://github.com/keycloakify/keycloakify/assets/8735906/fcfc9721-0d69-4953-8004-f8b019ba7002">

**Comment by garronej** [comment]
I'm looking into it right now.  
Since you're a customer of @xgp (PhaseTwo) you have premium support. He's been essential in some of Keycloakiy latest devloppement.  

PS: Damn ChatGPT is usefull 

<img width="1803" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/b8b19677-f016-4d76-8d8e-1459243e3991">

**Comment by xgp** [comment]
@garronej Thanks for all the help here. We're looking into this in parallel to see if we can figure it out.

Had no idea chatgpt could do that. Amazing.

**Comment by garronej** [comment]
@xgp don't worry about it, I've identified the issue, I'll release a fix in half an hour or so.

**Comment by garronej** [comment]
Hey @TimDMorris,  

If you update to Keycloakify 10.0.0-rc.107 it should be fixed!

**Comment by HarryNiotis** [comment]
Thanks @garronej!
We can now see the option textes, although they still vary from the storybook
<img width="603" alt="image" src="https://github.com/keycloakify/keycloakify/assets/23638721/d00c5b2a-1db7-4eba-980b-644205d252f6">
I assume we probably need to do some more work around this on our customization

**Comment by garronej** [comment]
Hey @HarryNiotis,  

In the storybook the mock data are different.  

The default story uses:  

`src/login/pages/SelectAuthenticator.stories.tsx`
```tsx
export const WithDifferentAuthenticationMethods: Story = {
    render: () => (
        <KcPageStory
            kcContext={{
                auth: {
                    authenticationSelections: [
                        {
                            authExecId: "f607f83c-537e-42b7-99d7-c52d459afe84",
                            displayName: "otp-display-name",
                            helpText: "otp-help-text",
                            iconCssClass: "kcAuthenticatorOTPClass"
                        },
                        {
                            authExecId: "5ed881b1-84cd-4e9b-b4d9-f329ea61a58c",
                            displayName: "webauthn-display-name",
                            helpText: "webauthn-help-text",
                            iconCssClass: "kcAuthenticatorWebAuthnClass"
                        }
                    ]
                }
            }}
        />
    )
};
```

But you can create a story for your Keycloak configuration with:  

```tsx
export const WithRealmTranslations: Story = {
    render: () => (
        <KcPageStory
            kcContext={{
                auth: {
                    authenticationSelections: [
                        {
                            authExecId: "f0c22855-eda7-4092-8565-0c22f77d2ffb",
                            displayName: "home-idp-discovery-display-name",
                            helpText: "home-idp-discovery-help-text",
                            iconCssClass: "kcAuthenticatorDefaultClass"
                        },
                        {
                            authExecId: "20456f5a-8b2b-45f3-98e0-551dcb27e3e1",
                            displayName: "identity-provider-redirctor-display-name",
                            helpText: "identity-provider-redirctor-help-text",
                            iconCssClass: "kcAuthenticatorDefaultClass"
                        },
                        {
                            authExecId: "eb435db9-474e-473a-8da7-c184fa510b96",
                            displayName: "auth-username-password-form-display-name",
                            helpText: "auth-username-password-help-text",
                            iconCssClass: "kcAuthenticatorDefaultClass"
                        }
                    ]
                },
                "x-keycloakify": {
                    messages: {
                        "home-idp-discovery-display-name": "Home identity provider",
                        "home-idp-discovery-help-text": "Sign in via your home identity provider which will be automatically determined based on your provided email address.",
                        "identity-provider-redirctor-display-name": "Identity Provider Redirector",
                        "identity-provider-redirctor-help-text": "Sign in via your identity provider.",
                        "auth-username-password-help-text": "Sign in via your username and password."
                    }
                }
            }}
        />
    )
};
```

An you'll get his:  

<img width="1568" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/e00e963b-ff56-4e1f-852c-8a1168673d5b">

The icons are expected to be the default ones since you use  `kcAuthenticatorDefaultClass` this is something you woule configure on the Keycloak server to use, for examples`kcAuthenticatorOTPClass` or `kcAuthenticatorWebAuthnClass`.  

What surprises me however is that you don't seem to get any translations from the server.  

Can you send me another screeshot of you kcContext like the previous one but makes sure to show the `x-keycloakify` values:  

<img width="2054" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/a39bdcdb-0902-46d6-a8cb-de099f14ab9f">

Thanks!

**Comment by HarryNiotis** [comment]
Thanks for the info @garronej . 

I will update the stories with the updated messages and see how it works. I thought there must have been something there.

Below is the screenshot you asked with the `x-keycloakify` struct
<img width="1541" alt="Screenshot 2024-07-12 at 09 38 03" src="https://github.com/user-attachments/assets/0f6b9667-cf92-4764-a3a4-98710493f41a">

**Comment by HarryNiotis** [comment]
This is our storybook after adding details on the `x-keyclokify` as you suggested, so that works as expected. I have removed the middle option for now, server team advised it was there by accident and they will also remove it
<img width="893" alt="image" src="https://github.com/user-attachments/assets/7f7f4021-ebde-4d29-9731-b66ca025cdaf">

**Comment by garronej** [comment]
Hi @HarryNiotis,

Thanks for the additional information. I made a mistake in the code fetching the backend internationalization message. I’ll be releasing a patch this evening to fix it.

Sorry for the inconvenience. Keycloakify 10 is still a bit rough around the edges.

**Comment by garronej** [comment]
@HarryNiotis,  

This time it should be fixed! Try keycloakify `10.0.0-rc.110`

**Comment by TimDMorris** [comment]
@garronej we have tested this morning and that looks good!  Thanks again for the prompt support and getting this resolved so quickly.

**Comment by TimDMorris** [comment]
tested with 10.0.0-rc.110 and can confirm issue appears resolved!

**Comment by HarryNiotis** [comment]
Thanks again @garronej for all the support!
