### ISSUE TITLE
Update Language in account theme not working in v10

### ISSUE THREAD

**Issue by deincodeverbesserer93** [keycloakify/keycloakify#583]
Hello, 

i use currently the keycloakify starter project with keycloakify 10.0.0-rc.106.
In the account theme the language dropown does not change the language in keycloak or translate the view.
In the login theme this works

**Comment by garronej** [comment]
Ok thank you for reporting let me check

**Comment by garronej** [comment]
It seems to work as expected.  

https://github.com/keycloakify/keycloakify/assets/6702424/03328c99-e2ae-4842-822d-1b48b4ff2246  

If you're wondering why it does not work in Storybook:  

https://docs.keycloakify.dev/i18n#stories-in-different-languages

**Comment by deincodeverbesserer93** [comment]
@garronej ,
in which keycloak version did you tested?

I have downloaded new starter-template
- in 24.0.6 works
- in 25.0.1 works not 

And a little other problem in Keycloak 25.0.1 the refresh_token is one second valid and redirects in the admin console to the login.

**Comment by garronej** [comment]
Hey @deincodeverbesserer93,  

I'm sorry but I can't reproduce:  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/keycloakify/Screen%20Recording%202024-07-10%20at%2018.40.25.mov  

It must be something specific to how you changed the code or configured your Keycloak.  
If you can come up with reproduction steps I can look it up.
