### ISSUE TITLE
Attributes Group message bundle not being loaded.

### ISSUE THREAD

**Issue by cvivieca** [keycloakify/keycloakify#585]
### I'm doing something wrong or this is the expected behavior?

If you add a new group and attach the group to a form field, it appears that the message bundle is not being created for the attribute group, but it is applied to the attributes.

![image](https://github.com/keycloakify/keycloakify/assets/22035782/1c49b12c-bd82-4e77-be00-8249a597f3c6)

I printed the result of `kcContext["x-keycloakify"].realmMessageBundleUserProfile` and looks like the problem is because user profile message bundle is loaded but not the messages for the attribute group. As you can see there notice the `${profile.attributes.favourite_pet}` is correctly mapped but not `${profile.attribute-group.test}`

![image](https://github.com/keycloakify/keycloakify/assets/22035782/c6c30168-7bd2-4ae7-86e0-30603734c8e1)

Here the group I created.

![image](https://github.com/keycloakify/keycloakify/assets/22035782/36729f13-91f1-4f6c-9898-c02818cb7996)

**Comment by garronej** [comment]
Hello @cvivieca,  
You're not doing anything wrong. This is a bug, I will fix it, thanks for reporting and sorry for the inconveignece.

**Comment by garronej** [comment]
It's fixed in keycloakify `10.0.0-rc.108`!  

Just to let know know, the translation messages are now under x-keycloakify.messages:  

<img width="464" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/c8006994-f03b-4178-8e83-36a9e95bc486">

**Comment by cvivieca** [comment]
I tested it. 

It is working properly. 

Thanks! That was fast. 🚀

![image](https://github.com/keycloakify/keycloakify/assets/22035782/a77f1ace-1adf-476a-bab1-04c569a18a37)
