### ISSUE TITLE
Command start-keycloak lists unavailable images

### ISSUE THREAD

**Issue by rgrosjean** [keycloakify/keycloakify#587]
Hi,

after the creation of the tag 24.0.6 today, it's not possible to test in the theme in Keycloak 24. A workaround is to tag version 24.0.5 as 24.0.6 locally, but it would still be great if the prompt would only list the version available for download. The "standard" tags are created by "keycloak-bot", while the extra tags (for RHBoK?) are created by the project lead. This could help to filter to get only the "good" version. Or only list the released version.

To reproduce, just run `npx keycloakify start-keycloak` and select 24.0.6. The docker image can't be downloaded

I'm using the version 10.0.0-rc.115, not sure if the problem exists in the version 9.

**Comment by rgrosjean** [comment]
ok, second workaround, you can execute `npx keycloakify start-keyclo
ak --keycloak-version 24.0.5` to target a specific version of KC

**Comment by garronej** [comment]
thanks for reprting, that needs to be fixed indeed

**Comment by garronej** [comment]
fixed now
