### ISSUE TITLE
Missing Login Actions page

### ISSUE THREAD

**Issue by ceadreak** [keycloakify/keycloakify#588]
Hi, 

The page "login actions" is missing from login pages.
Translations are in i18n files.

Is this planned in a future version of keycloakify ?

TY

**Comment by garronej** [comment]
Hello @ceadreak,  

All the default pages are implemented by Keycloakify.  
The pages you're refering to is either one of the pages listed here:  
https://storybook.keycloakify.dev/  
Or it's a page generated by a Custom Keycloak Extention and in this case you should follow this guide: https://docs.keycloakify.dev/faq-and-help/integration-with-custom-keycloak-extention  

Can you send a screenshot of the page in question?  
Can you also open the dev tool and in the JavaScript REPL type: `kcContext.pageId` and tell me what you're getting:  

<img width="2055" alt="image" src="https://github.com/user-attachments/assets/4bf0b7bf-8048-4975-b15e-f59f9a7bf11c">

**Comment by ceadreak** [comment]
Hi @garronej, 

You're right, this is the info.ftl file !
In my case I just need an email verification, so the display is a little bit different because there is only one action 

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/08b09f35-9c94-4970-b158-0ea3d0dd98fa">

Thank you for the quick answer

**Comment by nvmnghia** [comment]
Chime in a bit. In my `login-actions` page, it's `pageId` is `login-idp-link-confirm.ftl`
