### ISSUE TITLE
Login page - With Immutable Preset Username

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#590]
Hello,

I've downloaded the keycloakify-starter project and ejected the page "Login.ftl" from the login theme with the command:

`npx keycloakify eject-page`

I've done the same for the ejection of the storybook'story related to the same Login.ftl with the command:

`npx keycloakify add-story`

Running storybook in local i'm able to see the case "With Immutable Preset Username", while inspecting the storybook page in the browser i can see the #kc-username div.

<img width="1164" alt="Screenshot 2024-07-18 alle 12 22 27" src="https://github.com/user-attachments/assets/c1f865f1-71f1-4fb8-9822-e469185b9c87">

But in the ejected Login.tsx component i cannot see the above tag.

Am I missing something?  Is the Login.tsx component the one that renders the above functionality ? 

Thank you in advance

**Comment by garronej** [comment]
Hello @PietroFalcetti,  
This is in the Template that is shared across all pages.  
You must run `npx keycloakify eject-page` and select `login -> Template.tsx`
