### ISSUE TITLE
Allow fetching JARs from private maven repo

### ISSUE THREAD

**Issue by TotallyNotASecret** [keycloakify/keycloakify#591]
The build process fetches the theme and ui jars from: https://repo1.maven.org/maven2. If you are using a private maven repo and cannot access the public one, you cannot build the project. It would be nice to be able to specify a private repo in the packages.json or vite config keycloakify options.

**Comment by garronej** [comment]
Hello @TotallyNotASecret,  

There is a solution for restricted network environement, you can restore the cache using the `XDG_CACHE_HOME ` environement variable:  

https://docs.keycloakify.dev/build-options/xdg_cache_home  

You can create a backup of the `node_modules/.cache/keycloakify/` directory generated from a machine that has network access.  

Let me know if you need futher guidance.
