### ISSUE TITLE
KcContext doesn't include social element on Registration (even though it exists)

### ISSUE THREAD

**Issue by magnayn** [keycloakify/keycloakify#592]
I have modified the registration.ftl template to include links to social providers (google) that I use, so the customer can decide whether to type in email/password or use their social provider.

The KcContext does not have the 'social' element defined - but it _does_ exist, since the following works as expected:

```
export type Social = {

    displayInfo: boolean;
    providers?: {
        loginUrl: string;
        alias: string;
        providerId: string;
        displayName: string;
        iconClasses?: string;
    }[];
};

...

 const social:Social = (kcContext as any).social;
```

I don't know the Keycloakify codebase to make the change, but it feels like it ought to be relatively simple ?

**Comment by garronej** [comment]
Hello @magnayn,  

For the time being the policy is to include in the KcContext type definition only the values that are used by the builtin pages.  
However the KcContext type can easily be extended to fit your usecase:  

![image](https://github.com/user-attachments/assets/1a7ee86b-b881-494c-891c-9e63f9c073df)

![image](https://github.com/user-attachments/assets/c142cae5-05d0-45d5-97ff-b93dee4fc2d6)

**Comment by garronej** [comment]
Yes you are right, thanks for the feedback!

**Comment by garronej** [comment]
I've created a documentation page: https://docs.keycloakify.dev/faq-and-help/some-values-you-need-are-missing-from-in-kccontext
