### ISSUE TITLE
Localization is not taken into consideration in the inputTypePlaceholder annotation

### ISSUE THREAD

**Issue by ayoam** [keycloakify/keycloakify#594]
![image](https://github.com/user-attachments/assets/2a5fcaf9-8448-47b5-975a-41b8c155674c)

i'm trying to add register page form placeholders from keycloak server , i added i18n key in the placeholder annotation like mentioned in keycloak docs , but the input placeholder shows the key itself not the value .
the i18n localization key is defined in the i18n.ts file .

![image](https://github.com/user-attachments/assets/176fd85f-8fd7-44e3-8421-915fb5ccfc77)

![image](https://github.com/user-attachments/assets/fc364db2-e25c-41b6-9f97-fb69c6303113)

i fixed the problem by using i18n advancedMsgStr() in the placeholder value

```
placeholder={i18n.advancedMsgStr(attribute.annotations.inputTypePlaceholder ?? "")}
```

 
![image](https://github.com/user-attachments/assets/f8ba4f60-a95a-4e1d-a7d7-46038d31e584)

**Comment by garronej** [comment]
Hello @ayoam, good catch!  

Thanks for reporting that was the correct fix indeed. I released a new version.
