### ISSUE TITLE
Account template wrong active check for `federatedIdentity`

### ISSUE THREAD

**Issue by nmathew98** [keycloakify/keycloakify#597]
The active check for the federated identity sidebar item checks if `active === 'social'` but in Storybook `active` has the value of `federatedIdentity`

https://github.com/keycloakify/keycloakify/blob/main/src/account/Template.tsx#L98

<img width="1137" alt="image" src="https://github.com/user-attachments/assets/eace6362-6334-469c-bc26-1dd73eeb11f9">

**Comment by garronej** [comment]
Thanks for reporting!!  I're released a version with the fix `@10.0.0-rc.120`.  

Be aware that there's been a breaking change in 118:  

<img width="1297" alt="image" src="https://github.com/user-attachments/assets/95950a13-d9ea-4c7b-bd3f-e41f9da84369">

**Comment by nmathew98** [comment]
noted, thanks very much for all ur hard work! the project's great!
