### ISSUE TITLE
Apache Maven required. Install it with `sudo apt-get install mvn`

### ISSUE THREAD

**Issue by brill3000** [keycloakify/keycloakify#598]
I already have maven in my command line. I have been trying to build the theme on the tailwind branch but cannot seem to go past this stage. Do I need to point keycloak to my maven dir ?
Here is my package.json showing the version.
{
    "name": "keycloakify-starter",
    "version": "0.0.0",
    "description": "Starter for Keycloakify 10",
    "repository": {
        "type": "git",
        "url": "git://github.com/codegouvfr/keycloakify-starter.git"
    },
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "tsc && vite build",
        "build-keycloak-theme": "npm run build && keycloakify build",
        "storybook": "storybook dev -p 6006",
        "format": "prettier . --write"
    },
    "license": "MIT",
    "keywords": [],
    "dependencies": {
        "autoprefixer": "^10.4.19",
        "keycloakify": "10.0.0-rc.115",
        "mvn": "^3.5.0",
        "postcss": "^8.4.39",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "tailwindcss": "^3.4.4"
    },
    "devDependencies": {
        "@storybook/react": "^8.1.10",
        "@storybook/react-vite": "^8.1.10",
        "@types/react": "^18.2.43",
        "@types/react-dom": "^18.2.17",
        "@typescript-eslint/eslint-plugin": "^6.14.0",
        "@typescript-eslint/parser": "^6.14.0",
        "@vitejs/plugin-react": "^4.2.1",
        "eslint": "^8.55.0",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-react-refresh": "^0.4.5",
        "eslint-plugin-storybook": "^0.8.0",
        "prettier": "3.3.1",
        "storybook": "^8.1.10",
        "typescript": "^5.2.2",
        "vite": "^5.0.8"
    },
    "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}

![maven-required](https://github.com/user-attachments/assets/dc8d95fa-c688-4cc0-8d5e-f4c7fcdaf44a)
![maven](https://github.com/user-attachments/assets/e05502fd-01b8-4f97-ba90-e7217342a661)

**Comment by garronej** [comment]
Hello @brill3000,  

It's strange, is seems like mvn is not in the `PATH` defined as environement variable when running `yarn build-keycloak-theme`...  

Can you add a script:  

`package.json`
```json
"scripts": {
    "test-mvn": "node ./test-mvn.js"
}
```

And create a `test-mv.js` file
```js
const child_process = require("child_process");

console.log(process.env.PATH);

const out = child_process.execSync("mvn --version").toString("utf8");

console.log(out);
```

And run `yarn test-mvn` 

Show me what you're getting

**Comment by grbick** [comment]
I had the same issue. I ran your script and realized there's an extra "mvn" package inside of node_modules. Once I deleted it, the script ran as it was supposed to.
Hope this helps.

**Comment by garronej** [comment]
Ah yeah make sense!  
I thought I included in my answer to remove this package but I didn't 😕
I'm going to put a more insightful message.

**Comment by garronej** [comment]
With the latest keycloak version you'll get this message if you have the nvm package inst
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/7f28fef1-63f3-4126-a0b0-089fdfb23373">
