### ISSUE TITLE
Using Password policies in account/password.ftl page

### ISSUE THREAD

**Issue by ayoam** [keycloakify/keycloakify#600]
Hello, can passwordPolicies be used in the account/password.ftl page ? i want to use it for frontend password validation .
i extended kcContext but passwordPolicies is always undefined .
i see that the account theme is not included in the **keycloak-theme-additional-info-extension** package .

**Comment by garronej** [comment]
Hello @ayoam,  

Ahh yeah :(  
I just realize the issue now.  
We should add the password policies to the kcContext in the password.ftl page of the Multi-Page Account :/  

However as of today the update password page have been offically moved from the account to the login theme by the keycloak team.  

And the good thing is that on this page you have the password policies provided in the kcContext:  

![image](https://github.com/user-attachments/assets/6de0f904-afa9-4ccc-b0d3-88c07f1e80d0)

So the best solution I can offer you as of today is to add a button in your account theme that redirects to your login theme.  

I've done it with [oidc-spa](https://www.oidc-spa.dev/) on the following branch for you: 

https://github.com/keycloakify/keycloakify-starter/tree/account_api_poc  

Here is the relevent commit:  

https://github.com/keycloakify/keycloakify-starter/commit/acc429422d78105aa4a438945b579fa5e1f4fd2c

**Comment by ayoam** [comment]
Hello @garronej , Thank you for the solution .
