### ISSUE TITLE
Relative BASE_URL is not supported

### ISSUE THREAD

**Issue by TotallyNotASecret** [keycloakify/keycloakify#602]
Currently using Keycloakify version 10.0.0-rc.116.

When trying to build with `base: "./"` in vite config, the keycloakify build returns the error:

> error during build:
Error: BASE_URL=./ is not supported By Keycloakify. Use an absolute path instead.
If this is a problem, please open an issue at https://github.com/keycloakify/keycloakify/issues/new

This is a problem because I need to support IE 11 with this theme. This is theoretically possible using the `@vitejs/plugin-legacy`, but after the build trying to load the login page the following error is thrown:

> Unhandled promise rejection Error: https://{myserver}/assets/index-legacy-Boc43ur1.js, (SystemJS https://github.com/systemjs/systemjs/blob/main/docs/errors.md#3)

This is happening because in the DOM there is this element:
```
<script id="vite-legacy-entry" crossorigin="" nomodule="" data-src="/assets/index-legacy-Boc43ur1.js">
  System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))
</script>
```

This causes IE 11 to try and load the file from https://{myserver}/assets/index-legacy-Boc43ur1.js, but it obviously does not exist there.
Using the base option should allow the file to load from the correct location.
I appreciate adding support for this option or any other help that would allow me to solve this problem and support IE 11 with Keycloakify.

**Comment by garronej** [comment]
Hello @TotallyNotASecret,  

Sorry this slipped through. I'm going to have a look at it to see if I can do something.

**Comment by garronej** [comment]
@TotallyNotASecret So, it's more complicated than this.  
Replacing `data-src="/assets/index-legacy-Boc43ur1.js"` by `data-src="./assets/index-legacy-Boc43ur1.js"` wouldn't solve the issue.  
It would try to download the file from  
`https://{myserver}/auth/realms/sspcloud/protocol/openid-connect/auth/assets/index-legacy-Boc43ur1.js` when in reality the file is here:  
`https://{myserver}/auth/resources/{aDynamicalHash}/login/onyxia/dist/assets/index-legacy-Boc43ur1.js`

The dynamical hash is not knoable ahead of time. It's provided to the FreeMarker context when rendering the page.   

Anyway. I've updated the bundler in `keycloakify@10.0.0-rc.126` it should work now.  

In order to update to the latest version you have  to apply thoses changes:  

`vite.config.ts`
```diff
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        keycloakify({
+           accountThemeImplementation: "Multi-Page" // or "none" if you have removed the account theme
        })
    ]
});
```

And if you have specifying version targets:  
```diff
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react(), keycloakify({
        accountThemeImplementation: "none", 
        keycloakVersionTargets: {
-           hasAccountTheme: true,
            // ...
        }
    })]
});
```  

You `src/main.tsx` must be updated as well refer to:  https://github.com/keycloakify/keycloakify-starter/blob/main/src/main.tsx  

Let me know if everything works.  

Best

**Comment by TotallyNotASecret** [comment]
It is working now, thank you for the help!!

I still needed to add a lot of polyfills until I got it to work, so I will list them if anyone else ends up here (or for the documentation):

add `events-polyfill` and `element-polyfill` as dev dependencies, and the vite legacy plugin options are:

```
plugins: [
  legacy({
    targets: ["ie >= 11"],
    additionalLegacyPolyfills: ["regenerator-runtime/runtime", "events-polyfill", "element-polyfill"],
    polyfills: [
      "es/symbol",
      "es/object",
      "es/function",
      "es/parse-int",
      "es/parse-float",
      "es/number",
      "es/math",
      "es/string",
      "es/date",
      "es/array",
      "es/regexp",
      "es/map",
      "es/set",
    ]
  })
]
```

I am not sure all of the polyfills are required, but I needed enough of them that I just added all of them.

**Comment by garronej** [comment]
Yeah, thank you very much for sharing!  

And note for pepole I've tried the default theme on IE11 (Without keycloakify) and it's very broken...

**Comment by garronej** [comment]
@TotallyNotASecret If you have more insight please put them here! I'll create a documentation page for IE11 if you get it working

Thanks for your help

**Comment by TotallyNotASecret** [comment]
I don't know about the default Keycloak theme because I didn't try it, But for my theme the configuration above worked and I'm pretty sure it would also work for the default Keycloakify pages. Anyone creating their own theme with Keycloakify would need to add all required polyfills to the additionalLegacyPolyfills parameters of the vite legacy plugin.

**Comment by garronej** [comment]
@TotallyNotASecret Thanks that's good to know!  

However by "default Keycloak theme" I was refering to the theme that comes builtin with Keycloak. Not the default Keycloakify theme.  

It looks like this out of the box:  

<img width="2055" alt="image" src="https://github.com/user-attachments/assets/c51d76d4-db3b-4734-860f-5cf24c7babb8">
