### ISSUE TITLE
Customizing Terms.tsx does not work

### ISSUE THREAD

**Issue by leonardbiofi** [keycloakify/keycloakify#604]
Hi,

After I have ejected the terms.tfl using the command `npx keycloakify eject-page` I have a new file Terms.tsx created in the login/pages/Terms.tsx location. Everything if fine. However I cannot see the modification to the page at all... even commenting all the html code in the Terms.tsx or addind any sort of <p> tag or <div> does not reflect any change on the page at all.. 

I am missing something ? It seems that keycloak is loading that page from somewhere else and whatever changes I bring to the page nothing happens...
I customized the login page and everything seems to be working fine but about the terms nothing happens.

HELP!!!

**Comment by garronej** [comment]
Hello @leonardbiofi,  

Yeah you probably missed the step where you have to actually import the component.  

<img width="841" alt="image" src="https://github.com/user-attachments/assets/9ee6e3fb-707d-433c-8134-cc4832e44c24">

**Comment by leonardbiofi** [comment]
I did but everytime I restart the dev server with the command `keycloakify start-keycloak -p apps/keycloak-theme` to test my modification the file gets overwritten. This file is autogenerated by keycloakify that's why I was not modifying it because it gets overwritten everytime. 

How Am I suppose to test my new layout if the file get overwritten at every server restart ? I need to run the full cloakify server because I would like to update he "termsText" variable on the admin UI of keycloak so I can see my text coming back to the terms and condition page. Otherwise I cannot customize anything. 

Let me know whether or not there is another way to make this work

**Comment by leonardbiofi** [comment]
My bad !!! I was modifying the wrong file !! Thank you very much for your help. All good now !

**Comment by garronej** [comment]
Great!
