### ISSUE TITLE
Access Custom Realm attributes

### ISSUE THREAD

**Issue by PManaras** [keycloakify/keycloakify#624]
Hi everyone,
i am trying to port my theme to keycloakify, but i can't figure out, how to access realm attributes. In FTL i could access the corresponding attribute via `${realm.attributes.myAttribute}`. I tried to accomplish this by following the documentation [here](https://docs.keycloakify.dev/faq-and-help/some-values-you-need-are-missing-from-in-kccontext).

Can someone point me in the right direction, IF this is even possible?

**Comment by garronej** [comment]
Hello @PManaras,  

Yes it's possible, can you tell me the names of the properties your want to access on the realm.attributes object?

**Comment by PManaras** [comment]
Hi @garronej,
the realm attributes are, e.g. **realm.attributes.imprint** and **realm.attributes.portalLink** besides some other attributes to accomplish a somewhat dynamic theme for different realms.
That's why i am looking for a way to access the realm attributes in keycloakify, without the need to change my custom forms provider code, which will break things when migrating to a keycloakify based theme.

I also had a look at the login.ftl and it seems that the realmAttributes are "redacted" from the json response of the backend.

**Comment by garronej** [comment]
Hello @PManaras,  

I recorded a video just for you 😊 

https://www.youtube.com/watch?v=WdSPrpFObhg  

Here is the documentation page:  

https://docs.keycloakify.dev/taking-ownership-of-the-script-responsible-for-generating-the-kccontext

**Comment by PManaras** [comment]
Thanks a lot! it works!

cheers!

**Comment by garronej** [comment]
> to accomplish a somewhat dynamic theme for different realms.  

This is a very valid usecase, maybe I shouldn't exclude the realm attributes by default then.  
Or maybe only includes the custom ones...?  

What are you thoughs on the matter?

**Comment by PManaras** [comment]
it definitely makes sense to include some realm attributes. Since it's also a valid point not to include all of the properties of the realm, removing certain internal information is also important. So i tried the following:

I have removed the part which skips the realmAttributes as shown in the video and did something like this, to only allow specified attributes to be added:

 `<#if (key == "realmAttributes")>
  <#assign localAttributes = object[key]>
  <#assign allowedKeys = ['cibaBackchannelTokenDeliveryMode'] >
  <#assign newAttributes = {}>
  <#list localAttributes?keys as localAttributeKey>
      <#if allowedKeys?seq_contains(localAttributeKey)>
          <#assign newAttributes = newAttributes + { localAttributeKey : localAttributes[localAttributeKey]}>
      </#if>
  </#list>
  <#local recOut = toJsDeclarationString(newAttributes, path + [ key ])>
  <#local outSeq += ['"' + key + '": ' + recOut + ","]>
  <#continue>
</#if>`

this example allows only attributes specified in allowedKeys. It works fine when starting the embedded keycloak. in reality i think its easier to exclude the information via the LoginFormsProvider. In my setup, i have a custom one myself, anyways.

**Comment by garronej** [comment]
I'm glad that you have a solution that works for you.  

What would be a good default for the project according to you?  

Excluding all known realm attributes values and forwarding all the custom ones?

**Comment by PManaras** [comment]
Only allowing custom ones would be the safest. The realm that is created for testing contains these values:

`{
    "cibaBackchannelTokenDeliveryMode": "poll",
    "cibaExpiresIn": "120",
    "cibaAuthRequestedUserHint": "login_hint",
    "oauth2DeviceCodeLifespan": "600",
    "clientOfflineSessionMaxLifespan": "0",
    "oauth2DevicePollingInterval": "5",
    "clientSessionIdleTimeout": "0",
    "parRequestUriLifespan": "60",
    "clientSessionMaxLifespan": "0",
    "clientOfflineSessionIdleTimeout": "0",
    "cibaInterval": "5",
    "realmReusableOtpCode": "false"
  }`

Exposing these is not a threat in my opinion, but you can't be sure, if there won't be potential sensitive information in there in the future.

**Comment by garronej** [comment]
You're right.  

I've updated the documentation:  

https://docs.keycloakify.dev/taking-ownership-of-the-kccontext  

I was considering adding a specific option for declaring the user attributes that should be forwarded but then I realized that the Keycloak team actually discourage the usage of custom realm attributes and there's no pages in the Keycloak Account Console to edit them so I figured that I'll just leave it at that:  

PS: I think you could have a simple modification of the freemarker templat just by doing:  

```diff
-    ) || (
-        key == "attributes" &&
-        areSamePath(path, ["realm"])
-    ) || (
+    ) || (
+        areSamePath(path, ["realm", "attributes"]) &&
+        !["cibaBackchannelTokenDeliveryMode"]?seq_contains(key)
+    ) || (
```
