### ISSUE TITLE
Module '"keycloakify/login"' has no exported member 'createGetKcContext' in Keycloakify 10.0.3

### ISSUE THREAD

**Issue by PrzemyslawPolrolniczak** [keycloakify/keycloakify#626]
Hi,

recently we've been trying to bump keycloakify version from `9.1.4` to `10.0.3` and we've encountered two issues:

1. `Module '"keycloakify/login"' has no exported member 'createGetKcContext' ` and in fact after checking out lib files I don't see that export anymore, however it's absence is not mentioned in migration guide
![Screenshot 2024-08-28 at 16 46 27](https://github.com/user-attachments/assets/4e52cfaf-7b5b-481d-a1a9-fe39bf7e57e7)

2. We cannot import `KcContext` type because there seems to be casing issue.
![Screenshot 2024-08-28 at 16 31 06](https://github.com/user-attachments/assets/c84d54d3-87fb-4c76-a35f-47ed91e28dd9)
Funny, that for `account`, import statement is exact the same as it was before (notice `kcContext` starting with lowercase)
![Screenshot 2024-08-28 at 16 41 03](https://github.com/user-attachments/assets/f8f864a3-968d-4b80-b16f-a18dcc311dc4).
 I've fixed that by changing casing in application components, however I wanted to let you know as this is undocumented change (at least in migration guide)

while 2nd issue is easily fixable, the first one we don't know how to tackle, any ideas?

**Comment by garronej** [comment]
Hello @PrzemyslawPolrolniczak,  

I'm sorry to have to inform you that updating form v9 to v10 isn't as easy as bumping the package version number 😞   

https://docs.keycloakify.dev/faq-and-help/migration-guides/v9-greater-than-v10
