### ISSUE TITLE
Cannot use Keycloakify in Keycloak version 20

### ISSUE THREAD

**Issue by snguyen51** [keycloakify/keycloakify#628]
I got the error " Cannot read properties of undefined (reading 'endsWith')" when running with Keycloak version 20.0.0. After debugging, I notice the code expects the serverBaseUrl in KcContextLike. However, the environment variables do not contain that property. I spent a whole week just to find out the issue. Not sure if you can help but Thanks.

TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Array.<anonymous> (6960.65883c7d.chunk.js:1:3367)
    at Array.map (<anonymous>)
    at o (joinPath.ts:9:12)
    at 2967 (i18n.ts:30:15)

**Comment by garronej** [comment]
Hello @snguyen51,  

Sorry about the issue.  
Can you give me a little more context?  
What version of Keycloakify are your using?  
What bundler are you using? Vite or Webpack?  
For what kind of theme does this happen? The Account SPA theme? The Login theme?  

If it's the Single Page account theme [the is no backward compatiblity prior Keycloak 25](https://docs.keycloakify.dev/account-theme). We can maybe look if there's a way but it might be a dead end.  

If it's any other thing I'll be able to help.

**Comment by garronej** [comment]
Yeah I guess you're experiencing the issue with the account SPA, I'll try and see if I can make a retrocompatibility patch, it's just for the base url it shouldn't be an issue but there might be more problem down the line. The Keycloak account UI was released in keycloak 25.

**Comment by snguyen51** [comment]
Thank you for quick response.

I want to customize the theme for the single-page account. I followed all the steps in the document. I could run the command npx keycloakify start-keycloak and chose Keycloak version 25. When I ran with  npx keycloakify start-keycloak --keycloak-version 20.0.0 I got the above error.

**Comment by garronej** [comment]
I added a retro compatiblity patch for making the account theme SPA works with keycloak 20, 22, 23 and 24.  
21 it requires some extra work but I'm not sure it's worth the time to make it work so I'll wait until pepole request support for it.  

You can update to the latest version: https://github.com/keycloakify/keycloak-account-ui?tab=readme-ov-file#installation

**Comment by snguyen51** [comment]
Thank you so much! You're the best!

**Comment by garronej** [comment]
@snguyen51,  

Please put your error here and add the presise steps to reproduce.  (Where should I click in the ui?)

**Comment by snguyen51** [comment]
After updating to the latest code, the SPA Account is loaded. All the
account pages work except for Personal Info. I got the error

Failed to load resource: the server responded with a status of 404
(Not Found)Understand this error
protocol/openid-connect/3p-cookies/step1.html:1 An iframe which has
both allow-scripts and allow-same-origin for its sandbox attribute can
escape its sandboxing.Understand this warning
login-status-iframe.html:1 An iframe which has both allow-scripts and
allow-same-origin for its sandbox attribute can escape its
sandboxing.Understand this warning
Header.tsx:42 Header
account/supportedLocales:1


       Failed to load resource: the server responded with a status of
404 (Not Found)Understand this error
parse-response.ts:19 Uncaught (in promise) s: RESTEASY003210: Could
not find resource for full path:
http://localhost:8080/realms/myrealm/account/supportedLocales
    at r (http://localhost:8080/resources/ua1vz/account/keycloakify-starter/dist/static/js/9534.423e32e9.chunk.js:1:2472)
    at async Promise.all (index 1)
    at async http://localhost:8080/resources/ua1vz/account/keycloakify-starter/dist/static/js/2960.c01b072a.chunk.js:2:161962Understand
this error

STR:

1. Start the command npx keycloakify start-keycloak —keycloak-version 20.0.0
2. Navigate to the my theme url as suggested in the console and login with
testuser account.
3. The Personal Info account page was loaded with a spinning icon and
nothing else. Observe the above error in the console. The other pages like
Applications work with no errors.

**Comment by garronej** [comment]
> 1. Start the command npx keycloakify start-keycloak —keycloak-version 20.0.0  

Never use the very first major, it's pretty much always broken with a patch coming a few hours later.   
Manually select 20.0 when asked or go to https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest and see the latest v20 release.

**Comment by garronej** [comment]
Ok I can reproduce, I'll se what I can do, yesterday it was working

**Comment by snguyen51** [comment]
Thanks a lot for your time. I’ll work with Multi-page for now. Hopefully I
don’t have to re-work on css 😀

**Comment by garronej** [comment]
No wait I'll ship support for Single-Page.  

The multi page is completely differents from the single page and has its own set of gotchas

**Comment by snguyen51** [comment]
Ok, thanks.

**Comment by snguyen51** [comment]
@garronej, is there any update on the issue? Could you please point me to where I should look so I may fix it? Thank you.

**Comment by garronej** [comment]
I'll be working on it now. Sorry I didn't had the time earlyer

**Comment by garronej** [comment]
It's a bit harder than I anticipated but I'm getting there

**Comment by snguyen51** [comment]
Awesome, thanks for the update!

**Comment by garronej** [comment]
Hey @snguyen51,  

It's done.  
You can't imagine the number of tricks I had to deploy to make this work.  

I've recoded a video to demo the feature:  

https://youtu.be/HWiWHpF5mY0

**Comment by snguyen51** [comment]
Thank you for the hard work and the time. You don’t know how much you help me! Thanks On Aug 31, 2024, at 2:11 PM, Joseph Garrone ***@***.***> wrote:﻿
Hey @snguyen51,
It's done.
You can't imagine the number of tricks I had to deploy to make this work.
I've recoded a video to demo the feature:
https://youtu.be/HWiWHpF5mY0
