### ISSUE TITLE
Is it possible to use the Keycloakify theme as the default Keycloak theme?

### ISSUE THREAD

**Issue by mzbrandl** [keycloakify/keycloakify#633]
Hi, I have added Keycloakify to the docker build process of my Keycloak image. Instead of manually setting the theme in my realm settings, I would like to have it enabled globally using the KC_SPI_THEME_DEFAULT="my-theme" environment variable. When I do so and open the welcome page it displays the text "Theme is null" and the logs show this:
```
ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-1) Failed to find WELCOME theme my-theme, using built-in themes
ERROR [org.keycloak.quarkus.runtime.services.resources.QuarkusWelcomeResource] (executor-thread-1) Theme is null please check the "--spi-theme-default" parameter
```
I do not need to customize the welcome theme, so it would be ok if it just falls back to the default theme in this case. I also tried to activate just the login theme with `KC_SPI_THEME_LOGIN_THEME=my-theme` but it did not get applied. Could it be about the theme being included as a jar in providers and not directly in the `/opt/keycloak/themes/` dir?

Anyways I'd be happy about any input in that matter, thanks!

**Comment by garronej** [comment]
Hello @mzbrandl,  

I though the Welcome page had been removed in recent version of Keycloak?  

I didn't know about thoses environement variables existence. I'll have to look into it.  
I though the way to enable a theme "by default" would be to provide a realm configuration json like in this screen:  

<img width="1523" alt="image" src="https://github.com/user-attachments/assets/da94189f-ab37-4de7-b385-03a9acdf9122">  

Let me know if you have more success in your trials

**Comment by garronej** [comment]
Hey I'll cose this since I haven't much to add but if you have any aditional insight to add it will benefit the comunity!

**Comment by mzbrandl** [comment]
Hi, I went with specifying the theme in the realm.json. I think it is a fine approach.
