### ISSUE TITLE
Set selected language based on Browser language

### ISSUE THREAD

**Issue by MuratKaragozgil** [keycloakify/keycloakify#636]
Hello guys, i have a question for you,

I want to open Register, Login etc. pages based on browser language, if customer access the website first time and internalization enabled and the customer's browser language support, this one should be selected automatically. Otherwise it can use the default language from keycloak interface. 

Is there a settings for it or any workaround way ?

Thank you,
Murat

**Comment by garronej** [comment]
Hello @MuratKaragozgil,  

The user never access the login pages "directly".  
It's always redirected to the login pages by an app that implement an oidc client such as [oidc-spa](https://oidc-spa.dev).  
When you redirect your user you can add the query parameter `ui_locales=fr` for example to the url and the language will be set to french.  

If there is no ui_locales specified, I'm not sure what the behavior is but I think, at least in recent version of keycloak that the page will be in the language that is pecified, if any in the the header of the get request. (E.g: Accept-Language: en-US;en)

**Comment by MuratKaragozgil** [comment]
Ah okay make sense, thank you.

**Comment by garronej** [comment]
Let me know if you need some aditional info
