### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#637]
Hello everyone,
I'm getting the following error while building my keycloak theme with keycloakify:

`
🔏 Building the keycloak theme...⌚
/Users/pietro.falcetti/Developer/Quadra/Quadra-FE/node_modules/.pnpm/keycloakify@9.3.1_@types+react@18.0.9_react@18.1.0/node_modules/keycloakify/bin/keycloakify/generateFtl/generateFtl.js:69
    var $ = cheerio_1.default.load(indexHtmlCode);
                              ^
TypeError: Cannot read properties of undefined (reading 'load')`

I'm using:

`"react": "18.1.0",
"keycloakify": "^9.3.1",`

any help on this ? 

thank you

**Comment by garronej** [comment]
Hello @PietroFalcetti,  

It has been fixed in the latest v9 version [9.7.3](https://www.npmjs.com/package/keycloakify/v/9.7.3)
