### ISSUE TITLE
authChecker.js doesn't work in Keycloak v25

### ISSUE THREAD

**Issue by yinrouni** [keycloakify/keycloakify#638]
Hi, I'm reaching out for a problem about login in multiple browser tabs. 

When a user is authenticated in a browser tab, other browser tabs should authenticated the user automatically. So in base Keycloak theme, `authChecker.js` is added to check the state of authentication every 2 seconds. 

In a Keycloakify theme, there is `authChecker.js`, but it doesn't work in Keycloak v25. 

And I noticed that the cookie `KC_AUTH_STATE` was removed in [Keycloak v25](https://www.keycloak.org/docs/25.0.2/release_notes/#removing-kc_auth_state-cookie). 
![image](https://github.com/user-attachments/assets/1bb18342-9d78-4d97-b846-2efd5e7e174f)

 `authChecker.js` should be updated to [this](https://github.com/keycloak/keycloak/blob/25.0.0/themes/src/main/resources/theme/base/login/resources/js/authChecker.js) for Keycloak v25.

**Comment by garronej** [comment]
Hello @yinrouni,  

Thanks for investigating and reporting this.  

I'll fix it. It's not as easy as updating the script used since I have to make sure that it does not break older versions of Keycloak.

**Comment by garronej** [comment]
Sorry it's taking longer than anticipated but I'm working on it

**Comment by garronej** [comment]
It will be fixed when this PR gets merged #632

**Comment by garronej** [comment]
Should be fixed now in Keycloakify 10.1.0 let me know if there is any issue

**Comment by garronej** [comment]
It was still broken but it should be good now in 10.1.4
