### ISSUE TITLE
LoginResetPassword.tsx is missing

### ISSUE THREAD

**Issue by Darfito** [keycloakify/keycloakify#641]
Hi!, I would like to ask how I can customise the LoginResetPassword.tsx page because it is not available in version 6.0.3 and I have searched for it in other v6 versions as well. Please help me and guide me how to customise the LoginResetPassword.tsx page.

Thxx!

**Comment by garronej** [comment]
Hello @Darfito,  

Keycloakify v6 is very old.  
I encourage you to update to v10.  
If you can't you can manaully add support for it, look at the MyExtraPages examples.  

https://github.com/keycloakify/keycloakify-starter/blob/3a3b112d01ef286f3e6763ea9c12d5d22a29ab4b/src/keycloak-theme/login/pages/MyExtraPage1.tsx

**Comment by Darfito** [comment]
ok thank youu for your answer, but can you give me a refrence for the LoginResetPassword.tsx because i want to see the <form> and how the submit work

**Comment by garronej** [comment]
Here: https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/LoginResetPassword.tsx  

I understand that you're probably a freelance and wand to get over with this as soon as possible however you should let your client know that their theme isn't compatible with Keycloak 24, 25 and 26 if they do not update to the latest version of Keycloakify.  
It's probably a bad call to keep updating a theme based on Keycloakify v6

**Comment by Darfito** [comment]
ok thx for your answer
