### ISSUE TITLE
Build customization

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#644]
Hi there,
I noticed that once the theme is built and deployed into the keycloak instance, when inspecting my web page, I can see the code of my theme as if it is not minified.
In attachment you can see an example: "Quadra-FE-keycloakify-theme" is the name of my theme and as you can see, the whole code is available.

<img width="1436" alt="Screenshot 2024-09-10 alle 15 11 20" src="https://github.com/user-attachments/assets/b8c915ce-a147-4342-8527-6ff9b352d1cf">

Also the comments I put in my code are available to see:

<img width="1440" alt="Screenshot 2024-09-10 alle 15 13 44" src="https://github.com/user-attachments/assets/85e4a7fd-9beb-4a82-8f32-f01a17b3aaf2">

I'm using keycloakify ^9.7.4.
Is there a way to tell the builder to minify the code and remove comments ? 

Thank you,
Pietro

**Comment by garronej** [comment]
Well you're either using Vite or Webpack.  

If you don't have a vite config this means that you are using webpack, specifically create-react-app.  

So here:  https://github.com/keycloakify/keycloakify-starter-webpack/blob/6575789cb197cf0052d2568fca438b993ef7fd4b/package.json#L15-L16  

You want to use `"build": "GENERATE_SOURCEMAP=false react-scripts build",`

**Comment by PietroFalcetti** [comment]
Hello,
Thank you for the explanation. I have been able to fix my problem.

I'm bothering you again with another question ... 
while inspecting the minified file, I noticed the presence of a "totpSecret" key and "totpSecretEncoded" ... I see those related to the "login-configg-totp.ftl" page, which I'm not using in my customization ...

Is there a way to remove those ?
Ty

**Comment by garronej** [comment]
Thoses are mock data that where included in the build.  
You can remove thoses by upgrading to Keycloakifty 10: https://docs.keycloakify.dev/faq-and-help/migration-guides/v9-greater-than-v10  

You'll need to do it eventually if you want to update to Keycloak version later than 24.

**Comment by PietroFalcetti** [comment]
Thank you for you help!

At the moment we are still evaluating if upgrading to V10, but probably we'll do.
