### ISSUE TITLE
https://storybook.keycloakify.dev/ is all blank pages

### ISSUE THREAD

**Issue by laduke** [keycloakify/keycloakify#645]
Hi there, 
I went here https://storybook.keycloakify.dev/ and clicked on a handful of the stories in 3 different browsers and an incognito window and nothing shows. 

<img width="738" alt="Screenshot 2024-09-10 at 8 52 09 AM" src="https://github.com/user-attachments/assets/0c66ae05-f54d-46cb-b67f-b34e021297b9">

a few resources are 404'ing. I don't know if that's the issue. 

<img width="895" alt="Screenshot 2024-09-10 at 8 54 49 AM" src="https://github.com/user-attachments/assets/1823356b-e1e7-40c9-9906-0e763353a231">

**Comment by garronej** [comment]
thank you for reporting! Let's see...

**Comment by garronej** [comment]
Fixed thanks for reporting
