### ISSUE TITLE
Attribute name are not translated in error messages

### ISSUE THREAD

**Issue by rgrosjean** [keycloakify/keycloakify#648]
Hi there,

I'm currently using the multi-page variant of the account console and I have a small problem with the translation of the error messages when a field is required.

Firstly, the key is missing for some languages, but my problem is that the name of the attribute is not translated, but is used directly in the template (see screenshot)

![image](https://github.com/user-attachments/assets/dcc1563e-19d7-43dc-a79a-b20119590ec6)

I've really tried to find the place in the code where it's used to make a PR, but after several hours I have to admit defeat..

Am I missing something? Would it be possible to fix this in the project or is it coming from Keycloak itself?

Edit: Ok, I figured out that the messages are generated from Keycloak source code. Some keys are still missing

**Comment by garronej** [comment]
Hello @rgrosjean,  

Thanks for attemptying to fix this upstream.  
The problem is that the Muti-Page account theme doesn't know the UserProfile attributes out of the box.  
You should checkout this video where I try to explain all this:  

https://docs.keycloakify.dev/account-theme/multi-page#using-the-rest-api

**Comment by rgrosjean** [comment]
I'll check that thanks.

Concerning the missing keys. That's weird. I'm trying to debug `generate-i18n-messages.ts` but I do not understand why some keys are skipped for some languages. e.g. `error-user-attribute-read-only` is present for Arabic, English, Finnish and Dutch, but not German

**Comment by garronej** [comment]
Yes, the account-v1 was removed from keycloak in version 22.  
So the translations included are the most recent version.  
I'll very soon add the posiblity of adding extra languages translation though

**Comment by garronej** [comment]
Hi @rgrosjean,  

Here is the support for adding extra language: https://docs.keycloakify.dev/i18n/adding-support-for-extra-languages
