### ISSUE TITLE
Using the build tools with Angular

### ISSUE THREAD

**Issue by Yawarzy** [keycloakify/keycloakify#649]
Hi,
I am currently trying to figure out how I can use the Angular for the keycloak templates, and I checked the keycloakify-starter-angular, which generates the theme but it did not work well. All I could see was white screen, and the js files linked to the ftl file had wrong path. It would be really helpful if you could point me to a way which I can follow.
Thanks.

**Comment by garronej** [comment]
Hello @Yawarzy,  

The Keycloakify Angular Starter created by @kathari00 is still somewhat experimental.  
What do you think, @kathari00? Is it ready for use at this stage?

Currently, only React is officially supported by Keycloakify. Using it with other frameworks, like Angular, is still considered experimental.

**Comment by Yawarzy** [comment]
@garronej Thanks for the quick response. Is there any approach, which you have in mind that I can take to make this work with Angular ?

**Comment by garronej** [comment]
Only @kathari00 would be able to guide you on this.  
She's the only one that have an Keycloakify Angular theme in production to my knowelage.

**Comment by kathari00** [comment]
Hey, @Yawarzy please hmu in the keycloakify discord. Surely we can make the project work for you. There are still things to do but all important concepts should be working.

**Comment by Yawarzy** [comment]
@kathari00 , Alright I will reach out to you on discord. Thanks!
