### ISSUE TITLE
SVG issue

### ISSUE THREAD

**Issue by GioviQ** [keycloakify/keycloakify#651]
I changed the logo in Account UI Single-page according to https://docs.keycloakify.dev/account-theme/single-page#changing-the-logo

My log is and SVG file and this is the error in browser console log

![Immagine 2024-09-14 115541](https://github.com/user-attachments/assets/fd3334c2-4823-4b5b-ac7e-db8addd40b30)

Should I follow the proposed solutions?

I used the same logo.svg in Login UI, NOT in public directory, and it works. Why?

**Comment by garronej** [comment]
Hello @GioviQ,

I believe the error message explains the issue quite well. 

The `logoUrl` prop expects a URL that begins with `https`, but you're passing an inline `data:image...` string, which isn't supported.

When SVGs are very small, are inlined as a data URL. To resolve this, you can either:

1. Move your SVG file to the public directory, or
2. Add some comments to the SVG to artificially prevent it from being inlined.

Alternatively, you can adjust your Vite configuration to lower the threshold for asset inlining. Here's a helpful link for that:  
https://vitejs.dev/config/build-options#build-assetsinlinelimit

**Comment by GioviQ** [comment]
@garronej still I don't understand why this happens only in Accoun UI and not in Login UI with the same SVG file.

Do Account UI and Login UI have different Vite configurations?

**Comment by garronej** [comment]
> Do Account UI and Login UI have different Vite configurations?  

No. There's only one vite configuration for the project.  

It work in the Login UI because in theory there's no issue with the url being a data url.  
It's just that the Account UI components are less flexible than the Login UI components.  
The account UI components are made by the Keycloak team, Keycloakify is just re-packaging them.  

This is not a bug, this is just the spec. The account UI component expect an https url. It does not work with data urls.

**Comment by GioviQ** [comment]
![Immagine 2024-09-14 180120](https://github.com/user-attachments/assets/7d62f29d-382b-43c8-8c43-ae44ca8194b3)

after changing the logo, the ancor link changed too. I am looking for pf-v5-c-page__header-brand-link in many repositories, with no luck. Do you know where is the variable to set the proper url?
Thank you

**Comment by garronej** [comment]
Hum that's not ideal indeed, I should fix that.  

In the meantime you can watch this video to understand how the Account UI works:  

https://docs.keycloakify.dev/account-theme/single-page  

You need to find the header component and eject it (copy paste it into your repo)

**Comment by garronej** [comment]
Hi, @GioviQ It's fixed in 25.0.4-rc.9
