### ISSUE TITLE
Upgrading from Keycloak 23 to 25.

### ISSUE THREAD

**Issue by tomgelu** [keycloakify/keycloakify#657]
Hello,
I want to upgrade my Keycloak instance from 23 to 25 and I'm wondering if these changes from Keycloak 24 and 25 would need me to rebuild a theme:
* https://www.keycloak.org/docs/latest/upgrading/index.html#changes-to-the-welcome-theme
* https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-theme-variables

My theme is built on version 6.1.10 of Keycloakify
Thanks

**Comment by garronej** [comment]
@tomgelu,  

You're looking at the changelog from 24 to 25 which are not very important.  
However they did massive breaking changes from 23 to 24 so yeah, you most likely need to update your keycloakify to v10:  

https://docs.keycloakify.dev/faq-and-help/migration-guides/v9-greater-than-v10

**Comment by tomgelu** [comment]
Thanks for the quick response, i'll close the issue!
