### ISSUE TITLE
Migration v9 -> v10 - pom.xml, docreatejar

### ISSUE THREAD

**Issue by 500E** [keycloakify/keycloakify#660]
Hello! 
I want to migrate from v9 to v10 and most of the process is going well. However I'm missing two things that I can't find it the docs: 
1. https://docs.keycloakify.dev/v/v9/build-options#docreatejar - is there an equivalent for this option in v10?
2. `pom.xml` file creation - in v9 it was placed directly in the `dist_keycloak` folder after the build, now I can only find it in the generated `.jar` file. Is it possible to generate `pom.xml` file similarly to the v9?

Thank you!

**Comment by thomashexagon** [comment]
I was also looking for 1.

**Comment by garronej** [comment]
Hello @500E,  

- 1. No, it's no longer possible. The theme dosen't work anymore just by copying the assets manually into Keycloak. The proper way to load extentions in Keycloak is to put a jar in `/opt/keycloak/providers` and run `bash /opt/keycloak/bin/kc.sh build` then start Keycloak.  
- 2. No it's not possible.  

Thoses two things can be addressed just by running `jar -xf keycloak-theme.jar`.  
Maybe you can describe to me what you are trying to acheive and I can tell you what's the best way to do it.

**Comment by iliascholl-up42** [comment]
Hey @garronej,

I am a colleague of @500E. We are injecting `repositories` and `distributionManagement` sections into the `pom.xml` to reference our private maven repository and run `mvn install` and `mvn deploy` to build and publish the JAR to our private repo. The versioned publishing enables us to pull the JAR during the deployment of the Keycloak server.

We are in the process of changing our deployment process and I think we will be able to work around this issue with a monorepo setup.

On a different note: could you please elaborate on the following:
> The theme doesn't work anymore just by copying the assets manually into Keycloak.

**Comment by garronej** [comment]
Hello @iliascholl-up42, 

Can't you use [this](https://github.com/keycloakify/keycloakify/issues/623#issuecomment-2314675038) to publish the JAR after the JAR is built?  

> On a different note: could you please elaborate on the following:

This extension is needed for the password policies to be available: https://github.com/jcputney/keycloak-theme-additional-info-extension  
We got this PR merged in Keycloak so it won't be required anymore starting with Keycloak 26: https://github.com/keycloak/keycloak/pull/32625  
We also need https://github.com/p2-inc/keycloak-account-v1 for pepole implementing [the multi page flavor of the account theme](https://docs.keycloakify.dev/account-theme/multi-page)

**Comment by iliascholl-up42** [comment]
@garronej thanks for the explanation, it makes sense!

> Can't you use https://github.com/keycloakify/keycloakify/issues/623#issuecomment-2314675038 to publish the JAR after the JAR is built?

This does indeed work for us! I have initially dismissed this approach since we are deploying to GCP Artifact Registry and need a maven extension to do so. A quick search brought me to https://stackoverflow.com/a/71177199 explaining that one can use [Maven Core Extensions](https://maven.apache.org/docs/3.3.1/release-notes.html#core-extensions) for this.

We should be good!

**Comment by garronej** [comment]
Great thanks for the feedback.  

Just a note https://github.com/p2-inc/keycloak-account-v1 is included in the jar **only** if you have explicitely opted in for the Multi-Page account theme.
