### ISSUE TITLE
Custom CSS does not reflect when building JAR file

### ISSUE THREAD

**Issue by fikrifaris** [keycloakify/keycloakify#661]
I followed the documentation:
- Replaced with own logo
- Remove some sections
- Created a custom CSS to change login button color
- then build the theme

I installed the JAR file in Keycloak, the logo was applied but somehow the css is not reflected compared to when i tried in localhost. I've tried lots of solutions, still nothing.

**Comment by garronej** [comment]
Hello @fikrifaris,  

What files did you edit?

**Comment by fikrifaris** [comment]
Added import "./main.css" to KcPage.tsx, then put the main.css inside the login folder as per the documentation. In my css, i used the .kcButtonClass.

**Comment by garronej** [comment]
Well, share more about what you are doing. Or share your code

**Comment by fikrifaris** [comment]
This is the custom css i want to add:
<img width="353" alt="Screenshot 2024-09-19 190853" src="https://github.com/user-attachments/assets/ca809a1b-06d9-4edc-9112-8f61bd9d13a3">

Then i import it to KcPage.tsx:
<img width="467" alt="Screenshot 2024-09-19 190936" src="https://github.com/user-attachments/assets/3fd16392-4a58-450d-8372-3b45fe669156">

This is vite.config.ts:
<img width="436" alt="Screenshot 2024-09-19 191034" src="https://github.com/user-attachments/assets/bb5246a3-702d-4d10-9ff0-3f3be06ebe2b">

I followed as the documentation said (https://docs.keycloakify.dev/customization-strategies/css-level-customization/basic-example). Then build using npm run build-keycloak-theme.

Put the JAR file to keycloak's provider folder then restart the keycloak server. Set to the new theme from the keycloak admin dashboard. The css from main.style didnt applied. 

When i inspect the content of the JAR file, i didnt find the main.css anywhere.

**Comment by garronej** [comment]
You probably didn't apply the theme at the correct place, read this:  

https://docs.keycloakify.dev/enabling-your-theme  

My guess is that you applied the theme on the master realm.  

Otherwise it works: https://filedn.com/lYPEPucNMheV19aDu23lK0Q/transfert/Screen%20Recording%202024-09-19%20at%2014.54.52.mov

**Comment by fikrifaris** [comment]
I did apply the correct theme, this is from my keycloak server
<img width="282" alt="Screenshot 2024-09-19 212100" src="https://github.com/user-attachments/assets/e7553278-741b-41af-87a0-ab73737fe801">

as you can see, i replaced the logo and removed the language dropdown.

This is the result i want to achieved at least, this is from my keycloakify-starter localhost:
<img width="290" alt="Screenshot 2024-09-19 192005" src="https://github.com/user-attachments/assets/55882bc2-8a88-4007-b19d-4fe6e10813da">

is there a chance i didn't set the project correctly, even though the build was successful?

**Comment by garronej** [comment]
Do you still have the issue?  

I can look into it if you send me the jar on discord or link me the repo.  

Closing for now
