### ISSUE TITLE
Login theme: keycloak.v2

### ISSUE THREAD

**Issue by rui-leite-ndrive** [keycloakify/keycloakify#665]
Any way to use the new login theme version: keycloak.v2?

**Comment by garronej** [comment]
Hello @rui-leite-ndrive,  

No, the account v2 is in constant rework, converting the FreeMarker template into equivalent react components is a lot of work so Keycloakify mirror the current stable version.  

What feature are you missing?  

It's always possible to implement the page yourself in your project if you really need...

**Comment by rui-leite-ndrive** [comment]
Hi @garronej!

I have a login theme based on keycloak.v2 login. 

Now I want to customise the account console, keeping the login theme I already have.

As I would like to reuse some CSS files, do you recommend any possibility to just copy my login folder to the final build of keycloakify and use my login files next to the account theme build of keycloakify? Any way to integrate that copy step, on vite config file?

**Comment by garronej** [comment]
Yes it's possible.  

If you want Keycloakify to build a single jar that contains:  
- An OG login theme (not react, not managed by Keycloakify)
- An account Single-Page  

What you'll do is:  

```bash
git clone https://github.com/keycloakify/keycloakify-starter
cd keycloakify-starter
yarn
npx keycloakify initialize-account-theme # Select the Single-Page option
```

Then you want to copy the `login` directory (containing your .ftl files) at the root of your project.  

Finally you can edit your `vite.config.ts` as follow:  

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        keycloakify({
            accountThemeImplementation: "Single-Page",
            postBuild: async (buildContext) => {

                const fs = await import("fs");
                const path = await import("path");

                const logFilePath = path.join(buildContext.projectDirPath, "log.txt");

                fs.rmSync(logFilePath, { force: true });

                const loginDirPath = path.join("theme", buildContext.themeNames[0], "login");

                fs.rmSync(loginDirPath, { recursive: true });

                fs.cpSync(
                    path.join(buildContext.projectDirPath, "login"),
                    loginDirPath,
                    { recursive: true }
                );

            }
        })
    ]
});
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        keycloakify({
            accountThemeImplementation: "Single-Page",
            postBuild: async (buildContext) => {

                const fs = await import("fs");
                const path = await import("path");

                const loginDirPath = path.join("theme", buildContext.themeNames[0], "login");

                fs.rmSync(loginDirPath, { recursive: true });

                fs.cpSync(
                    path.join(buildContext.projectDirPath, "login"),
                    loginDirPath,
                    { recursive: true }
                );

            }
        })
    ]
});
```  
Documentation of the postBuild hook: https://docs.keycloakify.dev/configuration-options/postbuild

It only work with the very last version of Keycloakify 11.0.1  

I demo it here: https://github.com/keycloakify/keycloakify-starter/tree/with_og_login_theme

**Comment by rui-leite-ndrive** [comment]
It works! 😀 Thank you so much
