### ISSUE TITLE
[MULTIPLE THEMES] email template per theme

### ISSUE THREAD

**Issue by djleonskennedy** [keycloakify/keycloakify#669]
Hello!

I can't find in the docs how to set up an email template according to the theme, is it possible?

Keycloakify version: latest

**Comment by garronej** [comment]
I'll ship a new feature to make it possible soon

**Comment by garronej** [comment]
It's now possible starting with Keycloakify 11.2.0  

https://docs.keycloakify.dev/theme-variants#email-theme
