### ISSUE TITLE
Account page select a locale doubling

### ISSUE THREAD

**Issue by AlexBab11** [keycloakify/keycloakify#679]
Hi, I noticed that there are two select a locale dropdowns in account page. The second one only appear when i choose keycloackify theme. Could you please help fixing it? 
![issue](https://github.com/user-attachments/assets/106b50be-d56c-4743-bd48-74befbab763c)

**Comment by garronej** [comment]
Hello, what version of Keycloak are you using?  

Does it show the same when you run `npx keycloakify start-keycloak`?

**Comment by AlexBab11** [comment]
1. I'm using 24.0
2. Yes.

**Comment by garronej** [comment]
I can reproduce. I'll fix it.

**Comment by garronej** [comment]
It's fixed in @keycloakify/keycloak-account-ui version 25.0.4-rc.8

**Comment by AlexBab11** [comment]
Hi. I pulled main, but still can reproduce though on 25 it works fine.

**Comment by garronej** [comment]
Hi @AlexBab11,  

It's fixed. You probably didn't update to the latest version.  

What do you mean by "I pulled main"?  

You must update `@keycloakify/keycloak-account-ui` to `25.0.4-rc.9`  

https://docs.keycloakify.dev/account-theme/single-page#updating-keycloak-account-ui-to-a-new-version

**Comment by AlexBab11** [comment]
Ahh i didn't get how to update account page at first, thanks for letting me know @garronej
