### ISSUE TITLE
Failed at: #if !object[key]??  [in template "login.ftl" in function "toJsDeclarationString" at line 253, column 17]

### ISSUE THREAD

**Issue by TommyNT** [keycloakify/keycloakify#684]
Hi, 

I have a problem with errors below when I try to deploy Keycloak themes to a server

```
- Failed at: #if !object[key]??  [in template "login.ftl" in function "toJsDeclarationString" at line 253, column 17]
- Reached through: ${toJsDeclarationString(.data_model, ...  [in template "login.ftl" at line 20, column 19]
```

Last successfully deploy was on 28th September 2024 and since this time I don't do changes in Keycloak theme
I have Keycloak v25.0.6, Keycloakify v10

Edit: CI updates Keycloak to latest (v26.0.0) and there are the problems with error, I lock Keycloak version to `25.x.x` and it's working

**Comment by garronej** [comment]
The version of keycloakify your theme was build with probably released before Keycloak 26, so it doesn’t include the compatibility layer for that version. When I mention that Keycloakify themes are compatible with all Keycloak versions, I mean they are compatible with versions available at the time of the Keycloakify release.

To support a newer version, you’ll need to update Keycloakify to the latest version of the major release you're using and rebuild the theme.
