### ISSUE TITLE
Changing language no longer works since commit e5ab46727a13f95423757dfe732ec4360d3afc9f (for Keycloak >= v24)

### ISSUE THREAD

**Issue by JohnMichaelTO** [keycloakify/keycloakify#686]
Hello @garronej,

First time posting an issue here 👋 
Beforehand, thank you for all the work around Keycloakify!

I'm encountering an issue when changing language since this [commit](https://github.com/keycloakify/keycloakify/commit/e5ab46727a13f95423757dfe732ec4360d3afc9f) (my assumption as I couldn't dig further).

Steps to reproduce:
1. Clone https://github.com/keycloakify/keycloakify-starter/
2. `yarn install`
3. `npx keycloakify start-keycloak`
4. Choose any version from v24 to v26
5. Go to https://my-theme.keycloakify.dev/ (make sure internationalization is enabled with at least 2 languages on Keycloak instance)
6. On the login page after being redirected, select any other language
7. We get the error here (see screenshot)

<img width="524" alt="image" src="https://github.com/user-attachments/assets/38b37a46-6d1d-4fc0-aa68-c6bae051ccdf">

I suspect something has changed on Keycloak side so it shouldn't be related to the commit mentioned above because when I test it with v23, it's working as expected.

I hope this is helping and thanks again for your amazing work!

**Comment by garronej** [comment]
Thank you for the kind work and the perfect issue.  
If all the issue submited could be as good as this one my life would be so much easyer.  

I'll fix it tonight.

**Comment by JohnMichaelTO** [comment]
@garronej Amazing! Can't wait to see this fixed! 🚀

**Comment by garronej** [comment]
Hello @JohnMichaelTO,  

Unfortunately I wasn't able to reproduce the error on the starter.  

If you have recently updated to Keycloakify 11, have you followed the migration guide?  

https://docs.keycloakify.dev/faq-and-help/migration-guides/v10-greater-than-v11  

Let me know.  

Best

**Comment by JohnMichaelTO** [comment]
Hello @garronej,

Thanks for your help! Yes, I initially followed the upgrade guide.
I just found out it's actually a false alert, sorry for that! 🙏
 
As you couldn't reproduce the error on the starter, it made me realized I should have tried it on another browser or private window (I was on Firefox), which I just did and it turns out the problem was because of some residual cookies I got on my dev environment.

![image](https://github.com/user-attachments/assets/b4e94b69-6d1a-4f93-96b1-60911159f21b)

I believe among those, there were at least (I don't recall all of them unfortunately) multiple times as you can see in the screenshot above:
* KC_RESTART
* KEYCLOAK_IDENTITY_LEGACY
* KEYCLOAK_IDENTITY
* KEYCLOAK_SESSION_LEGACY
* AUTH_SESSION_ID
* AUTH_SESSION_ID_LEGACY

After deleting them, it worked on Firefox (initial browser where I encountered the error described above).

I'm closing this issue

**Comment by garronej** [comment]
Great, thank you for the context as it will help user facing the same issue.
