### ISSUE TITLE
Custom translation keys can't be set or overridden by Keycloak Realm Overrides

### ISSUE THREAD

**Issue by novelnet** [keycloakify/keycloakify#691]
I'm using keycloak 25.0.2 and keycloakify 11.3.4 and added a custom "teestvaar" in the test realm as override, also in the same realm i have the following keycloak theme enabled. The translations set withCustomTranslations in i18nBuilder work, but won't be overridden with Keycloak Override. If i use advancedMsgStr like in ```console.log('advancedMsgStr', advancedMsgStr('teestvaar'));``` it outputs only the key again (teestvaar) without finding the translation from realm override.

**Realm override:**
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/2456453e-834f-4f92-8f4e-02c566add8ec">

**i18n.ts (also tested in login and account):**
```
import { i18nBuilder } from "keycloakify/account";
import type { ThemeName } from "../kc.gen";

const { useI18n, ofTypeI18n } = i18nBuilder
    .withThemeName<ThemeName>()
    .withCustomTranslations({
        en: {
            // teestvaar: "en test" // works when uncommented but also cant be overridden by realm override
        },
        de: {
            // teestvaar: "de test"
        }
    })
    .build()

type I18n = typeof ofTypeI18n;

export { useI18n, type I18n };
```

**login/Template.tsx:**
```ts
import { useEffect } from "react";
import { clsx } from "keycloakify/tools/clsx";
import type { TemplateProps } from "keycloakify/login/TemplateProps";
import { getKcClsx } from "keycloakify/login/lib/kcClsx";
import { useInitialize } from "keycloakify/login/Template.useInitialize";
import { useSetClassName } from "keycloakify/tools/useSetClassName";
import type { I18n } from "./i18n";
import type { KcContext } from "./KcContext";
import "../main.css"
import bitaloSvgUrl from "../account/assets/bitalo.svg";
import { kcSanitize } from "keycloakify/lib/kcSanitize";

export default function Template(props: TemplateProps<KcContext, I18n>) {
    const {
        displayInfo = false,
        displayMessage = true,
        displayRequiredFields = false,
        headerNode,
        socialProvidersNode = null,
        infoNode = null,
        documentTitle,
        bodyClassName,
        kcContext,
        i18n,
        doUseDefaultCss,
        classes,
        children
    } = props;

    const { kcClsx } = getKcClsx({ doUseDefaultCss, classes });

    const { msg, msgStr, advancedMsgStr, currentLanguage, enabledLanguages } = i18n;

    console.log('advancedMsgStr', advancedMsgStr('teestvaar')); // not working, outputs: teestvaar
```

**Comment by garronej** [comment]
Hello @novelnet,

Currently, not every key can be overridden at the realm level. While this is something I could address, the reasoning behind it is as follows:

- For keys like `termsText` or any label, placeholder, or helper text related to custom user attributes, it makes sense to define them at the realm level. In such cases, Keycloakify will apply any overrides defined at the realm.
- For everything else, particularly custom i18n keys, these are specific to the theme. The Keycloak server doesn't necessarily need to manage them, so defining translations at the realm level for keys that originate from the theme can feel out of place. Additionally, theme variants allow for different translations of a given key. [See documentation](https://docs.keycloakify.dev/theme-variants#different-text-for-each-of-your-theme-variants).

If you realy need to do if for some reason you can implement this hack:  

```tsx
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        keycloakify({
            // Don't mind the sementic here, it's not the inded purpose of the fuction.  
            kcContextExclusionsFtl: [
                '<@addToXKeycloakifyMessagesIfMessageKey str="teestvaar" />',
                '<@addToXKeycloakifyMessagesIfMessageKey str="someOtherVar" />',
                // ...
            ].join("\n")
        })
    ]
});
```  

It's levraging this function:  https://docs.keycloakify.dev/configuration-options/kccontextexclusionsftl

**Comment by novelnet** [comment]
Thanks a lot for you fast and very helpful answer, that understanding of only specific keys can be overridden by realms was unclear before. Also the theme variants are a good solution, but i choose kcContextExclusionsFtl where i change a url via translation by each realms only, which works great.
