### ISSUE TITLE
Can't run in docker using start-keycloak

### ISSUE THREAD

**Issue by jansivans** [keycloakify/keycloakify#694]
Trying to run my theme in docker by using `npx keycloakify start-keycloak` results in this error:
```
docker: Error response from daemon: create ./node_modules/.cache/keycloakify/myrealm-realm-26.json: "./node_modules/.cache/keycloakify/myrealm-realm-26.json" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```
![CleanShot 2024-10-17 at 13 18 52@2x](https://github.com/user-attachments/assets/108110ab-c2d8-4378-aef2-eb5720f921f7)

**Comment by garronej** [comment]
Hello @jansivans,  

Thanks for reporting.  
Can you test with `keycloakify@11.3.7-rc.0` ?

**Comment by jansivans** [comment]
@garronej it works! Thank you🎉
