### ISSUE TITLE
Error thrown when using npx keycloakify initialize-email-theme and selecting KC-Version 24.0.8 

### ISSUE THREAD

**Issue by lucaa6i** [keycloakify/keycloakify#696]
```
Error: end of central directory record signature not found
    at /Users/user/kc-email-theme/node_modules/keycloakify/bin/33.index.js:1520:14
    at /Users/user/kc-email-theme/node_modules/keycloakify/bin/33.index.js:1964:5
    at /Users/user/kc-email-theme/node_modules/keycloakify/bin/33.index.js:1000:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
```

After cloning the keycloakify starter and installing all dependencies.
I get hit with the error from above when selecting KC-Version 24.0.8.

Choosing KC-Version 25.x / 26.x / 23.x works fine, and the folder src/email is created.

Tested on keycloakify versions 11.3.6 & 10.0.0-rc.128

**Comment by garronej** [comment]
Hello @lucaa6i,  

Thanks for reporting, it's fixed in 11.3.7.  
I recomend however to initialize you email theme with the latest available version regardless of the Keycloak version you are curently targetting.
