### ISSUE TITLE
[Help Needed] - Want to change current login page with Keycloack

### ISSUE THREAD

**Issue by muhammadjasim78** [keycloakify/keycloakify#702]
I am new to Keycloack and my client product is using KeyCloack for identity management. Right now the frontend is using custom Form field with react-hook-form and sending the request to the keylock URL to authenticate which is deployed on the server. Now they don't want to use custom fields, they wanna use the keylock login page but they want to keep the current theming and UI and only wanna change the custom fields with keycloack.

This is the current Login page: 

![Screenshot 2024-10-21 122508](https://github.com/user-attachments/assets/3cb7f7c8-047a-4ae8-b5f8-e2647af9b4bc)

Now what we want is to keep the page as it is as there are other things happening on this login page and client only wants to change the login form that is circled in red with keycloack login form. 

So in the end, users will not see any difference in the login page and the only thing that will be different is the login form will be from keycloack instead of the custom one that we already have.

I was playing with keycloackify and I understand that I can customize the whole page, but what I don't understand is how can I use this in my current login page. 

Is it even possible to do that?

Frontend Specs:
- React 18
- Vite
- MUI 5

**Comment by garronej** [comment]
> Is it even possible to do that?  

No, it's not. Maybe with an iframe but this is hacky as hell. It goes against the core principle of OAuth, that imply that the whole authentication process happens outside the application.  

> Right now the frontend is using custom Form field with react-hook-form and sending the request to the keylock URL to authenticate which is deployed on the server.  

What you company was doing it generally considered an antipatern. See [this post](https://keycloak.discourse.group/t/creating-a-custom-login-ui-frontend/27734).  

That beeing said, looking at your screenshot, it seems like you're using MUI. You can easyly replicate the same exact page as a Keycloak theme, the user won't even notice it's being redirected away.

**Comment by garronej** [comment]
There is a tutorial video for creating Keycloakify theme with MUI.  

https://youtu.be/PhNE-3EwwP8?si=A4B82k_i1w-qHG9N  

In the tutorial, the approach implemented is to start from the default styles and incrementally customize them.  

In your case since you already have the all page ready to go, I'd just make sure to set the correct input names, urls and accomodate for the error messages but mainly start from scatch.  
Make sure to se "doUseDefaultCss" to false for the login.ftl

**Comment by muhammadjasim78** [comment]
Okay, so that means I have to create this whole page from scratch using keycloackify?

But how can I add extra stuff that I already have in my current login page which is not a part of keycloak login flow?

**Comment by garronej** [comment]
Be more specific

**Comment by muhammadjasim78** [comment]
I mean the login.ftl file will only have the login related components
![Screenshot 2024-10-21 132216](https://github.com/user-attachments/assets/9b4b836b-3288-4f9c-a177-427769a5b1c7)

So, how can I add other components that I have in my current login page?

**Comment by garronej** [comment]
Keycloakify theme are just Vite/React (or Vite/Angular) web apps!  
You can do whatever you want with it. Keycloakify provide you the keycloak context so that you know where to submit the forms.  
It's not a restrictive framwork. It just comes by default with the react components that matches the aspect of the default keycloak theme but you're not forced to use thoses components.

**Comment by nima70** [comment]
Hi @muhammadjasim78,

I'm not sure if this will help you, but in this [repo](https://github.com/nima70/keycloakify-tailwind-shadcn.git), I am adding my own components. I am using ShadCN and Tailwind. 

For example, something like the scroll area is not part of Keycloakify by default.  
![Custom Sidebar](https://github.com/user-attachments/assets/16998105-e55b-4b79-a00c-812c4c88a313)

You can check out the live demo of all the added components here:  
[View Storybook](https://nima70.github.io/keycloakify-tailwind-shadcn/storybook/)

If you'd like to learn more about this repo, you can check out this video as well:  
[![Watch the video](https://img.youtube.com/vi/LG5Wv7dsh4I/maxresdefault.jpg)](https://youtu.be/LG5Wv7dsh4I)

### [Watch this video on YouTube](https://youtu.be/LG5Wv7dsh4I)

**Comment by garronej** [comment]
Hey @nima70,  

Thanks for getting your help and offering support.  
I think he's using MUI, the best strat here for him is probably just to put the main frame of he's page in template and have a simple form using MUI inputs component on the login page.  
Tailwind and ShadeCN is another stack.

**Comment by nima70** [comment]
Hi @garronej 

Oh, I see. Noted.

**Comment by garronej** [comment]
But don't get me wrong, I'm super happy if you can help pepole here. There's a ton of pepole that uses tailwind/shadecnUI.

**Comment by nima70** [comment]
Hi @garronej 

No worry at all. It is all good.😉

**Comment by muhammadjasim78** [comment]
Thanks for your help guys @garronej @nima70 
It simplified a lot of things for me. 
Thanks for the quick support.
Closing this issue.

**Comment by nima70** [comment]
@muhammadjasim78. You are welcome. It was our pleasure.

**Comment by muhammadjasim78** [comment]
Hi @garronej 
I understand the theming concept now.
Now I have another question related to redirects. I tried finding it on keycloack but there is no good answer over there.
So right now my current login page is at `https://smartlab.ladecloud-dev.de/login`
And now the main requirement for now is to create `https://smartlab.ladecloud-dev.de/login-v2` where the keycloack login page should be placed which will be the exact copy of `https://smartlab.ladecloud-dev.de/login` but it will be designed with keycloakify theming system and pushed to keycloak as a theme.
I was playing with keycloack admin and there for every client that I create I get this kind of URL 

`https://my-keycloack-domain/auth/realms/my-keycloack/protocol/openid-connect/auth?client_id=my-client-id&response_type=code&redirect_uri=https%3A%2f%2fsmartlab.ladecloud-dev.de` 

Can I add proxy to this URL somehow as in keycloack issues they said, it is not possible: https://github.com/keycloak/keycloak/discussions/17690

Do you have any insights on that? we really don't wanna use iframes and according to the requirements if I will go to `https://smartlab.ladecloud-dev.de/login-v2` I should land on my keycloack themed login page

Thanks

**Comment by garronej** [comment]
Hello @muhammadjasim78,  

No it's impossible. It's not how OAuth works.  You can however redirect to the Keycloak login pages when they navigate to `https://smartlab.ladecloud-dev.de/login` with a library like [oidc-spa](https://oidc-spa.dev) (or whatever oidc client library you are implementing).  

Do not use iframe, do not try to bend the standards to your requirements.  
In this url:  
`https://my-keycloack-domain/auth/realms/my-keycloack/protocol/openid-connect/auth?client_id=my-client-id&response_type=code&redirect_uri=https%3A%2f%2fsmartlab.ladecloud-dev.de`

This part can be customized: `https://my-keycloack-domain/auth`
This part cannot: `realms/my-keycloack/protocol/openid-connect/auth?client_id=my-client-id&response_type=code&redirect_uri=https%3A%2f%2fsmartlab.ladecloud-dev.de`  

The users cannot directly navigate to the login pages, the redirectioin have to be initiated by your app.  

You have two options here:  
- Change your requirements.  
- Roll your own auth
