### ISSUE TITLE
Crash when trying to setup recovery codes from account page

### ISSUE THREAD

**Issue by thib-rdr** [keycloakify/keycloakify#713]
Hi,

I'm building a custom theme for my Keycloak installation, and I'm encountering a crash when trying to finish the setup of the recovery codes of the OTP.

Despite checking the checkbox "I have saved these codes somewhere safe", the "Complete setup" button stays disabled. 
When checking the box, an exception is thrown in the console : 

<img width="1072" alt="Screenshot 2024-11-06 at 14 59 52" src="https://github.com/user-attachments/assets/d9b611d9-5f90-4147-8a9a-13dbe9eda4cf">

FYI, it works normally if I don't use my custom theme, but the default keycloak one. 

I did not eject this page my theme, I'm using the default one.

I'm using Keycloakify 11.2.10, with Keycloak 26

Please let me know if you need more info.

**Comment by garronej** [comment]
Hello @thib-rdr,  

Thanks for reporting, please update to the latest version of Keycloakify and tell me if the problem persists

**Comment by thib-rdr** [comment]
Hi, thanks for your answer

I upgraded to v11.3.16, and the problem persists, but there's another error that appears (cf screenshot below)

<img width="1534" alt="Screenshot 2024-11-06 at 21 28 30" src="https://github.com/user-attachments/assets/cf5d41cf-5d3c-49e0-a518-1da485b600ed">

The first error appears on page load, the second appears when I check the "I have saved these codes somewhere safe" checkbox.

Thanks !

**Comment by thib-rdr** [comment]
Hey, it's me again ! 

After more investigation, I found the problem, and  I opened a PR : https://github.com/keycloakify/keycloakify/pull/714

Please let me know if you have any feedback !

Thanks

**Comment by garronej** [comment]
Fixed in 11.3.17  
Thank you for your pacience
