### ISSUE TITLE
LoginPasskeysConditionalAuthenticate mismatches the keycloak ftl

### ISSUE THREAD

**Issue by zvn2060** [keycloakify/keycloakify#721]
There is 3 bug in the `LoginPasskeysConditionalAuthenticate` component

1. the `div` whose id is `kc-form-passkey` should be `kc-form-passkey`
since there is a **hardcoded** [reference](https://github.com/keycloak/keycloak/blob/7adbba6079933a26616003aeb33709f11a0ad5e0/themes/src/main/resources/theme/base/login/resources/js/passkeysConditionalAuth.js#L48) to toggle element visibility

https://github.com/keycloakify/keycloakify/blob/64ca0bc0ca61de5d35626a10de8a2d5c5ae1302f/src/login/pages/LoginPasskeysConditionalAuthenticate.tsx#L118C25-L122C61
     
https://github.com/keycloak/keycloak/blob/7adbba6079933a26616003aeb33709f11a0ad5e0/themes/src/main/resources/theme/base/login/login-passkeys-conditional-authenticate.ftl#L70-L73

2. the `form#kc-form` should outside `kcContext.authenticators` nil check
    
3. the `autoComplete` of `input#username` should be `username webauthn`
    not sure why `keycloak` give it `username webauthn` and `off` again
    but it should be `username webauthn`
    https://github.com/keycloakify/keycloakify/blob/64ca0bc0ca61de5d35626a10de8a2d5c5ae1302f/src/login/pages/LoginPasskeysConditionalAuthenticate.tsx#L146-L150

**Comment by garronej** [comment]
Hello @zvn2060,

Thank you for reporting these bugs. I had “blindly” ported those pages, doing my best to avoid any mistakes during the translation, but it seems several issues have slipped through.

Since you’ve done an excellent job analyzing the problem, would you be open to submitting a PR to fix them?

It would be greatly appreciated!

**Comment by zvn2060** [comment]
ok, give me about 2 days

**Comment by garronej** [comment]
Thank you very much!
