### ISSUE TITLE
Incorrect display of Chinese locale name

### ISSUE THREAD

**Issue by untone-survive** [keycloakify/keycloakify#726]
This line 
https://github.com/keycloakify/keycloakify/blame/cfda99f5b0c6e16eaf1cbcaa3e4c94d41330fb95/src/login/i18n/noJsx/getI18n.tsx#L173 makes `Chinese (Simplified) (中文 (简体))` look like `Simplified` in locales dropdown. Do we actually need to display only the translated name of the language?

**Comment by garronej** [comment]
Hello @untone-survive,  

Good catch, just fixed it.  

> Do we actually need to display only the translated name of the language?  

We stick to how it's in Keycloak's default theme. You can change it in your theme if you want.
