### ISSUE TITLE
Error when setting up 2FA and redirecting to account management

### ISSUE THREAD

**Issue by fabianrochelt** [keycloakify/keycloakify#735]
I have tried to set up an authenticator app and when I enter the code and the theme s redirecting to the account/account-security/signing-in url the error page not found occurs. Why? In standard theme it is working but standard theme uses hashtags in url??

**Comment by garronej** [comment]
Hello @fabianrochelt,  

You'll have to give me some more context.  

What are you talking about?  
The Account Single-Page theme?  
What are you doing exactly, what version of Keycloakify and Keycloak are you using.  
Please provide as much detail as you can.

**Comment by fabianrochelt** [comment]
Thanks for your response, so here is what I am trying to do:
I am using keycloakify v11 starter and keycloak 24 running on my digitalocean droplet as container. I have created an account theme SPA which is working nicely so far. However, it shows some unexpected behaviour when redirecting during changes in the account page from the user whereas the standard theme is handling it correct.
When the user opens his account management page and sings out the theme shows an error message "sorry page not found" although the url looks correct the only difference between standard theme and customized theme is the hashtag after the account:
Url standard theme:
https://auth.mydomain.at/realms/myrealm/account/#/account-security/signing-in
Url customized theme:
https://auth.mydomain.at/realms/myrealm/account/account-security/signing-in

![keycloak1](https://github.com/user-attachments/assets/00c60c11-86e6-4918-a603-07d9215ba99b)
![keycloak2](https://github.com/user-attachments/assets/628224e8-e32b-4721-a808-4e9e5a9b04c2)

The same thing is happening when the user sets up a 2FA authenticator like SMS or Google authenticator. When redirecting also the page not found error occurs.

Additional question, when I set up the SMS authenticator I have seen that the mobile phone config screen and the sms code input screen are not customized with my theme. Why is that and how can I customize them?

**Comment by garronej** [comment]
I'm glad the problem was solved. It would be nice to have aditional infos though for pepole that might face the same issue.  

> Open question: How can I customize the mobile phone config screen and the sms code input screen to adhere with my customized
theme?  

I don't know. Account theme or login theme? Are you using a keycloak extention, are you usine PhaseTwo?

**Comment by fabianrochelt** [comment]
I added now the custom pages and locally with vite they look good. I build the theme now with:
'npx keycloakify build' and with 'npm run build-keycloak-theme' but there are no .ftl files added in the dist-keycloak folder and the screens are also not customized on my website. Why? You write something about bundling and build?

**Comment by garronej** [comment]
Show me your src/login/KcContext.ts file

**Comment by fabianrochelt** [comment]
yes sure:

here is the code:
`/* eslint-disable @typescript-eslint/ban-types */
import type { ExtendKcContext } from "keycloakify/login";
import type { KcEnvName, ThemeName } from "../kc.gen";

export type KcContextExtension = {
    themeName: ThemeName;
    properties: Record<KcEnvName, string> & {};
    // NOTE: Here you can declare more properties to extend the KcContext
    // See: https://docs.keycloakify.dev/faq-and-help/some-values-you-need-are-missing-from-in-kccontext
};

export type KcContextExtensionPerPage = {
    "login-sms.ftl": {
        auth: {
            attemptedUsername: string;
        };
        url: {
            loginRestartFlowUrl: string;
            loginAction: string;
        };
    };

    "mobile_number_form.ftl": {
        auth: {
            attemptedUsername: string;
        };
        url: {
            loginRestartFlowUrl: string;
            loginAction: string;
        };
    };
};

export type KcContext = ExtendKcContext<KcContextExtension, KcContextExtensionPerPage>;
`

**Comment by garronej** [comment]
@fabianrochelt It looks ok to me, it should work.  
If you can give me access to the repo I can tell you what's wrong.

**Comment by fabianrochelt** [comment]
Hi Joseph,

alright here I attached the repo as zip I just removed the images. Please let me know what's wrong with my setup. Thanks in advance.
[custom-theme.zip](https://github.com/user-attachments/files/17974545/custom-theme.zip)

**Comment by garronej** [comment]
Hello @fabianrochelt,  

Well the page are indeed generated by Keycloakify:  

<img width="812" alt="image" src="https://github.com/user-attachments/assets/3ef60f34-0085-4a3a-afd1-70c82b806d42">

<img width="313" alt="image" src="https://github.com/user-attachments/assets/4f943d33-436f-4038-b99c-feead175b266">

**Comment by fabianrochelt** [comment]
which build command did you use?

**Comment by fabianrochelt** [comment]
cleaned the .jar files in the docker container and now it seems the correct .jar is selected from the providers folder and everything is working fine. thank you very much and I close this issue right away.
