### ISSUE TITLE
 `keycloak-version` parameter in `start-keycloak` doesn't work

### ISSUE THREAD

**Issue by timofei-iatsenko** [keycloakify/keycloakify#746]
try to run the command:

```bash
keycloakify start-keycloak --keycloak-version=26.0.4
```

Result:

> Invalid Keycloak version: 26.0.4 It should be a valid semver version example: 26.0.4

The root cause of it is here
https://github.com/keycloakify/keycloakify/blob/73031e74ec5ce735c67e2ef0ed8d6f66871ec984/src/bin/main.ts#L145-L157

```js
SemVer.parse(keycloakVersion); // <-- here value is not returned, its always false or undefined
```

**Comment by garronej** [comment]
Hello @timofei-iatsenko,  

My bad, this part of the code was not completed indeed.  

I've fixed it.  

By the way you can now do:  

```bash
keycloakify start-keycloak --keycloak-version=26.0.4
keycloakify start-keycloak --keycloak-version=26.0
keycloakify start-keycloak --keycloak-version=26
```

All options will work.
