### ISSUE TITLE
Add support for Nrwl/NX

### ISSUE THREAD

**Issue by adover** [keycloakify/keycloakify#87]
In my company we use NX Monorepos to house our applications and our design system. I would like to make some modifications to Keycloakify to allow us to be able to do the following:

- Specify NX as a build provider, either detected automatically or by an argument in the command line
- With NX as the build provider, paths for `build` and `build_keycloak` are modified to be inside the `dist` folder
- The keycloakify project is resolved dynamically somehow

I plan to raise a PR for this, but open to suggestions from the community!

**Comment by garronej** [comment]
Hi,  
Any news?

**Comment by lordvlad** [comment]
I have some WIP on this, I'll try and pick this up again next week

**Comment by garronej** [comment]
Damn, you're the real MVP!

**Comment by lordvlad** [comment]
@adover got a few questions for your requirements

> With NX as the build provider, paths for build and build_keycloak are modified to be inside the dist folder

This is quite clear and easy to implement

> Specify NX as a build provider, either detected automatically or by an argument in the command line

Here im not sure what you mean by 'build' provider? Keycloakify does not call any other build tool, the react app must be compiled beforehand. Maybe you can elaborate?

> The keycloakify project is resolved dynamically somehow

This requirement again is unclear, maybe you can elaborate?

**Comment by garronej** [comment]
Hi @lordvlad,  
I think he dosen't have clear requirements in mind.  
He just now that he's working in a Nx monorepo framwork ant that he'd like to create a Keyclaokify theme.  
He probably has a `ui` dir and he would like to be imort he's component and tooling from here.  

Beyound that it's our job to come up with a nice DX.  Why not start from a cean Nx monorepo and see ho we would do 
to have a Keycloak theme fit in there?  

Wether we have to modify the build tool or simply have a new documentation page is yet to determin.  
My intuition is there is probably something do do with [typescript paths](https://betterprogramming.pub/how-to-configure-path-aliases-with-typescript-8586dc0aa214) and https://github.com/justkey007/tsc-alias

**Comment by lordvlad** [comment]
I see. well I'll start with configurable directories for everything. I'll see then if theres anything to add, but I expect few adjustments required if any, as keycloakify is more of a post-processor turning a react app into ftl templates

**Comment by lordvlad** [comment]
I believe the discussion  arount vite support/integration has superceded this one, no?

**Comment by garronej** [comment]
> I believe the discussion arount vite support/integration has superceded this one, no?  

Yes

**Comment by garronej** [comment]
@adover Keycloakify 10 now officially supports monorepos integaration.  

Here is the guide for Nx: https://docs.keycloakify.dev/keycloakify-in-my-app/as-a-subproject-of-your-monorepo/nx-integrated-monorepo
